/**
 * Machine-readable "AI-generated" marking for the files /api/generate writes
 * (EU AI Act, Regulation 2024/1689, art. 50(2): outputs of a generative AI
 * system are "marked in a machine-readable format and detectable as
 * artificially generated or manipulated").
 *
 * What this does, per format, with no dependency and no re-encoding (the
 * pixels are never touched):
 *
 *   PNG   an iTXt "XML:com.adobe.xmp" chunk carrying an XMP packet, and a
 *         tEXt "ai-generated" = "true" chunk, inserted before the first IDAT
 *         (readers such as libvips only look for metadata ahead of the data).
 *   JPEG  an APP1 XMP segment, inserted after SOI (and after APP0/JFIF, which
 *         must stay first).
 *   WebP  an "XMP " chunk, with the VP8X header created or flagged for it.
 *
 * The XMP says what the IPTC standard says AI output should say:
 * Iptc4xmpExt:DigitalSourceType = trainedAlgorithmicMedia (or
 * compositeWithTrainedAlgorithmicMedia for an edit of a person's own image),
 * the vocabulary Google, Adobe, Meta and OpenAI read. No account, prompt or
 * person is written into the file: the marking says what made it, not who.
 *
 * What it deliberately does NOT do:
 *
 *   - Touch a file that already carries a C2PA manifest (PNG caBX, JPEG APP11
 *     JUMBF, WebP C2PA). The provider's signed provenance is the stronger
 *     marking, and inserting bytes would break its hash binding.
 *   - Video and audio (MP4, MP3, WAV…). Those are returned untouched; the
 *     providers that make them (Veo/Lyria with SynthID, and others) mark them
 *     at the source or not at all, and writing a container box safely needs a
 *     real muxer. See docs/pricing/LEGAL_CHECKLIST.md § AI Act.
 *
 * A malformed file is returned unchanged rather than "fixed": a marking step
 * must never be the reason a generation fails.
 */

export interface MarkingInput {
  /** The model that made it, e.g. "GPT Image 2". Written as the creator tool. */
  generator: string;
  /** True when the output is an edit of an image the person supplied. */
  edited?: boolean;
  /** The product name, e.g. "Alevr". */
  product: string;
}

export interface MarkingResult {
  bytes: Buffer;
  /** What happened, for logs and tests. */
  marked: "xmp" | "skipped-c2pa" | "skipped-unsupported" | "skipped-already" | "skipped-malformed";
}

export const IPTC_TRAINED_ALGORITHMIC = "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia";
export const IPTC_COMPOSITE_TRAINED_ALGORITHMIC =
  "http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia";

const XMP_NS_HEADER = "http://ns.adobe.com/xap/1.0/\0";
/** Present in every packet this module writes: the idempotence check. */
const OUR_MARK = "Iptc4xmpExt:DigitalSourceType";

function xmlEscape(value: string): string {
  return value.replace(/[<>&"']/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&apos;" })[c]!);
}

/** The XMP packet. Exported for tests. */
export function aiXmpPacket(input: MarkingInput): string {
  const source = input.edited ? IPTC_COMPOSITE_TRAINED_ALGORITHMIC : IPTC_TRAINED_ALGORITHMIC;
  const tool = xmlEscape(`${input.product} (${input.generator})`);
  const description = input.edited ? "Edited with generative AI" : "Generated by AI";
  return (
    '<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>' +
    '<x:xmpmeta xmlns:x="adobe:ns:meta/">' +
    '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">' +
    '<rdf:Description rdf:about=""' +
    ' xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/"' +
    ' xmlns:xmp="http://ns.adobe.com/xap/1.0/"' +
    ' xmlns:dc="http://purl.org/dc/elements/1.1/"' +
    ` Iptc4xmpExt:DigitalSourceType="${source}"` +
    ` xmp:CreatorTool="${tool}">` +
    `<dc:description><rdf:Alt><rdf:li xml:lang="x-default">${description}</rdf:li></rdf:Alt></dc:description>` +
    "</rdf:Description></rdf:RDF></x:xmpmeta>" +
    '<?xpacket end="r"?>'
  );
}

// ---------------------------------------------------------------------------
// PNG
// ---------------------------------------------------------------------------

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

let crcTable: Uint32Array | null = null;
function crc32(bytes: Uint8Array): number {
  if (!crcTable) {
    crcTable = new Uint32Array(256);
    for (let n = 0; n < 256; n += 1) {
      let c = n;
      for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
      crcTable[n] = c >>> 0;
    }
  }
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i += 1) crc = crcTable[(crc ^ bytes[i]!) & 0xff]! ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function pngChunk(type: string, data: Buffer): Buffer {
  const head = Buffer.alloc(8);
  head.writeUInt32BE(data.length, 0);
  head.write(type, 4, "latin1");
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([head.subarray(4), data])), 0);
  return Buffer.concat([head, data, crc]);
}

/** Every chunk as [type, start offset, total length], or null when malformed. */
function pngChunks(bytes: Buffer): Array<{ type: string; start: number; end: number }> | null {
  if (bytes.length < 8 || !bytes.subarray(0, 8).equals(PNG_SIGNATURE)) return null;
  const chunks: Array<{ type: string; start: number; end: number }> = [];
  let at = 8;
  while (at + 12 <= bytes.length) {
    const length = bytes.readUInt32BE(at);
    const type = bytes.toString("latin1", at + 4, at + 8);
    const end = at + 12 + length;
    if (end > bytes.length) return null;
    chunks.push({ type, start: at, end });
    at = end;
    if (type === "IEND") return chunks;
  }
  return null;
}

function markPng(bytes: Buffer, input: MarkingInput): MarkingResult {
  const chunks = pngChunks(bytes);
  if (!chunks) return { bytes, marked: "skipped-malformed" };
  if (chunks.some((c) => c.type === "caBX")) return { bytes, marked: "skipped-c2pa" };
  const hasOurXmp = chunks.some(
    (c) => c.type === "iTXt" && bytes.toString("latin1", c.start + 8, c.end - 4).includes(OUR_MARK)
  );
  if (hasOurXmp) return { bytes, marked: "skipped-already" };
  const idat = chunks.find((c) => c.type === "IDAT");
  if (!idat) return { bytes, marked: "skipped-malformed" };
  // iTXt: keyword \0 compression-flag(0) compression-method(0) language \0 translated \0 text (UTF-8).
  const itxt = Buffer.concat([
    Buffer.from("XML:com.adobe.xmp", "latin1"),
    Buffer.from([0, 0, 0, 0, 0]),
    Buffer.from(aiXmpPacket(input), "utf8"),
  ]);
  const text = Buffer.concat([Buffer.from("ai-generated", "latin1"), Buffer.from([0]), Buffer.from("true", "latin1")]);
  return {
    bytes: Buffer.concat([bytes.subarray(0, idat.start), pngChunk("iTXt", itxt), pngChunk("tEXt", text), bytes.subarray(idat.start)]),
    marked: "xmp",
  };
}

// ---------------------------------------------------------------------------
// JPEG
// ---------------------------------------------------------------------------

function markJpeg(bytes: Buffer, input: MarkingInput): MarkingResult {
  if (bytes.length < 4 || bytes[0] !== 0xff || bytes[1] !== 0xd8) return { bytes, marked: "skipped-malformed" };
  // Walk the marker segments up to the first scan, looking for C2PA (APP11)
  // and an existing XMP APP1, and for where APP0 ends.
  let at = 2;
  let insertAt = 2;
  while (at + 4 <= bytes.length) {
    if (bytes[at] !== 0xff) return { bytes, marked: "skipped-malformed" };
    const marker = bytes[at + 1]!;
    if (marker === 0xda || marker === 0xd9) break; // start of scan / end of image
    const length = bytes.readUInt16BE(at + 2);
    const end = at + 2 + length;
    if (end > bytes.length || length < 2) return { bytes, marked: "skipped-malformed" };
    if (marker === 0xeb) return { bytes, marked: "skipped-c2pa" };
    if (marker === 0xe1 && bytes.toString("latin1", at + 4, at + 4 + XMP_NS_HEADER.length) === XMP_NS_HEADER) {
      // One XMP segment per file; a second would be ignored by readers.
      return { bytes, marked: bytes.toString("utf8", at + 4, end).includes(OUR_MARK) ? "skipped-already" : "skipped-unsupported" };
    }
    if (marker === 0xe0 && insertAt === at) insertAt = end; // keep JFIF first
    at = end;
  }
  const payload = Buffer.concat([Buffer.from(XMP_NS_HEADER, "latin1"), Buffer.from(aiXmpPacket(input), "utf8")]);
  if (payload.length + 2 > 0xffff) return { bytes, marked: "skipped-unsupported" };
  const head = Buffer.from([0xff, 0xe1, 0, 0]);
  head.writeUInt16BE(payload.length + 2, 2);
  return { bytes: Buffer.concat([bytes.subarray(0, insertAt), head, payload, bytes.subarray(insertAt)]), marked: "xmp" };
}

// ---------------------------------------------------------------------------
// WebP
// ---------------------------------------------------------------------------

function riffChunk(fourcc: string, data: Buffer): Buffer {
  const head = Buffer.alloc(8);
  head.write(fourcc, 0, "latin1");
  head.writeUInt32LE(data.length, 4);
  return Buffer.concat(data.length % 2 ? [head, data, Buffer.from([0])] : [head, data]);
}

/** Canvas size and alpha of a simple-format WebP, read from its bitstream header. */
function simpleWebpGeometry(fourcc: string, data: Buffer): { width: number; height: number; alpha: boolean } | null {
  if (fourcc === "VP8L") {
    if (data.length < 5 || data[0] !== 0x2f) return null;
    const bits = data.readUInt32LE(1);
    return { width: (bits & 0x3fff) + 1, height: ((bits >>> 14) & 0x3fff) + 1, alpha: ((bits >>> 28) & 1) === 1 };
  }
  if (fourcc === "VP8 ") {
    if (data.length < 10 || data[3] !== 0x9d || data[4] !== 0x01 || data[5] !== 0x2a) return null;
    return { width: data.readUInt16LE(6) & 0x3fff, height: data.readUInt16LE(8) & 0x3fff, alpha: false };
  }
  return null;
}

function markWebp(bytes: Buffer, input: MarkingInput): MarkingResult {
  if (bytes.length < 20 || bytes.toString("latin1", 0, 4) !== "RIFF" || bytes.toString("latin1", 8, 12) !== "WEBP") {
    return { bytes, marked: "skipped-malformed" };
  }
  const chunks: Array<{ fourcc: string; start: number; end: number; data: Buffer }> = [];
  let at = 12;
  while (at + 8 <= bytes.length) {
    const fourcc = bytes.toString("latin1", at, at + 4);
    const size = bytes.readUInt32LE(at + 4);
    const end = at + 8 + size + (size % 2);
    if (at + 8 + size > bytes.length) return { bytes, marked: "skipped-malformed" };
    chunks.push({ fourcc, start: at, end: Math.min(end, bytes.length), data: bytes.subarray(at + 8, at + 8 + size) });
    at = end;
  }
  if (chunks.some((c) => c.fourcc === "C2PA")) return { bytes, marked: "skipped-c2pa" };
  if (chunks.some((c) => c.fourcc === "XMP ")) {
    const xmp = chunks.find((c) => c.fourcc === "XMP ")!;
    return { bytes, marked: xmp.data.toString("utf8").includes(OUR_MARK) ? "skipped-already" : "skipped-unsupported" };
  }

  const xmpChunk = riffChunk("XMP ", Buffer.from(aiXmpPacket(input), "utf8"));
  let body: Buffer;
  const vp8x = chunks.find((c) => c.fourcc === "VP8X");
  if (vp8x) {
    const header = Buffer.from(bytes.subarray(vp8x.start, vp8x.end));
    header[8] = header[8]! | 0x04; // XMP flag
    body = Buffer.concat([bytes.subarray(12, vp8x.start), header, bytes.subarray(vp8x.end), xmpChunk]);
  } else {
    const first = chunks[0];
    const geometry = first ? simpleWebpGeometry(first.fourcc, first.data) : null;
    if (!geometry || geometry.width < 1 || geometry.height < 1) return { bytes, marked: "skipped-malformed" };
    const data = Buffer.alloc(10);
    data[0] = 0x04 | (geometry.alpha ? 0x10 : 0);
    data.writeUIntLE(geometry.width - 1, 4, 3);
    data.writeUIntLE(geometry.height - 1, 7, 3);
    body = Buffer.concat([riffChunk("VP8X", data), bytes.subarray(12), xmpChunk]);
  }
  const head = Buffer.alloc(12);
  head.write("RIFF", 0, "latin1");
  head.writeUInt32LE(body.length + 4, 4);
  head.write("WEBP", 8, "latin1");
  return { bytes: Buffer.concat([head, body]), marked: "xmp" };
}

// ---------------------------------------------------------------------------

/** Mark one generated file. Never throws; an unknown or broken file comes back unchanged. */
export function markAiGenerated(bytes: Buffer, mimeType: string, input: MarkingInput): MarkingResult {
  try {
    const type = mimeType.toLowerCase();
    if (type === "image/png") return markPng(bytes, input);
    if (type === "image/jpeg" || type === "image/jpg") return markJpeg(bytes, input);
    if (type === "image/webp") return markWebp(bytes, input);
    return { bytes, marked: "skipped-unsupported" };
  } catch {
    return { bytes, marked: "skipped-malformed" };
  }
}
