// Generated by `npm run models:sync -- --apply`. Do not edit by hand: fix the
// parser in scripts/model-sync/ or wait for the lab to fix its page, then re-run.
//
// Every rate below was read from the lab's own pricing page on the date in
// `verified`, from the URL in `source` (docs/models/SYNC.md). pricing.ts and
// model-metrics.ts read this table FIRST and fall back to their hand-coded
// rules only for a model it does not list.

export interface OfficialRateEntry {
  /** USD per 1M tokens. */
  input: number;
  output: number;
  cacheRead?: number;
  cacheWrite?: number;
  cacheWrite5m?: number;
  cacheWrite1h?: number;
  /** The lab's long-context surcharge; null = it publishes none for this model. */
  longContext?: { threshold: number; inclusive: boolean; inputMultiplier: number; outputMultiplier: number } | null;
  /** The lab's fast / priority tier; null = the lab has one and this model is not in it. */
  fast?: { input: number; output: number } | null;
  /** OpenAI's Ultrafast service tier, same convention as `fast`. */
  ultrafast?: { input: number; output: number } | null;
  source: string;
  verified: string;
}

export const OFFICIAL_RATES: Readonly<Record<string, OfficialRateEntry>> = {};
