// Generated by `npm run models:sync -- --apply`. Do not edit by hand: fix the
// parser in scripts/model-sync/ or wait for the lab to fix its page, then re-run.
//
// Every rate below was read from the lab's own pricing page on the date in
// `verified`, from the URL in `source` (docs/models/SYNC.md). pricing.ts and
// model-metrics.ts read this table FIRST and fall back to their hand-coded
// rules only for a model it does not list.

export interface OfficialRateEntry {
  /** USD per 1M tokens. */
  input: number;
  output: number;
  cacheRead?: number;
  cacheWrite?: number;
  cacheWrite5m?: number;
  cacheWrite1h?: number;
  /** The lab's long-context surcharge; null = it publishes none for this model. */
  longContext?: { threshold: number; inclusive: boolean; inputMultiplier: number; outputMultiplier: number } | null;
  /** The lab's fast / priority tier; null = the lab has one and this model is not in it. */
  fast?: { input: number; output: number } | null;
  /** OpenAI's Ultrafast service tier, same convention as `fast`. */
  ultrafast?: { input: number; output: number } | null;
  source: string;
  verified: string;
}

export const OFFICIAL_RATES: Readonly<Record<string, OfficialRateEntry>> = {
  "anthropic:claude-fable-5": {"input":10,"output":50,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":1,"cacheWrite5m":12.5,"cacheWrite1h":20,"longContext":null,"fast":null},
  "anthropic:claude-fable-5-1": {"input":10,"output":50,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.25,"cacheWrite5m":12.5,"cacheWrite1h":20,"longContext":null,"fast":null},
  "anthropic:claude-haiku-4-5": {"input":1,"output":5,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.1,"cacheWrite5m":1.25,"cacheWrite1h":2,"longContext":null,"fast":null},
  "anthropic:claude-haiku-5-5": {"input":0.1,"output":0.5,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.01,"cacheWrite5m":0.125,"cacheWrite1h":0.2,"longContext":{"threshold":100000,"inclusive":false,"inputMultiplier":5,"outputMultiplier":5},"fast":null},
  "anthropic:claude-opus-4-5": {"input":5,"output":25,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.5,"cacheWrite5m":6.25,"cacheWrite1h":10,"longContext":null,"fast":null},
  "anthropic:claude-opus-4-6": {"input":5,"output":25,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.5,"cacheWrite5m":6.25,"cacheWrite1h":10,"longContext":null,"fast":null},
  "anthropic:claude-opus-4-7": {"input":5,"output":25,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.5,"cacheWrite5m":6.25,"cacheWrite1h":10,"longContext":null,"fast":null},
  "anthropic:claude-opus-4-8": {"input":5,"output":25,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.5,"cacheWrite5m":6.25,"cacheWrite1h":10,"longContext":null,"fast":{"input":10,"output":50}},
  "anthropic:claude-opus-5": {"input":5,"output":25,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.5,"cacheWrite5m":6.25,"cacheWrite1h":10,"longContext":null,"fast":{"input":10,"output":50}},
  "anthropic:claude-opus-5-5": {"input":4,"output":20,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.2,"cacheWrite5m":5,"cacheWrite1h":8,"longContext":null,"fast":{"input":8,"output":40}},
  "anthropic:claude-sonnet-4-5": {"input":3,"output":15,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.3,"cacheWrite5m":3.75,"cacheWrite1h":6,"longContext":null,"fast":null},
  "anthropic:claude-sonnet-4-6": {"input":3,"output":15,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.3,"cacheWrite5m":3.75,"cacheWrite1h":6,"longContext":null,"fast":null},
  "anthropic:claude-sonnet-5": {"input":2,"output":10,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.2,"cacheWrite5m":2.5,"cacheWrite1h":4,"longContext":null,"fast":null},
  "anthropic:claude-sonnet-5-5": {"input":2,"output":10,"source":"https://platform.claude.com/docs/en/about-claude/pricing","verified":"2026-10-10","cacheRead":0.1,"cacheWrite5m":2.5,"cacheWrite1h":4,"longContext":null,"fast":null},
  "deepseek:deepseek-flash": {"input":0.15,"output":0.6,"source":"https://api-docs.deepseek.com/quick_start/pricing","verified":"2026-10-10","cacheRead":0.003,"longContext":null},
  "deepseek:deepseek-v4-pro": {"input":0.66,"output":1.98,"source":"https://api-docs.deepseek.com/quick_start/pricing","verified":"2026-10-10","cacheRead":0.022,"longContext":null},
  "google:gemini-2.5-pro": {"input":1.25,"output":10,"source":"https://ai.google.dev/gemini-api/docs/pricing","verified":"2026-10-10","cacheRead":0.125,"longContext":{"threshold":200000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5}},
  "google:gemini-3-flash-preview": {"input":0.5,"output":3,"source":"https://ai.google.dev/gemini-api/docs/pricing","verified":"2026-10-10","cacheRead":0.05,"longContext":null},
  "google:gemini-3.1-flash-lite": {"input":0.25,"output":1.5,"source":"https://ai.google.dev/gemini-api/docs/pricing","verified":"2026-10-10","cacheRead":0.025,"longContext":null},
  "google:gemini-3.1-pro-preview": {"input":2,"output":12,"source":"https://ai.google.dev/gemini-api/docs/pricing","verified":"2026-10-10","cacheRead":0.2,"longContext":{"threshold":200000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5}},
  "google:gemini-3.5-flash-lite": {"input":0.3,"output":2.5,"source":"https://ai.google.dev/gemini-api/docs/pricing","verified":"2026-10-10","cacheRead":0.03,"longContext":null},
  "mimo:mimo-v2.5": {"input":0.14,"output":0.28,"source":"https://mimo.mi.com/docs/en-US/price/pay-as-you-go","verified":"2026-10-10","cacheRead":0.0028,"longContext":null},
  "mimo:mimo-v2.5-pro": {"input":0.435,"output":0.87,"source":"https://mimo.mi.com/docs/en-US/price/pay-as-you-go","verified":"2026-10-10","cacheRead":0.0036,"longContext":null},
  "mimo:mimo-v2.6-flash": {"input":0.14,"output":0.28,"source":"https://mimo.mi.com/docs/en-US/price/pay-as-you-go","verified":"2026-10-10","cacheRead":0.0028,"longContext":null},
  "mimo:mimo-v2.6-pro": {"input":0.435,"output":0.87,"source":"https://mimo.mi.com/docs/en-US/price/pay-as-you-go","verified":"2026-10-10","cacheRead":0.0036,"longContext":null},
  "mimo:mimo-v2.6-pro-ultraspeed": {"input":4.35,"output":8.7,"source":"https://mimo.mi.com/docs/en-US/price/pay-as-you-go","verified":"2026-10-10","cacheRead":0.036,"longContext":null},
  "minimax:MiniMax-M2.5": {"input":0.3,"output":1.2,"source":"https://platform.minimax.io/docs/guides/pricing-paygo","verified":"2026-10-10","cacheRead":0.03,"longContext":null},
  "minimax:MiniMax-M2.7": {"input":0.3,"output":1.2,"source":"https://platform.minimax.io/docs/guides/pricing-paygo","verified":"2026-10-10","cacheRead":0.06,"longContext":null},
  "minimax:MiniMax-M2.7-highspeed": {"input":0.6,"output":2.4,"source":"https://platform.minimax.io/docs/guides/pricing-paygo","verified":"2026-10-10","cacheRead":0.06,"longContext":null},
  "minimax:MiniMax-M3": {"input":0.3,"output":1.2,"source":"https://platform.minimax.io/docs/guides/pricing-paygo","verified":"2026-10-10","cacheRead":0.06,"longContext":{"threshold":512000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":2}},
  "mistral:codestral-latest": {"input":0.3,"output":0.9,"source":"https://docs.mistral.ai/models/codestral-25-08","verified":"2026-10-10","longContext":null},
  "mistral:ministral-14b-latest": {"input":0.2,"output":0.2,"source":"https://docs.mistral.ai/models/ministral-3-14b-25-12","verified":"2026-10-10","longContext":null},
  "mistral:ministral-3b-latest": {"input":0.1,"output":0.1,"source":"https://docs.mistral.ai/models/ministral-3-3b-25-12","verified":"2026-10-10","longContext":null},
  "mistral:ministral-8b-latest": {"input":0.15,"output":0.15,"source":"https://docs.mistral.ai/models/ministral-3-8b-25-12","verified":"2026-10-10","longContext":null},
  "mistral:mistral-large-4": {"input":1.36,"output":4.18,"source":"https://docs.mistral.ai/models/mistral-large-4-0","verified":"2026-10-10","cacheRead":0.14,"longContext":null},
  "mistral:mistral-large-latest": {"input":0.5,"output":1.5,"source":"https://docs.mistral.ai/models/mistral-large-3-25-12","verified":"2026-10-10","longContext":null},
  "mistral:mistral-medium-latest": {"input":1.5,"output":7.5,"source":"https://docs.mistral.ai/models/mistral-medium-3-5-26-04","verified":"2026-10-10","longContext":null},
  "mistral:mistral-small-latest": {"input":0.15,"output":0.6,"source":"https://docs.mistral.ai/models/mistral-small-4-0-26-03","verified":"2026-10-10","longContext":null},
  "moonshot:kimi-k2.6": {"input":0.95,"output":4,"source":"https://platform.kimi.ai/docs/pricing/chat","verified":"2026-10-10","cacheRead":0.16,"longContext":null},
  "moonshot:kimi-k2.7-code": {"input":0.95,"output":4,"source":"https://platform.kimi.ai/docs/pricing/chat","verified":"2026-10-10","cacheRead":0.19,"longContext":null},
  "moonshot:kimi-k2.7-code-highspeed": {"input":1.9,"output":8,"source":"https://platform.kimi.ai/docs/pricing/chat","verified":"2026-10-10","cacheRead":0.38,"longContext":null},
  "moonshot:kimi-k3": {"input":3,"output":15,"source":"https://platform.kimi.ai/docs/pricing/chat","verified":"2026-10-10","cacheRead":0.3,"longContext":null},
  "openai:gpt-3.5-turbo": {"input":0.5,"output":1.5,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","longContext":null,"fast":null,"ultrafast":null},
  "openai:gpt-4o": {"input":2.5,"output":10,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":1.25,"longContext":null,"fast":{"input":4.25,"output":17},"ultrafast":null},
  "openai:gpt-4o-mini": {"input":0.15,"output":0.6,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.075,"longContext":null,"fast":{"input":0.25,"output":1},"ultrafast":null},
  "openai:gpt-5": {"input":1.25,"output":10,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.125,"longContext":null,"fast":{"input":2.5,"output":20},"ultrafast":null},
  "openai:gpt-5-mini": {"input":0.25,"output":2,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.025,"longContext":null,"fast":{"input":0.45,"output":3.6},"ultrafast":null},
  "openai:gpt-5.1": {"input":1.25,"output":10,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.125,"longContext":null,"fast":{"input":2.5,"output":20},"ultrafast":null},
  "openai:gpt-5.2": {"input":1.75,"output":14,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.175,"longContext":null,"fast":{"input":3.5,"output":28},"ultrafast":null},
  "openai:gpt-5.2-pro": {"input":21,"output":168,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","longContext":null,"fast":null,"ultrafast":null},
  "openai:gpt-5.4": {"input":2.5,"output":15,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.25,"longContext":{"threshold":272000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5},"fast":{"input":5,"output":30},"ultrafast":null},
  "openai:gpt-5.4-mini": {"input":0.75,"output":4.5,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.075,"longContext":null,"fast":{"input":1.5,"output":9},"ultrafast":null},
  "openai:gpt-5.4-nano": {"input":0.2,"output":1.25,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.02,"longContext":null,"fast":null,"ultrafast":null},
  "openai:gpt-5.4-pro": {"input":30,"output":180,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","longContext":{"threshold":272000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5},"fast":null,"ultrafast":null},
  "openai:gpt-5.5": {"input":5,"output":30,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.5,"longContext":{"threshold":272000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5},"fast":{"input":12.5,"output":75},"ultrafast":null},
  "openai:gpt-5.5-pro": {"input":30,"output":180,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","longContext":{"threshold":272000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5},"fast":null,"ultrafast":null},
  "openai:gpt-5.6-luna": {"input":0.2,"output":1.2,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.02,"cacheWrite":0.25,"longContext":{"threshold":272000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5},"fast":{"input":0.4,"output":2.4},"ultrafast":null},
  "openai:gpt-5.6-sol": {"input":4,"output":20,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.4,"cacheWrite":5,"longContext":{"threshold":272000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5},"fast":{"input":8,"output":40},"ultrafast":null},
  "openai:gpt-5.6-terra": {"input":2,"output":12,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.2,"cacheWrite":2.5,"longContext":{"threshold":272000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5},"fast":{"input":4,"output":24},"ultrafast":null},
  "openai:gpt-6-astra": {"input":10,"output":50,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":1,"cacheWrite":12.5,"longContext":{"threshold":272000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5},"fast":{"input":20,"output":100},"ultrafast":{"input":60,"output":300}},
  "openai:gpt-6-luna": {"input":0.1,"output":0.5,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.01,"cacheWrite":0.125,"longContext":{"threshold":272000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5},"fast":{"input":0.2,"output":1},"ultrafast":null},
  "openai:gpt-6-sol": {"input":2,"output":10,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.2,"cacheWrite":2.5,"longContext":{"threshold":272000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5},"fast":{"input":4,"output":20},"ultrafast":null},
  "openai:gpt-6.1-sol": {"input":2,"output":10,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.1,"cacheWrite":2.5,"longContext":{"threshold":272000,"inclusive":false,"inputMultiplier":2,"outputMultiplier":1.5},"fast":{"input":4,"output":20},"ultrafast":{"input":12,"output":60}},
  "openai:o1": {"input":15,"output":60,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":7.5,"longContext":null,"fast":null,"ultrafast":null},
  "openai:o3": {"input":2,"output":8,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.5,"longContext":null,"fast":{"input":3.5,"output":14},"ultrafast":null},
  "openai:o3-mini": {"input":1.1,"output":4.4,"source":"https://developers.openai.com/api/docs/pricing","verified":"2026-10-10","cacheRead":0.55,"longContext":null,"fast":null,"ultrafast":null},
  "qwen:qwen-max": {"input":1.6,"output":6.4,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3-235b-a22b": {"input":0.7,"output":2.8,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3-30b-a3b": {"input":0.2,"output":0.8,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3-coder-plus": {"input":1,"output":5,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3-vl-flash": {"input":0.05,"output":0.4,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3-vl-plus": {"input":0.2,"output":1.6,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3.5-flash": {"input":0.1,"output":0.4,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3.5-plus": {"input":0.4,"output":2.4,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3.6-flash": {"input":0.25,"output":1.5,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3.6-plus": {"input":0.5,"output":3,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3.7-flash": {"input":0.03,"output":0.13,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3.7-max": {"input":2.5,"output":7.5,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3.7-plus": {"input":0.4,"output":1.6,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3.8-flash": {"input":0.15,"output":0.47,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3.8-max": {"input":2,"output":6,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10"},
  "qwen:qwen3.8-omni-flash": {"input":0.15,"output":0.47,"source":"https://www.alibabacloud.com/help/en/model-studio/model-pricing","verified":"2026-10-10","cacheRead":0.016,"longContext":null},
  "xai:grok-4.20-0309-non-reasoning": {"input":1.25,"output":2.5,"source":"https://docs.x.ai/developers/models","verified":"2026-10-10","cacheRead":0.2,"longContext":{"threshold":200000,"inclusive":true,"inputMultiplier":2,"outputMultiplier":2}},
  "xai:grok-4.20-0309-reasoning": {"input":1.25,"output":2.5,"source":"https://docs.x.ai/developers/models","verified":"2026-10-10","cacheRead":0.2,"longContext":{"threshold":200000,"inclusive":true,"inputMultiplier":2,"outputMultiplier":2}},
  "xai:grok-4.20-multi-agent-0309": {"input":1.25,"output":2.5,"source":"https://docs.x.ai/developers/models","verified":"2026-10-10","cacheRead":0.2,"longContext":{"threshold":200000,"inclusive":true,"inputMultiplier":2,"outputMultiplier":2}},
  "xai:grok-4.3": {"input":1.25,"output":2.5,"source":"https://docs.x.ai/developers/models","verified":"2026-10-10","cacheRead":0.2,"longContext":{"threshold":200000,"inclusive":true,"inputMultiplier":2,"outputMultiplier":2}},
  "xai:grok-4.5": {"input":2,"output":6,"source":"https://docs.x.ai/developers/models","verified":"2026-10-10","cacheRead":0.3,"longContext":{"threshold":200000,"inclusive":true,"inputMultiplier":2,"outputMultiplier":2}},
  "xai:grok-4.6": {"input":2,"output":6,"source":"https://docs.x.ai/developers/models","verified":"2026-10-10","cacheRead":0.5,"longContext":{"threshold":200000,"inclusive":true,"inputMultiplier":2,"outputMultiplier":2}},
  "xai:grok-4.7": {"input":2,"output":6,"source":"https://docs.x.ai/developers/models","verified":"2026-10-10","cacheRead":0.5,"longContext":{"threshold":200000,"inclusive":true,"inputMultiplier":2,"outputMultiplier":2}},
  "xai:grok-build-0.1": {"input":1,"output":2,"source":"https://docs.x.ai/developers/models","verified":"2026-10-10","cacheRead":0.2,"longContext":{"threshold":200000,"inclusive":true,"inputMultiplier":2,"outputMultiplier":2}},
  "zhipu:glm-4-32b-0414-128k": {"input":0.1,"output":0.1,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","longContext":null},
  "zhipu:glm-4.5-air": {"input":0.2,"output":1.1,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.03,"longContext":null},
  "zhipu:glm-4.5-airx": {"input":1.1,"output":4.5,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.22,"longContext":null},
  "zhipu:glm-4.5-x": {"input":2.2,"output":8.9,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.45,"longContext":null},
  "zhipu:glm-4.5v": {"input":0.6,"output":1.8,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.11,"longContext":null},
  "zhipu:glm-4.6": {"input":0.6,"output":2.2,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.11,"longContext":null},
  "zhipu:glm-4.6v": {"input":0.3,"output":0.9,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.05,"longContext":null},
  "zhipu:glm-4.6v-flashx": {"input":0.04,"output":0.4,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.004,"longContext":null},
  "zhipu:glm-4.7": {"input":0.6,"output":2.2,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.11,"longContext":null},
  "zhipu:glm-4.7-flashx": {"input":0.07,"output":0.4,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.01,"longContext":null},
  "zhipu:glm-5": {"input":1,"output":3.2,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.2,"longContext":null},
  "zhipu:glm-5.1": {"input":1.4,"output":4.4,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.26,"longContext":null},
  "zhipu:glm-5.2": {"input":1.4,"output":4.4,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.26,"longContext":null},
  "zhipu:glm-5.3": {"input":1.4,"output":4.4,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.26,"longContext":null},
  "zhipu:glm-5.3-flash": {"input":0.15,"output":0.5,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.03,"longContext":null},
  "zhipu:glm-5.3-flashx": {"input":0.37,"output":1.25,"source":"https://docs.z.ai/guides/overview/pricing","verified":"2026-10-10","cacheRead":0.075,"longContext":null},
};
