// AUTO-GENERATED by scripts/sync-models.ts — do not edit by hand.
// Dry run: `npm run sync:models` · regenerate: `npm run sync:models:write`.
import type { Provider } from "@/lib/providers";

export interface DiscoveredModel {
  provider: Provider;
  /** Bare provider model id, exactly as the provider API expects it. */
  id: string;
  name: string;
}

/** ISO timestamp of the last successful `--write` sync (null = never synced). */
export const SYNC_STAMP: string | null = "2026-07-17T06:30:02.900Z";

/** Genuinely new chat models found on providers' live model APIs. Dumb data —
 *  plan/vision/reasoning/cost/webSearch are derived in models.ts via the
 *  guess* helpers, pending hand-curation. */
export const DISCOVERED: DiscoveredModel[] = [];

/** Canonical "provider:providerModel" ids of curated CHAT models the live API
 *  no longer serves — hidden from pickers; stored ids migrate in models.ts. */
export const UNAVAILABLE: string[] = [];
