/**
 * Continuum: the Alevr master mark as construction data.
 *
 * Pure data and pure functions: no JSX, no React, no imports. Plain Node can
 * import this file with type stripping only (the export and native projection
 * scripts read it), so: no enums, no namespaces, no parameter properties.
 *
 * Generated by the brand lane's construction tooling from the owner-selected
 * raster (docs/rework/brand/assets/alevr-continuum-symbol.png). The method,
 * the evidence and the numbers are in docs/rework/brand/CONTINUUM_GEOMETRY.md.
 * Edit the construction there and regenerate; do not hand-edit coordinates.
 *
 * THE SPACE. One unit is 4.5 px of the 1254 px source raster. The origin is
 * the centre of the aperture: the largest circle that fits between the blades,
 * radius 24 units. The broad path width is 48 units (one aperture diameter),
 * which is also the clear space; the wordmark sits 1.5 path widths away.
 *
 * THE BLADES. Four separate closed paths, numbered clockwise from the upper
 * sweep, the order the thinking handoff walks. Each runs clockwise from its
 * outer trailing tip. On-curve nodes sit only at the two pointed tips and at
 * the outline's horizontal and vertical extrema, so every extremum node has an
 * axis-aligned handle and the bounding box is read straight off the nodes.
 *
 * THE RULES the solver held while fitting the silhouette:
 *   1. Nodes on the half-unit lattice; handles to 0.01.
 *   2. G2 at every smooth node: the curvature arriving equals the curvature
 *      leaving (within about 3%), so no highlight kinks where two spans meet.
 *   3. No handle reaches past the point where its span's end tangents meet,
 *      and no span has an inflection.
 *   4. Tips pinned to the raster's measured tip points: silhouette overlap is
 *      blind to hair-thin tips, so they are never traded away for area.
 *
 * OPTICAL MASTERS (16, 20, 24, 32 px). Below 32 px the master's channels fall
 * under a pixel and the blades fuse, so each small size has its own drawing,
 * chosen by the mark's rendered width in DEVICE pixels (continuumDrawingSet:
 * a 16 px mark on a 2x screen is 32 device px and draws the 32 master).
 *   16 and 20 move whole blades: every blade keeps the master's exact outline
 *   (so its round head, its joins and its edges are the master's) and only its
 *   placement changes, a translation, a turn of at most 4.3 degrees about its
 *   own centroid and a uniform scale of at least 0.97, chosen by a search that
 *   keeps the drawing as close to the master as it can while every channel
 *   opens to `channel` px. Then the outer extrema snap to whole pixels.
 *   24 and 32, where the channels need far less, move outline points inward
 *   by softplus((w - d) / 2), d being the distance to the nearest other blade,
 *   and refit on the outline's own extrema.
 * Every optical master places the box slightly above centre because the visual
 * mass sits below the box centre; `rows` is the band of whole pixel rows the
 * ink occupies (the tight crop).
 */

export type ContinuumPoint = readonly [number, number];
export type ContinuumNodeKind = "tip" | "x-extremum" | "y-extremum";
export type ContinuumBladeId = "blade-1" | "blade-2" | "blade-3" | "blade-4";
export type ContinuumNode = { readonly kind: ContinuumNodeKind; readonly p: ContinuumPoint };
export type ContinuumSegment = { readonly c1: ContinuumPoint; readonly c2: ContinuumPoint; readonly to: ContinuumPoint };
export type ContinuumBlade = {
  readonly id: ContinuumBladeId;
  readonly name: string;
  /** nodes[i] is where segments[i] starts; the outline closes back to nodes[0]. */
  readonly nodes: readonly ContinuumNode[];
  readonly segments: readonly ContinuumSegment[];
};
export type ContinuumOpticalSize = 16 | 20 | 24 | 32;
export type ContinuumDrawing = {
  readonly viewBox: string;
  readonly paths: readonly { readonly id: ContinuumBladeId; readonly d: string }[];
};
/** One drawing per device-pixel class: `hiDpi` (for 1.5 dppx and up) is null when it would be the same drawing. */
export type ContinuumDrawingSet = { readonly base: ContinuumDrawing; readonly hiDpi: ContinuumDrawing | null };
export type ContinuumOptical = {
  /** The opened channel minimum, px. */
  readonly channel: number;
  /** How the master was adapted: whole blades moved ("placement") or outline points inset ("inset"). */
  readonly method: "placement" | "inset";
  /** The whole pixel rows the ink occupies, [top, bottom): the tight crop. */
  readonly rows: readonly [number, number];
  readonly blades: readonly { readonly id: ContinuumBladeId; readonly d: string }[];
};

/**
 * Where the master sits on the source raster: master (x, y) is raster pixel
 * (origin + unitPx * (x, y)). Evidence only: the fidelity check uses it.
 */
export const CONTINUUM_SOURCE = {
  file: "docs/rework/brand/assets/alevr-continuum-symbol.png",
  size: 1254,
  origin: [618, 656],
  unitPx: 4.5,
} as const;

/** Clockwise from the upper sweep: the order the thinking handoff passes along. */
export const CONTINUUM_BLADE_ORDER: readonly ContinuumBladeId[] = ["blade-1", "blade-2", "blade-3", "blade-4"];

/** The mark's tight bounds in master units (read from the extremum nodes). */
export const CONTINUUM_BOUNDS = { x: -112, y: -82.5, width: 240.5, height: 164 } as const;

/** The aperture: the largest empty circle between the blades. Its centre is the origin. */
export const CONTINUUM_APERTURE = { cx: 0, cy: 0, r: 24 } as const;

/** Broad path width (one aperture diameter). Clear space is one path width on every side. */
export const CONTINUUM_PATH_WIDTH = 48;

/**
 * A square box around the mark for icon-style use at sizes without an optical
 * master: centred horizontally, lifted 2 units so the visual mass reads centred.
 */
export const CONTINUUM_SQUARE_VIEWBOX = "-112 -118.75 240.5 240.5";

export const CONTINUUM_MASTER: readonly ContinuumBlade[] = [
  {
    id: "blade-1",
    name: "upper sweep",
    nodes: [
      { kind: "tip", p: [-112, 3.5] },
      { kind: "y-extremum", p: [26.5, -82.5] },
      { kind: "x-extremum", p: [50.5, -58.5] },
      { kind: "tip", p: [25, -1.5] },
      { kind: "y-extremum", p: [-10.5, -36] },
    ],
    segments: [
      { c1: [-84.35, -27.94], c2: [-13.76, -82.5], to: [26.5, -82.5] },
      { c1: [43.31, -82.5], c2: [50.5, -72.85], to: [50.5, -58.5] },
      { c1: [50.5, -38.6], c2: [36.9, -14.5], to: [25, -1.5] },
      { c1: [23.85, -22.04], c2: [16.3, -36], to: [-10.5, -36] },
      { c1: [-43.82, -36], c2: [-82.1, -15], to: [-112, 3.5] },
    ],
  },
  {
    id: "blade-2",
    name: "right fin",
    nodes: [
      { kind: "tip", p: [59, -57] },
      { kind: "x-extremum", p: [105, 9] },
      { kind: "y-extremum", p: [48, 36.5] },
      { kind: "tip", p: [1.5, 29] },
    ],
    segments: [
      { c1: [74.66, -43.62], c2: [105, -10.78], to: [105, 9] },
      { c1: [105, 31.9], c2: [65.4, 36.5], to: [48, 36.5] },
      { c1: [35.17, 36.5], c2: [10.75, 34], to: [1.5, 29] },
      { c1: [28.98, 9.77], c2: [61, -21.25], to: [59, -57] },
    ],
  },
  {
    id: "blade-3",
    name: "lower sweep",
    nodes: [
      { kind: "tip", p: [128.5, 37.5] },
      { kind: "y-extremum", p: [-4, 81.5] },
      { kind: "x-extremum", p: [-43.5, 47.5] },
      { kind: "tip", p: [-35, 16.5] },
      { kind: "y-extremum", p: [26, 50] },
    ],
    segments: [
      { c1: [98.2, 57.02], c2: [31.04, 81.5], to: [-4, 81.5] },
      { c1: [-26.37, 81.5], c2: [-43.5, 71.5], to: [-43.5, 47.5] },
      { c1: [-43.5, 36.65], c2: [-40, 26.3], to: [-35, 16.5] },
      { c1: [-33.67, 47.5], c2: [2.03, 50], to: [26, 50] },
      { c1: [59.9, 50], c2: [96.67, 45], to: [128.5, 37.5] },
    ],
  },
  {
    id: "blade-4",
    name: "left fin",
    nodes: [
      { kind: "tip", p: [-50.5, 65.5] },
      { kind: "x-extremum", p: [-101, 19.5] },
      { kind: "tip", p: [-13, -20.5] },
      { kind: "x-extremum", p: [-54.5, 49] },
    ],
    segments: [
      { c1: [-69.78, 62.02], c2: [-101, 38.75], to: [-101, 19.5] },
      { c1: [-101, -8.97], c2: [-31.81, -22.6], to: [-13, -20.5] },
      { c1: [-29.15, -5.47], c2: [-54.5, 22.5], to: [-54.5, 49] },
      { c1: [-54.5, 55.45], c2: [-53, 59.3], to: [-50.5, 65.5] },
    ],
  },
];

/** Per-size optical masters in pixel space (viewBox 0 0 size size). */
export const CONTINUUM_OPTICAL: Readonly<Record<ContinuumOpticalSize, ContinuumOptical>> = {
  16: {
    channel: 1.3,
    method: "placement",
    rows: [2, 13],
    blades: [
      { id: "blade-1", d: "M-0.02 6.614C1.801 4.83 6.334 1.837 8.778 2.02C9.798 2.096 10.191 2.714 10.126 3.585C10.036 4.793 9.101 6.195 8.32 6.93C8.343 5.678 7.948 4.796 6.321 4.675C4.298 4.524 1.879 5.626 -0.02 6.614Z" },
      { id: "blade-2", d: "M11.373 4.165C12.293 5.036 14.054 7.147 13.993 8.362C13.921 9.769 11.475 9.928 10.406 9.873C9.618 9.833 8.126 9.604 7.573 9.268C9.321 8.172 11.385 6.367 11.373 4.165Z" },
      { id: "blade-3", d: "M15.7 10.677C13.799 11.786 9.636 13.098 7.499 13.004C6.134 12.943 5.117 12.287 5.181 10.823C5.211 10.162 5.452 9.54 5.783 8.955C5.781 10.85 7.952 11.099 9.414 11.163C11.482 11.255 13.738 11.049 15.7 10.677Z" },
      { id: "blade-4", d: "M3.917 11.487C2.709 11.257 0.764 9.777 0.776 8.569C0.793 6.782 5.144 5.97 6.323 6.113C5.301 7.046 3.692 8.786 3.676 10.449C3.672 10.854 3.764 11.097 3.917 11.487Z" },
    ],
  },
  20: {
    channel: 1.15,
    method: "placement",
    rows: [2, 17],
    blades: [
      { id: "blade-1", d: "M-0.023 9.764C2.191 7.254 7.841 2.902 11.059 2.907C12.403 2.91 12.977 3.682 12.975 4.829C12.972 6.42 11.882 8.345 10.929 9.382C10.84 7.74 10.238 6.623 8.096 6.62C5.432 6.615 2.369 8.289 -0.023 9.764Z" },
      { id: "blade-2", d: "M14.278 5.396C15.546 6.484 18.001 9.154 17.997 10.758C17.992 12.616 14.779 12.981 13.368 12.978C12.327 12.975 10.346 12.768 9.597 12.36C11.83 10.806 14.434 8.296 14.278 5.396Z" },
      { id: "blade-3", d: "M19.945 13.095C17.545 14.721 12.189 16.813 9.372 16.878C7.573 16.919 6.177 16.146 6.133 14.216C6.113 13.344 6.375 12.505 6.759 11.708C6.923 14.198 9.799 14.333 11.726 14.289C14.452 14.227 17.4 13.757 19.945 13.095Z" },
      { id: "blade-4", d: "M5.099 15.167C3.552 14.91 1.025 13.081 1.004 11.54C0.972 9.26 6.498 8.091 8.007 8.238C6.73 9.46 4.731 11.728 4.761 13.85C4.768 14.367 4.892 14.674 5.099 15.167Z" },
    ],
  },
  24: {
    channel: 1,
    method: "inset",
    rows: [3, 20],
    blades: [
      { id: "blade-1", d: "M-0.002 12.216C2.79 9.176 9.628 3.634 13.828 3.634C15.087 3.634 16.159 4.285 16.159 5.632C16.159 7.997 15.216 9.75 13.724 11.517C13.603 11.067 13.558 10.636 13.409 10.201C12.885 8.673 11.6 8.274 10.113 8.274C7.748 8.274 4.493 9.54 2.439 10.686C1.623 11.141 0.795 11.711 -0.002 12.216Z" },
      { id: "blade-2", d: "M17.141 6.311C18.608 7.361 21.654 10.878 21.654 12.797C21.654 15.081 17.576 15.504 15.912 15.504C14.63 15.504 12.497 15.295 11.339 14.768C12.233 14.061 13.546 13.103 14.353 12.32C15.834 10.882 17.186 8.436 17.141 6.311Z" },
      { id: "blade-3", d: "M24 15.609C20.924 17.545 14.373 20 10.764 20C8.573 20 6.858 19.019 6.858 16.63C6.858 15.607 7.189 14.734 7.648 13.84C7.797 14.342 7.93 14.782 8.249 15.209C9.406 16.754 12.083 16.857 13.847 16.857C17.213 16.857 20.723 16.371 24 15.609Z" },
      { id: "blade-4", d: "M6.141 18.43C5.562 18.209 5.359 18.221 4.699 17.892C3.319 17.205 1.098 15.489 1.098 13.804C1.098 11.232 7.669 9.628 9.873 9.827C7.943 11.646 5.716 13.975 5.716 16.776C5.716 17.356 5.872 17.925 6.141 18.43Z" },
    ],
  },
  32: {
    channel: 1,
    method: "inset",
    rows: [5, 27],
    blades: [
      { id: "blade-1", d: "M0 16.443C3.621 12.4 12.915 5 18.443 5C20.477 5 21.608 6.094 21.608 8.137C21.608 10.926 19.976 13.677 18.236 15.752C17.978 12.578 16.747 11.188 13.447 11.188C8.944 11.188 3.747 14.131 0 16.443Z" },
      { id: "blade-2", d: "M22.744 8.388C24.738 10.161 28.873 14.425 28.873 17.185C28.873 20.252 23.501 20.833 21.256 20.833C19.547 20.833 16.648 20.549 15.107 19.839C18.588 17.291 23.166 13.179 22.744 8.388Z" },
      { id: "blade-3", d: "M32 20.967C27.91 23.542 19.165 26.821 14.368 26.821C11.38 26.821 9.116 25.499 9.116 22.253C9.116 20.686 9.62 19.562 10.259 18.194C10.168 22.269 15.504 22.63 18.414 22.63C22.885 22.63 27.648 21.978 32 20.967Z" },
      { id: "blade-4", d: "M8.183 24.694C5.632 24.114 1.465 21.29 1.465 18.523C1.465 14.936 10.338 12.974 13.162 13.259C10.745 15.537 7.65 19.016 7.65 22.528C7.65 23.373 7.873 23.931 8.183 24.694Z" },
    ],
  },
};

const num = (n: number): string => String(Math.round(n * 1000) / 1000);

/** SVG path data for one master blade. */
export function bladePath(blade: ContinuumBlade): string {
  let d = `M${num(blade.nodes[0].p[0])} ${num(blade.nodes[0].p[1])}`;
  for (const s of blade.segments) d += `C${num(s.c1[0])} ${num(s.c1[1])} ${num(s.c2[0])} ${num(s.c2[1])} ${num(s.to[0])} ${num(s.to[1])}`;
  return `${d}Z`;
}

/** Master blades as path data, in blade order. */
export const CONTINUUM_MASTER_PATHS: readonly { readonly id: ContinuumBladeId; readonly d: string }[] = CONTINUUM_MASTER.map((b) => ({ id: b.id, d: bladePath(b) }));

/** The master's width : height. */
export const CONTINUUM_ASPECT = CONTINUUM_BOUNDS.width / CONTINUUM_BOUNDS.height;

/**
 * The optical master that suits a rendered width in device pixels, or null
 * above 40 where the master itself holds its channels.
 */
export function opticalSizeFor(width: number): ContinuumOpticalSize | null {
  if (width <= 17) return 16;
  if (width <= 21) return 20;
  if (width <= 27) return 24;
  if (width <= 40) return 32;
  return null;
}

/**
 * What to draw for a mark `size` px tall at one device pixel per px: in a
 * size x size square, the optical master when one suits its width, otherwise
 * the master in its square box. `tight` crops to the ink instead (lockups,
 * where the box is not square): the optical master's whole pixel rows, or the
 * master's own bounds; the optical choice then follows the wider width.
 */
export function continuumDrawing(size: number, opts: { tight?: boolean } = {}): ContinuumDrawing {
  const width = opts.tight ? size * CONTINUUM_ASPECT : size;
  const optical = opticalSizeFor(width);
  if (optical) {
    const o = CONTINUUM_OPTICAL[optical];
    const viewBox = opts.tight ? `0 ${o.rows[0]} ${optical} ${o.rows[1] - o.rows[0]}` : `0 0 ${optical} ${optical}`;
    return { viewBox, paths: o.blades };
  }
  if (opts.tight) {
    const b = CONTINUUM_BOUNDS;
    return { viewBox: `${b.x} ${b.y} ${b.width} ${b.height}`, paths: CONTINUUM_MASTER_PATHS };
  }
  return { viewBox: CONTINUUM_SQUARE_VIEWBOX, paths: CONTINUUM_MASTER_PATHS };
}

/**
 * The drawings for 1x and for 1.5 dppx and up (renderers switch with
 * `@media (min-resolution: 1.5dppx)`): on a 2x screen a 16 px mark covers 32
 * device pixels, where the 32 master keeps both the shape and the channels and
 * the 16 master, tuned for 16 device pixels, would look thin and pinched.
 */
export function continuumDrawingSet(size: number, opts: { tight?: boolean } = {}): ContinuumDrawingSet {
  const base = continuumDrawing(size, opts);
  const hi = continuumDrawing(size * 2, opts);
  return { base, hiDpi: hi.paths === base.paths ? null : hi };
}
