/**
 * Continuum: the Alevr master mark as construction data.
 *
 * Pure data and pure functions: no JSX, no React, no imports. Plain Node can
 * import this file with type stripping only (the export and native projection
 * scripts read it), so: no enums, no namespaces, no parameter properties.
 *
 * Generated by the brand lane's construction tooling from the owner-selected
 * raster (docs/rework/brand/assets/alevr-continuum-symbol.png). The method,
 * the evidence and the numbers are in docs/rework/brand/CONTINUUM_GEOMETRY.md.
 * Edit the construction there and regenerate; do not hand-edit coordinates.
 *
 * THE SPACE. One unit is 4.5 px of the 1254 px source raster. The origin is
 * the centre of the aperture: the largest circle that fits between the blades,
 * radius 24 units. The broad path width is 48 units (one aperture diameter),
 * which is also the clear space; the wordmark sits 1.5 path widths away.
 *
 * THE BLADES. Four separate closed paths, numbered clockwise from the upper
 * sweep, the order the thinking handoff walks. Each runs clockwise from its
 * outer trailing tip. On-curve nodes sit only at the two pointed tips and at
 * the outline's horizontal and vertical extrema, so every extremum node has an
 * axis-aligned handle and the bounding box is read straight off the nodes.
 *
 * THE RULES the solver held while fitting the silhouette:
 *   1. Nodes on the half-unit lattice; handles to 0.01.
 *   2. G2 at every smooth node: the curvature arriving equals the curvature
 *      leaving (within about 3%), so no highlight kinks where two spans meet.
 *   3. No handle reaches past the point where its span's end tangents meet,
 *      and no span has an inflection.
 *   4. Tips pinned to the raster's measured tip points: silhouette overlap is
 *      blind to hair-thin tips, so they are never traded away for area.
 *
 * OPTICAL MASTERS (16, 20, 24, 32 px). Below 32 px the master's channels fall
 * under a pixel and the blades fuse. Each optical master moves every outline
 * point inward by softplus((w - d) / 2), where d is its distance to the nearest
 * other blade, so each channel opens to at least w px and nothing away from a
 * channel moves; tips are cut where a retreating edge meets its partner, then
 * the outline is refit on its own extrema. Vertical placement puts the outer
 * extrema on whole pixels and lifts the box slightly because the visual mass
 * sits below the box centre.
 */

export type ContinuumPoint = readonly [number, number];
export type ContinuumNodeKind = "tip" | "x-extremum" | "y-extremum";
export type ContinuumBladeId = "blade-1" | "blade-2" | "blade-3" | "blade-4";
export type ContinuumNode = { readonly kind: ContinuumNodeKind; readonly p: ContinuumPoint };
export type ContinuumSegment = { readonly c1: ContinuumPoint; readonly c2: ContinuumPoint; readonly to: ContinuumPoint };
export type ContinuumBlade = {
  readonly id: ContinuumBladeId;
  readonly name: string;
  /** nodes[i] is where segments[i] starts; the outline closes back to nodes[0]. */
  readonly nodes: readonly ContinuumNode[];
  readonly segments: readonly ContinuumSegment[];
};
export type ContinuumOpticalSize = 16 | 20 | 24 | 32;
export type ContinuumDrawing = {
  readonly viewBox: string;
  readonly paths: readonly { readonly id: ContinuumBladeId; readonly d: string }[];
};

/** Clockwise from the upper sweep: the order the thinking handoff passes along. */
export const CONTINUUM_BLADE_ORDER: readonly ContinuumBladeId[] = ["blade-1", "blade-2", "blade-3", "blade-4"];

/** The mark's tight bounds in master units (read from the extremum nodes). */
export const CONTINUUM_BOUNDS = { x: -112, y: -82.5, width: 240.5, height: 164 } as const;

/** The aperture: the largest empty circle between the blades. Its centre is the origin. */
export const CONTINUUM_APERTURE = { cx: 0, cy: 0, r: 24 } as const;

/** Broad path width (one aperture diameter). Clear space is one path width on every side. */
export const CONTINUUM_PATH_WIDTH = 48;

/**
 * A square box around the mark for icon-style use at sizes without an optical
 * master: centred horizontally, lifted 2 units so the visual mass reads centred.
 */
export const CONTINUUM_SQUARE_VIEWBOX = "-112 -118.75 240.5 240.5";

export const CONTINUUM_MASTER: readonly ContinuumBlade[] = [
  {
    id: "blade-1",
    name: "upper sweep",
    nodes: [
      { kind: "tip", p: [-112, 3.5] },
      { kind: "y-extremum", p: [26.5, -82.5] },
      { kind: "x-extremum", p: [50.5, -58.5] },
      { kind: "tip", p: [25, -1.5] },
      { kind: "y-extremum", p: [-10.5, -36] },
    ],
    segments: [
      { c1: [-84.35, -27.94], c2: [-13.76, -82.5], to: [26.5, -82.5] },
      { c1: [43.31, -82.5], c2: [50.5, -72.85], to: [50.5, -58.5] },
      { c1: [50.5, -38.6], c2: [36.9, -14.5], to: [25, -1.5] },
      { c1: [23.85, -22.04], c2: [16.3, -36], to: [-10.5, -36] },
      { c1: [-43.82, -36], c2: [-82.1, -15], to: [-112, 3.5] },
    ],
  },
  {
    id: "blade-2",
    name: "right fin",
    nodes: [
      { kind: "tip", p: [59, -57] },
      { kind: "x-extremum", p: [105, 9] },
      { kind: "y-extremum", p: [48, 36.5] },
      { kind: "tip", p: [1.5, 29] },
    ],
    segments: [
      { c1: [74.66, -43.62], c2: [105, -10.78], to: [105, 9] },
      { c1: [105, 31.9], c2: [65.4, 36.5], to: [48, 36.5] },
      { c1: [35.17, 36.5], c2: [10.75, 34], to: [1.5, 29] },
      { c1: [28.98, 9.77], c2: [61, -21.25], to: [59, -57] },
    ],
  },
  {
    id: "blade-3",
    name: "lower sweep",
    nodes: [
      { kind: "tip", p: [128.5, 37.5] },
      { kind: "y-extremum", p: [-4, 81.5] },
      { kind: "x-extremum", p: [-43.5, 47.5] },
      { kind: "tip", p: [-35, 16.5] },
      { kind: "y-extremum", p: [26, 50] },
    ],
    segments: [
      { c1: [98.2, 57.02], c2: [31.04, 81.5], to: [-4, 81.5] },
      { c1: [-26.37, 81.5], c2: [-43.5, 71.5], to: [-43.5, 47.5] },
      { c1: [-43.5, 36.65], c2: [-40, 26.3], to: [-35, 16.5] },
      { c1: [-33.67, 47.5], c2: [2.03, 50], to: [26, 50] },
      { c1: [59.9, 50], c2: [96.67, 45], to: [128.5, 37.5] },
    ],
  },
  {
    id: "blade-4",
    name: "left fin",
    nodes: [
      { kind: "tip", p: [-50.5, 65.5] },
      { kind: "x-extremum", p: [-101, 19.5] },
      { kind: "tip", p: [-13, -20.5] },
      { kind: "x-extremum", p: [-54.5, 49] },
    ],
    segments: [
      { c1: [-69.78, 62.02], c2: [-101, 38.75], to: [-101, 19.5] },
      { c1: [-101, -8.97], c2: [-31.81, -22.6], to: [-13, -20.5] },
      { c1: [-29.15, -5.47], c2: [-54.5, 22.5], to: [-54.5, 49] },
      { c1: [-54.5, 55.45], c2: [-53, 59.3], to: [-50.5, 65.5] },
    ],
  },
];

/** Per-size optical masters in pixel space (viewBox 0 0 size size). `channel` is the opened minimum in px. */
export const CONTINUUM_OPTICAL: Readonly<Record<ContinuumOpticalSize, { readonly channel: number; readonly blades: readonly { readonly id: ContinuumBladeId; readonly d: string }[] }>> = {
  16: {
    channel: 1.3,
    blades: [
      { id: "blade-1", d: "M1.47 6.483C3.083 4.769 6.846 2.045 9.221 2.045C9.771 2.045 10.578 2.259 10.578 2.931C10.578 3.139 10.483 3.389 10.457 3.599C10.43 3.826 10.445 4.014 10.403 4.277C10.258 5.199 9.757 6.05 9.188 6.775C9.008 6.495 8.826 6.096 8.653 5.87C8.199 5.278 7.185 4.999 6.47 4.999C4.91 4.999 2.834 5.732 1.47 6.483Z" },
      { id: "blade-2", d: "M11.719 4.243C12.68 4.729 14.436 7.014 14.436 8.139C14.436 9.657 11.347 9.742 10.253 9.742C9.418 9.742 8.412 9.693 7.617 9.443C7.936 9.218 8.202 8.957 8.55 8.749C8.92 8.527 9.296 8.438 9.646 8.168C10.647 7.395 11.561 5.54 11.719 4.243Z" },
      { id: "blade-3", d: "M16 10.028C13.951 11.316 9.585 12.956 7.182 12.956C6.618 12.956 5.62 12.824 5.283 12.318C5.15 12.119 5.116 11.876 5.048 11.652C4.927 11.252 4.843 11.16 4.843 10.705C4.843 10.278 4.989 9.838 5.15 9.449C5.406 9.711 5.684 10.014 5.988 10.221C7.075 10.96 8.909 11.046 10.197 11.046C12.561 11.046 13.777 10.548 16 10.028Z" },
      { id: "blade-4", d: "M3.676 11.647C2.608 11.572 0.765 9.984 0.765 8.983C0.765 7.601 4.991 6.395 6.328 6.311C5.504 7.491 5.158 7.342 4.557 7.932C3.983 8.495 3.54 9.92 3.54 10.744C3.54 11.098 3.581 11.311 3.676 11.647Z" },
    ],
  },
  20: {
    channel: 1.15,
    blades: [
      { id: "blade-1", d: "M0.238 9.938C2.582 7.451 8.041 3 11.523 3C12.359 3 13.386 3.42 13.386 4.348C13.386 4.542 13.322 4.77 13.304 4.971C13.132 6.855 12.715 7.817 11.467 9.304C11.286 8.918 11.257 8.645 11.101 8.281C10.603 7.115 9.495 6.852 8.332 6.852C6.352 6.852 3.484 7.854 1.779 8.853C1.171 9.209 0.787 9.517 0.238 9.938Z" },
      { id: "blade-2", d: "M14.431 5.437C15.58 6.096 18.046 9.138 18.046 10.616C18.046 12.615 14.465 12.832 13.04 12.832C11.973 12.832 10.42 12.711 9.448 12.276C9.918 11.915 10.56 11.398 11.017 11.07C11.342 10.836 11.692 10.667 11.993 10.404C13.219 9.336 14.355 7.113 14.431 5.437Z" },
      { id: "blade-3", d: "M20 12.979C17.439 14.591 11.978 16.638 8.973 16.638C8.126 16.638 6.874 16.409 6.354 15.675C6.208 15.469 6.137 15.202 6.052 14.963C5.902 14.543 5.823 14.303 5.823 13.847C5.823 13.137 6.073 12.463 6.374 11.831C6.618 12.225 6.753 12.562 7.103 12.907C8.266 14.051 10.672 14.049 12.216 14.049C14.809 14.049 17.476 13.566 20 12.979Z" },
      { id: "blade-4", d: "M4.9 15.181C3.521 15.06 0.919 13.049 0.919 11.474C0.919 9.961 4.847 8.676 6.081 8.399C6.859 8.225 7.412 8.162 8.206 8.161C7.638 8.737 7.189 9.241 6.649 9.809C6.36 10.114 5.996 10.348 5.756 10.638C5.151 11.368 4.656 12.91 4.656 13.881C4.656 14.395 4.735 14.702 4.9 15.181Z" },
    ],
  },
  24: {
    channel: 1,
    blades: [
      { id: "blade-1", d: "M-0.002 12.216C2.79 9.176 9.628 3.634 13.828 3.634C15.087 3.634 16.159 4.285 16.159 5.632C16.159 7.997 15.216 9.75 13.724 11.517C13.603 11.067 13.558 10.636 13.409 10.201C12.885 8.673 11.6 8.274 10.113 8.274C7.748 8.274 4.493 9.54 2.439 10.686C1.623 11.141 0.795 11.711 -0.002 12.216Z" },
      { id: "blade-2", d: "M17.141 6.311C18.608 7.361 21.654 10.878 21.654 12.797C21.654 15.081 17.576 15.504 15.912 15.504C14.63 15.504 12.497 15.295 11.339 14.768C12.233 14.061 13.546 13.103 14.353 12.32C15.834 10.882 17.186 8.436 17.141 6.311Z" },
      { id: "blade-3", d: "M24 15.609C20.924 17.545 14.373 20 10.764 20C8.573 20 6.858 19.019 6.858 16.63C6.858 15.607 7.189 14.734 7.648 13.84C7.797 14.342 7.93 14.782 8.249 15.209C9.406 16.754 12.083 16.857 13.847 16.857C17.213 16.857 20.723 16.371 24 15.609Z" },
      { id: "blade-4", d: "M6.141 18.43C5.562 18.209 5.359 18.221 4.699 17.892C3.319 17.205 1.098 15.489 1.098 13.804C1.098 11.232 7.669 9.628 9.873 9.827C7.943 11.646 5.716 13.975 5.716 16.776C5.716 17.356 5.872 17.925 6.141 18.43Z" },
    ],
  },
  32: {
    channel: 1,
    blades: [
      { id: "blade-1", d: "M0 16.443C3.621 12.4 12.915 5 18.443 5C20.477 5 21.608 6.094 21.608 8.137C21.608 10.926 19.976 13.677 18.236 15.752C17.978 12.578 16.747 11.188 13.447 11.188C8.944 11.188 3.747 14.131 0 16.443Z" },
      { id: "blade-2", d: "M22.744 8.388C24.738 10.161 28.873 14.425 28.873 17.185C28.873 20.252 23.501 20.833 21.256 20.833C19.547 20.833 16.648 20.549 15.107 19.839C18.588 17.291 23.166 13.179 22.744 8.388Z" },
      { id: "blade-3", d: "M32 20.967C27.91 23.542 19.165 26.821 14.368 26.821C11.38 26.821 9.116 25.499 9.116 22.253C9.116 20.686 9.62 19.562 10.259 18.194C10.168 22.269 15.504 22.63 18.414 22.63C22.885 22.63 27.648 21.978 32 20.967Z" },
      { id: "blade-4", d: "M8.183 24.694C5.632 24.114 1.465 21.29 1.465 18.523C1.465 14.936 10.338 12.974 13.162 13.259C10.745 15.537 7.65 19.016 7.65 22.528C7.65 23.373 7.873 23.931 8.183 24.694Z" },
    ],
  },
};

const num = (n: number): string => String(Math.round(n * 1000) / 1000);

/** SVG path data for one master blade. */
export function bladePath(blade: ContinuumBlade): string {
  let d = `M${num(blade.nodes[0].p[0])} ${num(blade.nodes[0].p[1])}`;
  for (const s of blade.segments) d += `C${num(s.c1[0])} ${num(s.c1[1])} ${num(s.c2[0])} ${num(s.c2[1])} ${num(s.to[0])} ${num(s.to[1])}`;
  return `${d}Z`;
}

/** Master blades as path data, in blade order. */
export const CONTINUUM_MASTER_PATHS: readonly { readonly id: ContinuumBladeId; readonly d: string }[] = CONTINUUM_MASTER.map((b) => ({ id: b.id, d: bladePath(b) }));

/**
 * The optical master that suits a rendered size (CSS px), or null above 40 px
 * where the master itself holds its channels.
 */
export function opticalSizeFor(size: number): ContinuumOpticalSize | null {
  if (size <= 17) return 16;
  if (size <= 21) return 20;
  if (size <= 27) return 24;
  if (size <= 40) return 32;
  return null;
}

/**
 * What to draw in a size x size square: the optical master when one suits,
 * otherwise the master in its square box. `tight` returns the master in its
 * own bounds instead (for lockups, where the box is not square).
 */
export function continuumDrawing(size: number, opts: { tight?: boolean } = {}): ContinuumDrawing {
  if (opts.tight) {
    const b = CONTINUUM_BOUNDS;
    return { viewBox: `${b.x} ${b.y} ${b.width} ${b.height}`, paths: CONTINUUM_MASTER_PATHS };
  }
  const optical = opticalSizeFor(size);
  if (optical) return { viewBox: `0 0 ${optical} ${optical}`, paths: CONTINUUM_OPTICAL[optical].blades };
  return { viewBox: CONTINUUM_SQUARE_VIEWBOX, paths: CONTINUUM_MASTER_PATHS };
}
