import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

import designSystem from "./eslint-rules/design-system.mjs";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "public/**",
      "prisma/migrations/**",
      "relay/node_modules/**",
      "relay/dist/**",
      "deploy/**",
      // Transient agent worktrees and the vendored Cloud Code runner (its own
      // build/lint story lives in CI) are not part of the app's lint surface.
      ".claude/**",
      ".worktrees/**",
      "runner/**",
      // Native build products are generated artifacts, not application source.
      // They can contain minified WebView bundles and Swift/Xcode intermediates
      // that produce false positives when ESLint walks the repository root.
      "native/**/.build/**",
      // The bundled Mac design editor is build output — minified, generated by
      // `npm run design:editor` from sources that ARE linted. Linting the bundle
      // reports thousands of warnings about the minifier's own comma
      // expressions and tells nobody anything.
      "native/macOS/JunoDesktop/Resources/DesignEditor/**",
      // Local scratch: `.probe/` holds one-off diagnostic scripts and
      // `head-wt/` is a detached checkout used to diff against HEAD. Neither
      // ships, and neither is tracked, so linting them only ever reports on
      // throwaway code.
      ".probe/**",
      "head-wt/**",
      "tmp-verify/**",
      "next-env.d.ts",
      "src/lib/i18n-catalog.generated.ts",
      // Bundled design-editor asset generated for the native WebView; lint the
      // TypeScript source that produces it, not its minified output.
      "native/macOS/JunoDesktop/Resources/DesignEditor/editor.js",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // no-img-element is off globally; keep the older inline disables at the
    // deliberate <img> sites without flagging them as unused.
    linterOptions: {
      reportUnusedDisableDirectives: "off",
    },
    rules: {
      // `_`-prefixed bindings and omittable catch params are the repo's
      // deliberate "intentionally unused" convention.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          caughtErrors: "none",
        },
      ],
      // User avatars/attachments come from arbitrary hosts at runtime, where
      // next/image optimization doesn't apply.
      "@next/next/no-img-element": "off",
    },
  },
  {
    // The design system, made enforceable. An error rather than a warning: the
    // whole point is that it fails CI, because the previous state of this rule
    // was a comment in tailwind.config.ts asking nicely.
    files: ["src/**/*.{ts,tsx}"],
    plugins: { "design-system": designSystem },
    rules: {
      "design-system/no-arbitrary-radius": [
        "error",
        {
          // Em-relative so it tracks the surrounding font size — the inline
          // source chip in a run of prose. The scale is in px and cannot
          // express this one.
          allow: ["0.25em"],
        },
      ],
      "design-system/no-ad-hoc-stacking": "error",
    },
  },
];

export default config;
