import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

import designSystem from "./eslint-rules/design-system.mjs";
import noArbitraryText from "./eslint-rules/no-arbitrary-text.js";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "public/**",
      "prisma/migrations/**",
      "relay/node_modules/**",
      "relay/dist/**",
      "deploy/**",
      // Transient agent worktrees and the vendored Cloud Code runner (its own
      // build/lint story lives in CI) are not part of the app's lint surface.
      //
      // `**/.claude/**` as well as `.claude/**`: flat-config ignores are
      // relative to this file, so the bare pattern only ever matched the one at
      // the repository root. An agent worktree nested under a subproject —
      // native/desktop-electron/.claude/worktrees/… — was still walked, and
      // being a full checkout it duplicates every file in the repo, so `eslint .`
      // reported thousands of errors from a copy of code it had already linted.
      ".claude/**",
      "**/.claude/**",
      ".worktrees/**",
      "**/.worktrees/**",
      "runner/**",
      // The Electron client is a standalone package — its own package.json,
      // tsconfig, eslint config and node_modules, same as `relay` and `runner`.
      // It was untracked until it was committed, at which point `eslint .` began
      // walking it with the WEB app's rules and failing on `require()` in its
      // CommonJS build configs. It lints itself in the `desktop` workflow, which
      // is where its rules live. (tsconfig.json excludes it for the same reason.)
      "native/desktop-electron/**",
      // Native build products are generated artifacts, not application source.
      // They can contain minified WebView bundles and Swift/Xcode intermediates
      // that produce false positives when ESLint walks the repository root.
      "native/**/.build/**",
      // The bundled Mac design editor is build output — minified, generated by
      // `npm run design:editor` from sources that ARE linted. Linting the bundle
      // reports thousands of warnings about the minifier's own comma
      // expressions and tells nobody anything.
      "native/macOS/JunoDesktop/Resources/DesignEditor/**",
      // Local scratch: `.probe/` holds one-off diagnostic scripts and
      // `head-wt/` is a detached checkout used to diff against HEAD. Neither
      // ships, and neither is tracked, so linting them only ever reports on
      // throwaway code.
      ".probe/**",
      "head-wt/**",
      "tmp-verify/**",
      "next-env.d.ts",
      "src/lib/i18n-catalog.generated.ts",
      // Bundled design-editor asset generated for the native WebView; lint the
      // TypeScript source that produces it, not its minified output.
      "native/macOS/JunoDesktop/Resources/DesignEditor/editor.js",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // no-img-element is off globally; keep the older inline disables at the
    // deliberate <img> sites without flagging them as unused.
    linterOptions: {
      reportUnusedDisableDirectives: "off",
    },
    rules: {
      // `_`-prefixed bindings and omittable catch params are the repo's
      // deliberate "intentionally unused" convention.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          caughtErrors: "none",
        },
      ],
      // User avatars/attachments come from arbitrary hosts at runtime, where
      // next/image optimization doesn't apply.
      "@next/next/no-img-element": "off",
    },
  },
  {
    // The design system, made enforceable. An error rather than a warning: the
    // whole point is that it fails CI, because the previous state of this rule
    // was a comment in tailwind.config.ts asking nicely.
    files: ["src/**/*.{ts,tsx}"],
    plugins: {
      // The text rule ships as its own CJS module (see its header for why), so
      // it is folded into the one plugin namespace here rather than growing a
      // second `plugins` key per rule file.
      "design-system": {
        rules: { ...designSystem.rules, "no-arbitrary-text": noArbitraryText },
      },
    },
    rules: {
      "design-system/no-arbitrary-radius": [
        "error",
        {
          // Em-relative so it tracks the surrounding font size — the inline
          // source chip in a run of prose. The scale is in px and cannot
          // express this one.
          allow: ["0.25em"],
        },
      ],
      "design-system/no-ad-hoc-stacking": "error",
      // Warn, not error, and the difference is a ratchet, not a softer
      // opinion: 457 text-[Npx] sites predate the `ui`/`micro` rungs and are
      // being migrated in batches. An error today would only teach people to
      // sprinkle disables; promote it alongside the other two once the count
      // reaches zero.
      "design-system/no-arbitrary-text": "warn",
    },
  },
  {
    /*
     * Node tooling under `scripts/` written as CommonJS.
     *
     * The repo's own convention already says which is which: everything meant
     * to be maintained is `.ts` or `.mjs` and is ESM, and the handful of plain
     * `.js` files here are throwaway operational one-offs run with `node` —
     * `require()` is the correct call in that file type, and the rule is aimed
     * at application source, not at a script that reads a file and exits.
     *
     * Narrow on purpose: `scripts/**` only, and only `.js`. A `.ts` or `.mjs`
     * script keeps the rule.
     */
    files: ["scripts/**/*.js"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
];

export default config;
