#!/bin/bash
# Stamp the current commit into the native builds.
#
# Diagnostics has to be able to answer "is the build on this device the one that
# is deployed?" from the device itself. That needs the commit baked into the
# bundle at build time, so this writes native/Config/Generated-Build.xcconfig,
# which Base.xcconfig picks up through an optional include.
#
# Run from the repository root before archiving:
#
#     ./native/Scripts/write-build-metadata.sh
#
# The generated file is deliberately not committed: it is build output, and a
# stale committed copy would report the wrong commit, which is worse than
# reporting "unknown".
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$ROOT/native/Config/Generated-Build.xcconfig"

SHA="$(git -C "$ROOT" rev-parse --short=10 HEAD 2>/dev/null || echo unknown)"
if ! git -C "$ROOT" diff --quiet HEAD 2>/dev/null; then
    SHA="$SHA-dirty"
fi

# The contract version is read from the single TypeScript source of truth rather
# than restated here, so the three copies (server, generated Swift, bundle) can
# never drift silently apart.
CONTRACT="$(sed -n 's/^export const CONTRACT_VERSION = "\(.*\)";$/\1/p' "$ROOT/src/lib/api-v1.ts")"
if [ -z "$CONTRACT" ]; then
    echo "write-build-metadata: could not read CONTRACT_VERSION from src/lib/api-v1.ts" >&2
    exit 1
fi

cat > "$OUT" <<EOF
// Generated by native/Scripts/write-build-metadata.sh — do not edit or commit.
JUNO_GIT_SHA = $SHA
JUNO_CONTRACT_VERSION = $CONTRACT
EOF

echo "native/Config/Generated-Build.xcconfig: sha=$SHA contract=$CONTRACT"
