// Generated by scripts/generate-design-tokens.ts — DO NOT EDIT.
//
// Source: src/app/globals.css (colour, motion) + tailwind.config.ts (radius).
// Regenerate with `npm run design:tokens`; `npm run design:tokens:check`
// fails CI when this file no longer matches its sources.
//
// tokens-digest: fcc87a86da080e62
//

/** `--dur-*` in milliseconds. */
export const DURATION = {
  press: 70,
  fast: 120,
  exit: 160,
  base: 220,
  slow: 360,
  emphasis: 560,
} as const;

/** `--ease-*` as cubic-bezier control points. */
export const EASING = {
  breathe: [0.45, 0, 0.55, 1] as const,
  in: [0.4, 0, 1, 1] as const,
  inOut: [0.65, 0, 0.35, 1] as const,
  outExpo: [0.16, 1, 0.3, 1] as const,
  outSoft: [0.33, 1, 0.68, 1] as const,
  outStrong: [0.32, 0.72, 0, 1] as const,
} as const;

/** The radius ladder, in pixels. */
export const RADIUS = {
  "micro": 2,
  "sm": 4,
  "xs": 6,
  "md": 8,
  "control": 10,
  "composerControl": 11,
  "field": 12,
  "composerAction": 13,
  "menu": 14,
  "card": 16,
  "popover": 18,
  "surface": 20,
  "composer": 22,
  "panel": 28,
} as const;

export type DurationToken = keyof typeof DURATION;
export type EasingToken = keyof typeof EASING;
export type RadiusToken = keyof typeof RADIUS;
