import Foundation
import Observation
import JunoCodeCore

/// The message that has not got a session yet.
///
/// There is no new-session sheet any more. A sheet asked seven questions before
/// the reader could type a word, and it asked them in a form that wrote to
/// different state than the composer did — so the same session could be created
/// with one mode and then appear to be in another. The draft is the composer:
/// pick a repository, write the message, send. The session is created by the act
/// of sending it, with exactly the contract the composer states.
@MainActor
@Observable
public final class CodeDraftModel {
    public var text = ""
    public var workspaceID: WorkspaceID?
    public var behavior: AgentBehavior = .code
    public var permissionMode: PermissionMode = .askBeforeChanges
    public var modelID = ""
    public var reasoningEffort: ReasoningEffort = .medium
    public private(set) var isCreating = false
    public private(set) var lastError: String?

    public init() {}

    /// The permission level actually in force. Ask and Plan are read-only by
    /// construction, so the stored choice is what the reader gets back on their
    /// return to Code rather than something that silently applies now.
    public var effectivePermissionMode: PermissionMode {
        behavior == .code ? permissionMode : .readOnly
    }

    public var canSend: Bool {
        !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            && workspaceID != nil
            && !modelID.isEmpty
            && !isCreating
    }

    /// Fills in the defaults that exist. Nothing is invented: with no workspace
    /// and no model, `canSend` stays false and the composer says why.
    public func prepare(_ model: WorkbenchModel) {
        if workspaceID == nil || !model.workspaces.contains(where: { $0.id == workspaceID }) {
            workspaceID = model.workspaces.first?.id
        }
        if modelID.isEmpty || !model.availableModels.contains(where: { $0.modelID == modelID }) {
            modelID = model.availableModels.first?.modelID ?? ""
        }
    }

    /// Creates the session and sends the drafted message as its first turn, so
    /// the transcript grows exactly where the draft was.
    public func send(using model: WorkbenchModel) async {
        let prompt = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !prompt.isEmpty, let workspaceID, !isCreating else { return }
        lastError = nil
        isCreating = true
        defer { isCreating = false }

        let configuration = AgentConfiguration(
            modelID: modelID,
            reasoningEffort: reasoningEffort,
            behavior: behavior,
            // Role is fixed: it was a fourth axis indistinguishable from mode,
            // and nothing in the product now offers it.
            role: .engineer,
            permissionMode: permissionMode,
            location: .local,
            // A standing screen-and-input grant is never implied by starting a
            // session; it is asked for from the window's own control.
            computerUseEnabled: false
        )
        guard let session = await model.createSession(
            workspaceID: workspaceID,
            configuration: configuration
        ) else {
            lastError = model.lastError ?? "Could not create the session."
            return
        }
        await model.renameSession(id: session.id, title: Self.title(from: prompt))
        guard let controller = await model.controller(for: session.id) else {
            lastError = model.lastError
                ?? "The session was created, but its workspace could not be opened."
            return
        }
        controller.composerText = prompt
        await controller.send()
        text = ""
    }

    /// The session's name, taken from the reader's own first line rather than
    /// left as "New session" or generated by a second model call.
    static func title(from prompt: String) -> String {
        let firstLine = prompt
            .split(separator: "\n")
            .first
            .map(String.init)?
            .trimmingCharacters(in: .whitespaces) ?? prompt
        return firstLine.count > 60 ? String(firstLine.prefix(60)) + "…" : firstLine
    }
}
