import type { OfficialRateEntry } from "../../src/lib/model-rates.generated";
import type { Addition, LifecycleEdit, Plan } from "./compare";

/**
 * Turning a plan into source edits. Three files, three kinds of edit:
 *
 *  - src/lib/model-rates.generated.ts is rewritten whole from the verified
 *    rates (sorted, one entry per line, so a review diff reads per model).
 *  - src/lib/models.ts gets surgical edits to the one-line `def({...})` rows:
 *    a field set or replaced, a row inserted, a row moved into
 *    RETIRED_MODELS. Every edit must find its row exactly once or the whole
 *    apply fails — a sync that half-edits the catalogue is worse than none.
 *  - the Mac picker fixture is regenerated by the caller from the result.
 */

export function renderRatesFile(rates: Record<string, OfficialRateEntry>, existingHeader: string): string {
  const ids = Object.keys(rates).sort();
  const body = ids.map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(rates[id])},`).join("\n");
  return `${existingHeader.trimEnd()}\n\nexport const OFFICIAL_RATES: Readonly<Record<string, OfficialRateEntry>> = {\n${body}\n};\n`;
}

/** Everything in the generated file above the table (header + interface). */
export function ratesFileHeader(source: string): string {
  const at = source.indexOf("export const OFFICIAL_RATES");
  if (at < 0) throw new Error("model-rates.generated.ts: OFFICIAL_RATES not found");
  return source.slice(0, at);
}

function rowPattern(provider: string, id: string): RegExp {
  const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`^.*def\\(\\{ provider: "${esc(provider)}", id: "${esc(id)}",.*$`, "gm");
}

function findRow(src: string, provider: string, id: string): RegExpExecArray {
  const matches = [...src.matchAll(rowPattern(provider, id))];
  if (matches.length !== 1) throw new Error(`models.ts: expected one def row for ${provider}:${id}, found ${matches.length}`);
  return matches[0] as RegExpExecArray;
}

function literal(key: string, value: unknown): string {
  if (typeof value === "number") return key === "contextWindow" ? value.toLocaleString("en-US").replace(/,/g, "_") : String(value);
  return JSON.stringify(value);
}

/** Set (or replace) `key: value` inside one def row. */
export function setField(row: string, key: string, value: unknown): string {
  const re = new RegExp(`\\b${key}: ("(?:[^"\\\\]|\\\\.)*"|[\\d_.]+|true|false)`);
  const lit = literal(key, value);
  if (re.test(row)) return row.replace(re, `${key}: ${lit}`);
  // New field: before `description`, so the lifecycle fields sit together.
  if (/, description: /.test(row)) return row.replace(/, description: /, `, ${key}: ${lit}, description: `);
  return row.replace(/ \}\),?\s*(\/\/.*)?$/, (tail) => tail.replace(/^ \}\)/, `, ${key}: ${lit} })`));
}

export function applyEdit(src: string, edit: LifecycleEdit): string {
  const [provider, id] = [edit.provider, edit.id.slice(edit.provider.length + 1)];
  const m = findRow(src, provider, id);
  let row = m[0];
  // Order matters only for readability: status, then the retirement trio.
  for (const key of ["status", "vision", "contextWindow", "deprecationNote", "retiresOn", "replacedBy"] as const) {
    if (edit.set[key] !== undefined) row = setField(row, key, edit.set[key]);
  }
  return src.slice(0, m.index) + row + src.slice(m.index + m[0].length);
}

export function renderAddition(a: Addition, today: string): string {
  const fields = [
    `provider: ${JSON.stringify(a.provider)}`,
    `id: ${JSON.stringify(a.id)}`,
    `name: ${JSON.stringify(a.name)}`,
    `family: ${JSON.stringify(a.family)}`,
    `status: "current"`,
    a.released ? `released: ${JSON.stringify(a.released)}` : null,
    `minPlan: ${JSON.stringify(a.minPlan)}`,
    `vision: ${a.vision}`,
    `reasoning: ${a.reasoning}`,
    `cost: ${a.cost}`,
    `contextWindow: ${literal("contextWindow", a.contextWindow)}`,
    `description: ${JSON.stringify(a.description)}`,
  ].filter(Boolean);
  const sources = a.sources.map((s) => s.url).filter((u, i, all) => all.indexOf(u) === i);
  return [
    `  // ${a.name}: added by models:sync on ${today} from ${sources.join(", ")}.`,
    `  // Price and limits are the page's; check the thinking ladder (model-metrics.ts reasoningCaps) and tool record by hand.`,
    `  def({ ${fields.join(", ")} }),`,
  ].join("\n");
}

export function applyAddition(src: string, a: Addition, today: string): string {
  const text = renderAddition(a, today);
  if (a.before) {
    const [provider, id] = [a.before.split(":")[0], a.before.slice(a.before.indexOf(":") + 1)];
    const m = findRow(src, provider, id);
    // Above the predecessor and above the comment block that belongs to it.
    let start = m.index;
    const lines = src.slice(0, start).split("\n");
    lines.pop(); // the partial line before the row (empty: rows start a line)
    let back = 0;
    for (let i = lines.length - 1; i >= 0 && /^\s*\/\//.test(lines[i]); i--) back += lines[i].length + 1;
    start -= back;
    return src.slice(0, start) + text + "\n" + src.slice(start);
  }
  throw new Error(`models.ts: no predecessor row to place ${a.provider}:${a.id} beside`);
}

/** Remove an expired row and add its redirect to RETIRED_MODELS. */
export function applyExpiry(src: string, e: Plan["expiries"][number]): string {
  const id = e.id.slice(e.provider.length + 1);
  const m = findRow(src, e.provider, id);
  // Drop the row, plus a comment block directly above it that only described it.
  let start = m.index;
  const end = m.index + m[0].length + 1;
  const before = src.slice(0, start).split("\n");
  before.pop();
  let back = 0;
  for (let i = before.length - 1; i >= 0 && /^\s*\/\//.test(before[i]); i--) {
    // Keep section headers ("// —— Qwen ——") and comments that also lead the next row.
    if (/——/.test(before[i])) break;
    back += before[i].length + 1;
  }
  const nextLine = src.slice(end).split("\n")[0] ?? "";
  if (back && !/^\s*def\(/.test(nextLine)) start -= back; // the block led only this row
  src = src.slice(0, start) + src.slice(end);
  // Out of UNAVAILABLE too, if it was there.
  // (UNAVAILABLE holds bare `"provider:id",` lines; nothing else in the file does.)
  src = src.replace(new RegExp(`^\\s*"${e.id.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}",\\n`, "m"), "");
  // Into RETIRED_MODELS, at the end of the map.
  const close = src.indexOf("\n};\n", src.indexOf("export const RETIRED_MODELS"));
  if (close < 0) throw new Error("models.ts: RETIRED_MODELS not found");
  const entry = `\n  ${JSON.stringify(e.id)}: ${JSON.stringify(e.replacedBy)}, // retired ${e.retiresOn} (models:sync)`;
  return src.slice(0, close) + entry + src.slice(close);
}

export function applyPlanToModels(src: string, plan: Plan, today: string): string {
  // Expiries first (they delete rows other edits must not touch), then edits, then inserts.
  for (const e of plan.expiries) src = applyExpiry(src, e);
  const expired = new Set(plan.expiries.map((e) => e.id));
  for (const e of plan.edits) if (!expired.has(e.id)) src = applyEdit(src, e);
  for (const a of plan.additions) src = applyAddition(src, a, today);
  return src;
}
