// Generated by scripts/generate-agent-protocol.mjs. Do not edit.
//
// Source of truth: contracts/agent/juno-agent-protocol-v1.json
// The same text is written to runner/agent-core/src/protocol.generated.ts and
// src/lib/agent-protocol/protocol.generated.ts (agent-core builds standalone),
// and the Swift half to the JunoAgentProtocol target. `npm run
// agent:protocol:check` fails when any of them drifts from the contract.
/* eslint-disable */

export const AGENT_PROTOCOL = {
  name: "juno-agent-protocol",
  major: 1,
  minor: 1,
  /** What a producer writes as `v`. */
  v: "1.1",
  /** SHA-256 of the contract this was generated from. */
  digest: "8220a2c3be3c54f9d7aa351f5dd22f48456949b3337f4e0a6ca6c1528f798e80",
} as const;

// ── Enums ───────────────────────────────────────────────────────────────────

/** Where a session runs. */
export const AGENT_SESSION_TARGET_VALUES = [
  "local", // On the machine showing it.
  "remote", // On one of the reader's own computers, driven from another device.
  "cloud", // On a cloud runner against a repository.
  "unknown", // A target this reader does not know.
] as const;
export type AgentSessionTarget = (typeof AGENT_SESSION_TARGET_VALUES)[number];

/** How much the agent may do before it has to ask. Swift maps its four internal modes onto these at the edge. */
export const AGENT_PERMISSION_MODE_VALUES = [
  "plan", // Read and search only; every change is refused.
  "ask", // Every edit and every command asks first.
  "auto_edit", // Edits inside the workspace proceed; commands still ask.
  "full", // Most actions proceed; the most dangerous still ask.
  "unknown", // A mode this reader does not know.
] as const;
export type AgentPermissionMode = (typeof AGENT_PERMISSION_MODE_VALUES)[number];

/** How hard the model was asked to think. Absent means no thinking parameter was sent. */
export const AGENT_REASONING_EFFORT_VALUES = [
  "minimal", // The least thinking the provider offers.
  "low", // Light thinking.
  "medium", // Moderate thinking.
  "high", // Deep thinking.
  "xhigh", // Deeper than high, where the provider offers it.
  "max", // The most the provider offers.
  "unknown", // An effort this reader does not know.
] as const;
export type AgentReasoningEffort = (typeof AGENT_REASONING_EFFORT_VALUES)[number];

/** What the agent is instructed to do this turn, on engines that keep it apart from the permission mode (the Mac's Ask, Survey, Plan and Code). */
export const AGENT_TURN_BEHAVIOR_VALUES = [
  "code", // Make the change: edits and commands, within the mode.
  "plan", // Work out what to do and propose it; change nothing.
  "ask", // Answer questions about the code; change nothing.
  "survey", // Map the repository before anyone commits to a change; change nothing.
  "unknown", // A behavior this reader does not know.
] as const;
export type AgentTurnBehavior = (typeof AGENT_TURN_BEHAVIOR_VALUES)[number];

/** What a session is doing, as one fact a list or a header can show. */
export const AGENT_SESSION_STATE_VALUES = [
  "idle", // Nothing is running; the session waits for a message.
  "running", // A turn is in progress.
  "awaiting_approval", // Blocked on an approval decision.
  "awaiting_input", // Blocked on an answer to a question.
  "completed", // Finished what it was given. Terminal for a one-shot run.
  "failed", // Stopped because something went wrong.
  "interrupted", // Ended before it finished, without anyone asking: a crash, a quit, a lost host.
  "cancelled", // Stopped because somebody asked it to.
  "paused", // A goal is paused; nothing runs until the reader resumes it.
  "waiting_background", // The run waits for background work (a shell, a sub-agent) to report before it goes on.
  "unknown", // A state this reader does not know.
] as const;
export type AgentSessionState = (typeof AGENT_SESSION_STATE_VALUES)[number];

/** What started a turn. */
export const AGENT_TURN_ORIGIN_VALUES = [
  "user", // A message the reader sent.
  "steer", // An instruction sent while the previous turn ran, taken at its next step.
  "queue", // A message queued behind a running turn, started when it ended.
  "hook", // A hook that asked the agent to keep going.
  "remote", // A message sent from another device.
  "schedule", // A routine that fired.
  "gate", // The runtime's stop check sent the agent back to work before it could finish.
  "goal", // The goal runtime continued toward an active goal.
  "checkin", // Background work reported, or a check-in on it was due.
  "ci", // A pull request's CI finished and the agent follows up.
  "unknown", // An origin this reader does not know.
] as const;
export type AgentTurnOrigin = (typeof AGENT_TURN_ORIGIN_VALUES)[number];

/** Why a turn ended. */
export const AGENT_STOP_REASON_VALUES = [
  "end_turn", // The model finished its answer.
  "max_steps", // The turn reached its step limit.
  "max_tokens", // The model reached its output limit.
  "cancelled", // Somebody stopped it.
  "refusal", // The model declined.
  "hook", // A hook ended the run.
  "budget", // A run or goal budget was reached and a wrap-up turn ran.
  "stalled", // Continuation turns in a row made no progress.
  "blocked", // The agent marked the remaining work blocked, or a goal was judged impossible.
  "unknown", // A reason this reader does not know.
] as const;
export type AgentStopReason = (typeof AGENT_STOP_REASON_VALUES)[number];

/** How a user message reached the agent. */
export const AGENT_USER_DELIVERY_VALUES = [
  "prompt", // As the message that starts a turn.
  "steer", // Into a running turn, before its next step.
  "queue", // Held until the running turn ended.
  "unknown", // A delivery this reader does not know.
] as const;
export type AgentUserDelivery = (typeof AGENT_USER_DELIVERY_VALUES)[number];

/** What kind of thing a tool call does. The Agent Client Protocol's kinds, so a bridge to it is a rename. */
export const AGENT_TOOL_KIND_VALUES = [
  "read", // Reads a file or a directory.
  "edit", // Creates, changes, moves or deletes a file.
  "execute", // Runs a command.
  "search", // Searches files or code.
  "fetch", // Reaches the network: a web fetch or a web search.
  "think", // Plans, delegates or records state without touching the workspace.
  "other", // Anything else: an MCP tool, the screen, a test runner.
  "unknown", // A kind this reader does not know.
] as const;
export type AgentToolKind = (typeof AGENT_TOOL_KIND_VALUES)[number];

/** How dangerous an action is. The Swift runtime's five tiers; agent-core's safe/edit/command/sensitive map onto read/write/execute/destructive. */
export const AGENT_RISK_VALUES = [
  "read", // Reads or searches inside the workspace.
  "write", // Creates or changes files inside the workspace.
  "execute", // Runs a command whose effects stay in the workspace.
  "critical", // Reaches the network or runs arbitrary code, inside the workspace.
  "destructive", // Escapes the workspace or cannot be undone.
  "unknown", // A tier this reader does not know.
] as const;
export type AgentRisk = (typeof AGENT_RISK_VALUES)[number];

/** How a tool call ended. Typed, so no reader ever parses an outcome out of a display string. */
export const AGENT_TOOL_RESULT_STATUS_VALUES = [
  "ok", // It ran and succeeded.
  "error", // It ran and failed: a non-zero exit, a missing file, a refused write.
  "denied", // It never ran because an approval, a rule or the mode refused it.
  "not_executed", // It never ran: the turn was steered or stopped before its turn came.
  "unknown", // It may have run and nobody knows how it ended: the host went away mid-call.
] as const;
export type AgentToolResultStatus = (typeof AGENT_TOOL_RESULT_STATUS_VALUES)[number];

/** Which stream a chunk of live output came from. */
export const AGENT_OUTPUT_CHANNEL_VALUES = [
  "stdout", // Standard output.
  "stderr", // Standard error.
  "log", // The host's own log line about the call.
  "unknown", // A channel this reader does not know.
] as const;
export type AgentOutputChannel = (typeof AGENT_OUTPUT_CHANNEL_VALUES)[number];

/** What happened to a file. */
export const AGENT_FILE_CHANGE_KIND_VALUES = [
  "created", // It did not exist before.
  "modified", // Its contents changed.
  "deleted", // It no longer exists.
  "moved", // It was renamed or moved.
  "unknown", // A change this reader does not know.
] as const;
export type AgentFileChangeKind = (typeof AGENT_FILE_CHANGE_KIND_VALUES)[number];

/** Where a delegated agent is in its life. The raw values are agent-core's and the Swift runtime's, character for character. */
export const AGENT_SUBAGENT_STATUS_VALUES = [
  "queued", // Accepted, waiting for a slot.
  "preparing", // Its session and tools are being built.
  "running", // Working.
  "waiting_approval", // Blocked on an approval.
  "completed", // Finished its task.
  "failed", // Could not finish.
  "cancelled", // Stopped by somebody.
  "interrupted", // The process ended before it did.
  "unknown", // A status this reader does not know.
] as const;
export type AgentSubagentStatus = (typeof AGENT_SUBAGENT_STATUS_VALUES)[number];

/** The answer to an approval request. The Agent Client Protocol's option names, plus redirect. */
export const AGENT_APPROVAL_DECISION_VALUES = [
  "allow_once", // This action, this once.
  "allow_always", // This action, and every one the saved rule matches from now on.
  "deny", // Not this action.
  "redirect", // Not this action; do this instead (the feedback says what).
  "unknown", // A decision this reader does not know.
] as const;
export type AgentApprovalDecision = (typeof AGENT_APPROVAL_DECISION_VALUES)[number];

/** Who or what answered an approval. A cloud run's automatic answer is recorded as `mode` rather than written as a person's. */
export const AGENT_APPROVAL_RESOLVER_VALUES = [
  "user", // A person answered.
  "rule", // A saved permission rule answered.
  "mode", // The permission mode answered, with nobody asked.
  "hook", // A hook answered.
  "timeout", // Nobody answered in time.
  "host", // The host answered for its own reasons: the session ended, the request went stale.
  "unknown", // A resolver this reader does not know.
] as const;
export type AgentApprovalResolver = (typeof AGENT_APPROVAL_RESOLVER_VALUES)[number];

/** Where one step of a plan or todo list stands. */
export const AGENT_PLAN_STEP_STATUS_VALUES = [
  "pending", // Not started.
  "in_progress", // Being worked on.
  "completed", // Done.
  "blocked", // Cannot move without something else.
  "cancelled", // Dropped.
  "unknown", // A status this reader does not know.
] as const;
export type AgentPlanStepStatus = (typeof AGENT_PLAN_STEP_STATUS_VALUES)[number];

/** The answer to a proposed plan. */
export const AGENT_PLAN_DECISION_VALUES = [
  "approved", // Go ahead and carry it out.
  "rejected", // Do not carry it out.
  "unknown", // A decision this reader does not know.
] as const;
export type AgentPlanDecision = (typeof AGENT_PLAN_DECISION_VALUES)[number];

/** Who a quiet note in the transcript is from. */
export const AGENT_NOTICE_SOURCE_VALUES = [
  "hook", // A project hook stepped in or failed.
  "runtime", // The agent runtime itself.
  "host", // The machine running the session: a setup step, a clone, a push.
  "unknown", // A source this reader does not know.
] as const;
export type AgentNoticeSource = (typeof AGENT_NOTICE_SOURCE_VALUES)[number];

/** Who wrote a compaction summary. */
export const AGENT_COMPACTION_SOURCE_VALUES = [
  "model", // The session's own model.
  "structural", // The runtime's bounded fallback notes.
  "unknown", // A source this reader does not know.
] as const;
export type AgentCompactionSource = (typeof AGENT_COMPACTION_SOURCE_VALUES)[number];

/** What class of failure an error is, so a reader can decide what to offer without reading the message. */
export const AGENT_ERROR_CODE_VALUES = [
  "plan_limit", // The account's plan limit was reached.
  "rate_limited", // The provider throttled the request.
  "provider_overload", // The provider was overloaded or unavailable.
  "context_overflow", // The conversation no longer fits the model's context.
  "tool_error", // A tool failed in a way the turn could not recover from.
  "network", // The host lost its connection.
  "cancelled", // Stopped by somebody.
  "internal", // Anything else.
  "unknown", // A code this reader does not know.
] as const;
export type AgentErrorCode = (typeof AGENT_ERROR_CODE_VALUES)[number];

/** Whose model calls a usage report counts. */
export const AGENT_USAGE_SCOPE_VALUES = [
  "turn", // The session's own turn.
  "subagent", // A delegated agent's calls (the envelope's agentId says which).
  "compaction", // The call that summarised older turns.
  "unknown", // A scope this reader does not know.
] as const;
export type AgentUsageScope = (typeof AGENT_USAGE_SCOPE_VALUES)[number];

/** Where a command stands at the host. */
export const AGENT_COMMAND_DISPOSITION_VALUES = [
  "pending", // Stored, not yet claimed.
  "claimed", // A host has it and is acting on it.
  "completed", // Done.
  "rejected", // The host refused it; errorCode says why.
  "expired", // Nobody claimed it before expiresAt.
  "cancelled", // Withdrawn by its sender.
  "unknown", // A disposition this reader does not know.
] as const;
export type AgentCommandDisposition = (typeof AGENT_COMMAND_DISPOSITION_VALUES)[number];

/** Why a run ended. Every run ends with exactly one. */
export const AGENT_RUN_END_REASON_VALUES = [
  "done_checked", // The stop check passed and fresh passing checks cover the change.
  "done_unchecked", // The stop check passed, but no check is known or the change needs none.
  "checks_failing", // The agent finished after being sent back once, and a check still fails.
  "blocked", // The remaining work is blocked, with a reason, or a goal was judged impossible.
  "needs_you", // Waiting for an approval or an answer, parked until the reader decides.
  "step_limit", // The step limit was reached and a wrap-up turn ran.
  "budget", // A run or goal budget was reached and a wrap-up turn ran. Never done.
  "stalled", // Two continuation turns in a row made no tool call.
  "waiting_on_background", // Background work still runs; the run resumes when it reports.
  "stopped", // The reader pressed Stop.
  "interrupted", // The host quit or crashed mid-run.
  "error", // An error the retry policy could not clear.
  "unknown", // A value this reader does not know.
] as const;
export type AgentRunEndReason = (typeof AGENT_RUN_END_REASON_VALUES)[number];

/** Why the runtime kept a run going with no new reader message. */
export const AGENT_CONTINUE_REASON_VALUES = [
  "todos_open", // Todo items were still open.
  "unverified", // Files changed and no check has run since the last edit.
  "checks_failing", // The latest check after the last edit failed.
  "ui_unchecked", // A visible change was not yet looked at in the running result.
  "diff_unreviewed", // The diff was not read since the last edit.
  "review_findings", // The self-review found problems that are not yet answered.
  "goal_not_met", // The active goal is not met yet.
  "output_limit", // The model's output was cut off at its limit.
  "retry", // The reader asked to try a failed turn again.
  "after_quit", // The host quit mid-run and the reader resumed it.
  "keep_going", // The reader granted another block of steps or budget.
  "wrap_up", // The last turn before a limit: summarise and stop.
  "checkin", // Background work reported, or a check-in on it was due.
  "unknown", // A value this reader does not know.
] as const;
export type AgentContinueReason = (typeof AGENT_CONTINUE_REASON_VALUES)[number];

/** What a check is for. */
export const AGENT_CHECK_KIND_VALUES = [
  "build", // Builds the project.
  "test", // Runs tests.
  "lint", // Runs a linter.
  "typecheck", // Runs a type checker.
  "custom", // Anything else the project records as a check.
  "unknown", // A value this reader does not know.
] as const;
export type AgentCheckKind = (typeof AGENT_CHECK_KIND_VALUES)[number];

/** Where a UI check looked. */
export const AGENT_VERIFY_SURFACE_VALUES = [
  "web", // A web page in the preview.
  "ios", // An app in the iOS Simulator.
  "mac", // A Mac app, through app-scoped screen control.
  "unknown", // A value this reader does not know.
] as const;
export type AgentVerifySurface = (typeof AGENT_VERIFY_SURFACE_VALUES)[number];

/** How serious a review finding is. */
export const AGENT_REVIEW_PRIORITY_VALUES = [
  "p0", // Breaks something that matters now.
  "p1", // A real correctness, security or requirement problem.
  "p2", // Worth fixing; does not block.
  "p3", // A note.
  "unknown", // A value this reader does not know.
] as const;
export type AgentReviewPriority = (typeof AGENT_REVIEW_PRIORITY_VALUES)[number];

/** The reviewer's overall judgement of a diff. */
export const AGENT_REVIEW_OVERALL_VALUES = [
  "correct", // No blocking problems.
  "incorrect", // At least one blocking problem.
  "unknown", // A value this reader does not know.
] as const;
export type AgentReviewOverall = (typeof AGENT_REVIEW_OVERALL_VALUES)[number];

/** Where a goal stands. */
export const AGENT_GOAL_STATUS_VALUES = [
  "active", // Being worked toward.
  "paused", // Kept, not worked on until resumed.
  "needs_you", // Waiting on the reader, with a reason.
  "budget_reached", // Its budget ran out; Keep going adds another.
  "achieved", // Met, with evidence.
  "impossible", // Judged impossible, with a reason.
  "cleared", // Dropped by the reader.
  "unknown", // A value this reader does not know.
] as const;
export type AgentGoalStatus = (typeof AGENT_GOAL_STATUS_VALUES)[number];

/** What a check of a goal concluded. */
export const AGENT_GOAL_VERDICT_VALUES = [
  "not_met", // Not met yet.
  "met", // Met.
  "impossible", // Cannot be met.
  "gate_blocked", // The deterministic checks found something missing before any judge was asked.
  "unknown", // A value this reader does not know.
] as const;
export type AgentGoalVerdict = (typeof AGENT_GOAL_VERDICT_VALUES)[number];

/** Who set a goal. */
export const AGENT_GOAL_ORIGIN_VALUES = [
  "reader", // The reader, with /goal.
  "plan", // An approved plan carried out as a goal.
  "ci", // Fixing a pull request's failing checks.
  "proposed_by_model", // The agent proposed it and the reader started it.
  "unknown", // A value this reader does not know.
] as const;
export type AgentGoalOrigin = (typeof AGENT_GOAL_ORIGIN_VALUES)[number];

/** How one goal criterion is checked. */
export const AGENT_CRITERION_CHECK_VALUES = [
  "command", // A fresh passing run of a recorded check.
  "ui", // A fresh UI check of a target.
  "judged", // Judged from the conversation.
  "unknown", // A value this reader does not know.
] as const;
export type AgentCriterionCheck = (typeof AGENT_CRITERION_CHECK_VALUES)[number];

/** Where one CI check stands. */
export const AGENT_CICHECK_STATE_VALUES = [
  "queued", // Waiting to start.
  "running", // Running.
  "passed", // Passed.
  "failed", // Failed.
  "cancelled", // Cancelled.
  "skipped", // Skipped.
  "unknown", // A value this reader does not know.
] as const;
export type AgentCICheckState = (typeof AGENT_CICHECK_STATE_VALUES)[number];

/** Whose budget a limit belongs to. */
export const AGENT_BUDGET_SCOPE_VALUES = [
  "run", // One run's.
  "goal", // A goal's, across its runs.
  "unknown", // A value this reader does not know.
] as const;
export type AgentBudgetScope = (typeof AGENT_BUDGET_SCOPE_VALUES)[number];

/** Which ceiling of a budget was reached. */
export const AGENT_BUDGET_LIMIT_VALUES = [
  "minutes", // Time.
  "turns", // Continuation turns.
  "tokens", // Model tokens.
  "cost", // Spend.
  "unknown", // A value this reader does not know.
] as const;
export type AgentBudgetLimit = (typeof AGENT_BUDGET_LIMIT_VALUES)[number];

// ── Types ───────────────────────────────────────────────────────────────────

/** A repository a cloud session works on. */
export interface AgentRepositoryRef {
  /** The owner, as the forge names it. */
  owner: string;
  /** The repository name. */
  name: string;
  /** The branch the work starts from. */
  baseRef?: string;
}

/** One failure, typed. */
export interface AgentErrorInfo {
  /** The class of failure. */
  code: AgentErrorCode;
  /** What went wrong, for a person. */
  message: string;
  /** Whether trying the same thing again could succeed. */
  retryable: boolean;
}

/** Model usage. Every count is what the provider reported; nothing is estimated. */
export interface AgentUsage {
  /** Uncached input tokens. */
  inputTokens: number;
  /** Output tokens, including reasoning. */
  outputTokens: number;
  /** Input tokens read from the prompt cache. */
  cacheReadTokens?: number;
  /** Input tokens written to the prompt cache. */
  cacheWriteTokens?: number;
  /** The part of outputTokens spent thinking, when the provider says. */
  reasoningTokens?: number;
  /** What these calls cost, in millionths of a US dollar, when the producer knows. */
  costMicroUsd?: number;
}

/** One step of a plan or todo list. */
export interface AgentPlanStep {
  /** Stable for the life of the plan. */
  id: string;
  /** What the step is. */
  text: string;
  /** Where it stands. */
  status: AgentPlanStepStatus;
}

/** One offered answer to a question. */
export interface AgentQuestionOption {
  /** What the answer sends back. */
  id: string;
  /** What the reader sees. */
  label: string;
}

/** A ceiling on what a run or goal may spend. An absent field is unlimited. */
export interface AgentBudget {
  /** Wall-clock minutes. */
  minutes?: number;
  /** Continuation turns. */
  turns?: number;
  /** Model tokens, children included. */
  tokens?: number;
  /** Spend, in millionths of a US dollar. */
  costMicroUsd?: number;
}

/** What a run or goal has spent so far, children included. */
export interface AgentBudgetUsage {
  /** Wall-clock minutes. */
  minutes?: number;
  /** Continuation turns. */
  turns?: number;
  /** Model tokens. */
  tokens?: number;
  /** Spend, in millionths of a US dollar. */
  costMicroUsd?: number;
}

/** One row of a run report's Checked section, rendered only from recorded evidence. */
export interface AgentRunCheck {
  /** What was checked: a command, a preview route, the review. */
  label: string;
  /** Whether it passed. */
  passed: boolean;
  /** More, in words: duration, test count, after the last edit. */
  detail?: string;
}

/** One condition a UI check tested. */
export interface AgentUICheck {
  /** The condition, in words: HTTP 200, no new console errors. */
  name: string;
  /** Whether it held. */
  passed: boolean;
  /** Why it failed, or a detail worth keeping. */
  detail?: string;
}

/** One problem a self-review found in the diff. */
export interface AgentReviewFinding {
  /** How serious it is. */
  priority: AgentReviewPriority;
  /** The problem in one line. */
  title: string;
  /** 0 to 1, as the reviewer reported it. */
  confidence?: number;
  /** The file, relative to the workspace. */
  path?: string;
  /** The line. */
  line?: number;
  /** The explanation, bounded. */
  body?: string;
  /** The goal criterion it concerns, for a requirement gap. */
  criterion?: string;
}

/** One criterion of a goal. */
export interface AgentGoalCriterion {
  /** Stable for the goal: c1, c2. */
  id: string;
  /** What must be true. */
  text: string;
  /** How it is checked. */
  check: AgentCriterionCheck;
  /** The recorded check, for a command criterion. */
  checkId?: string;
  /** Where to look, for a UI criterion. */
  surface?: AgentVerifySurface;
  /** The route or app, for a UI criterion. */
  target?: string;
  /** Whether the evidence satisfies it now, when known. */
  met?: boolean;
}

/** One CI check on a pull request. */
export interface AgentCICheck {
  /** The check's name. */
  name: string;
  /** Where it stands. */
  state: AgentCICheckState;
  /** Its page, when the forge gave one. */
  url?: string;
}

/** What a host reports about a command. */
export interface AgentCommandReceipt {
  /** The command. */
  commandId: string;
  /** Its key. */
  idempotencyKey: string;
  /** Where it stands. */
  disposition: AgentCommandDisposition;
  /** Why it was rejected. */
  errorCode?: string;
  /** When the host said so. */
  at: string;
}

// ── Events ──────────────────────────────────────────────────────────────────

/** Every event carries these keys, beside its own. */
export interface AgentEventEnvelope {
  /** The protocol version the producer wrote, "<major>.<minor>". A reader refuses a major it does not know. */
  v: string;
  /** Unique per event and stable across retries: readers drop an id they have already applied. */
  id: string;
  /** The session this event belongs to. */
  sessionId: string;
  /** 1-based and increasing within one producer's stream of a session. Order, not identity; the id is the identity. */
  seq: number;
  /** When it happened, at the producer. */
  at: string;
  /** The turn it belongs to. Absent means the turn that is open, if any. */
  turnId?: string;
  /** The delegated agent it belongs to. Absent means the session's own agent. */
  agentId?: string;
}

/** A session began. The first event of every transcript. */
export interface AgentSessionCreatedEvent extends AgentEventEnvelope {
  type: "session.created";
  /** Where it runs. */
  target: AgentSessionTarget;
  /** The folder's display name. Never an absolute path. */
  workspaceName?: string;
  /** The repository, for a cloud session. */
  repository?: AgentRepositoryRef;
  /** The model it starts with. */
  model?: string;
  /** The thinking level it starts with. */
  effort?: AgentReasoningEffort;
  /** The permission mode it starts with. */
  mode?: AgentPermissionMode;
  /** Its title, when it has one. */
  title?: string;
}

/** What the next turn runs with. Only the fields that are set changed. */
export interface AgentSessionConfiguredEvent extends AgentEventEnvelope {
  type: "session.configured";
  /** The model. */
  model?: string;
  /** The thinking level. */
  effort?: AgentReasoningEffort;
  /** The permission mode in force. */
  mode?: AgentPermissionMode;
  /** What the agent is instructed to do. */
  behavior?: AgentTurnBehavior;
  /** A new title. */
  title?: string;
}

/** The session's state changed. */
export interface AgentSessionStateEvent extends AgentEventEnvelope {
  type: "session.state";
  /** The new state. */
  state: AgentSessionState;
  /** Why, when there is more to say than the state. */
  reason?: string;
}

/** A turn began. Carries the turnId every event of the turn may name. */
export interface AgentTurnStartedEvent extends AgentEventEnvelope {
  type: "turn.started";
  /** What started it. */
  origin: AgentTurnOrigin;
}

/** A turn ended normally. */
export interface AgentTurnCompletedEvent extends AgentEventEnvelope {
  type: "turn.completed";
  /** Why it ended. */
  stopReason: AgentStopReason;
  /** How long it took. */
  durationMs?: number;
  /** How many files it changed. */
  filesChanged?: number;
  /** What it did, in a sentence, when the producer has one. */
  summary?: string;
}

/** A turn ended because something went wrong. */
export interface AgentTurnFailedEvent extends AgentEventEnvelope {
  type: "turn.failed";
  /** What went wrong. */
  error: AgentErrorInfo;
}

/** A turn ended without finishing and without failing: a stop, a quit, a lost host. Any tool call still running has an unknown outcome. */
export interface AgentTurnInterruptedEvent extends AgentEventEnvelope {
  type: "turn.interrupted";
  /** What interrupted it. */
  reason?: string;
}

/** The transcript was rewound. A reader drops every turn and item it holds and rebuilds from the events that follow. */
export interface AgentTranscriptRestartedEvent extends AgentEventEnvelope {
  type: "transcript.restarted";
  /** The turn the session was rewound to, which is no longer in the transcript. */
  rewoundToTurnId?: string;
}

/** A message from the reader. */
export interface AgentItemUserMessageEvent extends AgentEventEnvelope {
  type: "item.user_message";
  /** Stable for this message. */
  itemId: string;
  /** What they wrote, as they wrote it (attachments are not inlined). */
  text: string;
  /** How it reached the agent. */
  delivery: AgentUserDelivery;
  /** The command that carried it, so the sender can mark it delivered. */
  commandId?: string;
}

/** More of the agent's reply. Appended to the item's text. */
export interface AgentItemAssistantTextDeltaEvent extends AgentEventEnvelope {
  type: "item.assistant_text.delta";
  /** The reply this belongs to. */
  itemId: string;
  /** The next piece. */
  text: string;
}

/** The whole of one reply. Replaces whatever the deltas built. */
export interface AgentItemAssistantTextEvent extends AgentEventEnvelope {
  type: "item.assistant_text";
  /** The reply. */
  itemId: string;
  /** Its full text. */
  text: string;
}

/** More of the model's visible thinking. Appended to the item's text. */
export interface AgentItemThinkingDeltaEvent extends AgentEventEnvelope {
  type: "item.thinking.delta";
  /** The thinking block this belongs to. */
  itemId: string;
  /** The next piece. */
  text: string;
}

/** A summary of the model's thinking. Replaces whatever the deltas built. Never raw private chain of thought. */
export interface AgentItemThinkingEvent extends AgentEventEnvelope {
  type: "item.thinking";
  /** The thinking block. */
  itemId: string;
  /** The summary. */
  summary: string;
}

/** The agent called a tool. The call is running until its tool_result arrives. */
export interface AgentItemToolCallEvent extends AgentEventEnvelope {
  type: "item.tool_call";
  /** The provider's call id, stable for the call. */
  itemId: string;
  /** The tool's own name (bash, run_command, read_file, …). */
  toolName: string;
  /** What kind of thing it does. */
  toolKind: AgentToolKind;
  /** One line for a person: `$ npm test`, `Read src/app.ts`. */
  title: string;
  /** A bounded, redacted summary of the input. Never a whole file. */
  inputSummary?: string;
  /** How dangerous the call is. */
  risk?: AgentRisk;
}

/** A chunk of a running call's live output. */
export interface AgentItemToolOutputEvent extends AgentEventEnvelope {
  type: "item.tool_output";
  /** The call. */
  itemId: string;
  /** Which stream. */
  channel: AgentOutputChannel;
  /** The chunk, bounded and redacted. */
  text: string;
}

/** How a tool call ended. */
export interface AgentItemToolResultEvent extends AgentEventEnvelope {
  type: "item.tool_result";
  /** The call. */
  itemId: string;
  /** How it ended. */
  status: AgentToolResultStatus;
  /** One line on the outcome. */
  summary?: string;
  /** The process's exit status, when it ran one. */
  exitCode?: number;
  /** How long it ran. */
  durationMs?: number;
  /** The tail of its output, bounded and redacted. */
  output?: string;
}

/** A file changed. */
export interface AgentItemFileChangeEvent extends AgentEventEnvelope {
  type: "item.file_change";
  /** Stable for this change. */
  itemId: string;
  /** Relative to the workspace. Never an absolute path. */
  path: string;
  /** What happened to it. */
  change: AgentFileChangeKind;
  /** Lines added. */
  linesAdded: number;
  /** Lines removed. */
  linesRemoved: number;
  /** A unified diff, bounded. Absent means none was sent, never that the change was empty. */
  patch?: string;
  /** The checkpoint taken before it, which an undo names. */
  checkpointId?: string;
  /** The tool call that made it. */
  toolItemId?: string;
}

/** A test run finished. */
export interface AgentItemTestRunEvent extends AgentEventEnvelope {
  type: "item.test_run";
  /** Stable for this run. */
  itemId: string;
  /** The command that ran the tests. */
  command: string;
  /** Whether every test passed. */
  passed: boolean;
  /** How many ran, when the runner said. */
  testsRun?: number;
  /** How many failed, when the runner said. */
  failures?: number;
  /** How long it took. */
  durationMs?: number;
}

/** A delegated agent's state, sent whenever it changes. The latest one wins. */
export interface AgentItemSubagentEvent extends AgentEventEnvelope {
  type: "item.subagent";
  /** The agent's id, stable for its life. */
  itemId: string;
  /** What it was asked to do, in a few words. */
  title: string;
  /** Where it is. */
  status: AgentSubagentStatus;
  /** Its role (builder, reviewer, …). */
  role?: string;
  /** What it is doing right now. */
  activity?: string;
  /** Its result, bounded. */
  summary?: string;
  /** Why it failed. */
  error?: string;
  /** The delegating tool call. */
  toolItemId?: string;
  /** Its own model usage so far. */
  usage?: AgentUsage;
}

/** Older turns now reach the model as a summary. The transcript keeps them; only what the model is sent shrank. */
export interface AgentItemCompactionEvent extends AgentEventEnvelope {
  type: "item.compaction";
  /** Stable for this compaction. */
  itemId: string;
  /** Who wrote the summary. */
  source: AgentCompactionSource;
  /** Model messages before. */
  beforeMessages?: number;
  /** Model messages after. */
  afterMessages?: number;
  /** Whether the reader asked for it. */
  requestedByUser?: boolean;
}

/** A quiet line the reader is owed: a hook stepped in, a setup step ran, the context was folded. */
export interface AgentItemNoticeEvent extends AgentEventEnvelope {
  type: "item.notice";
  /** Stable for this notice. */
  itemId: string;
  /** Who it is from. */
  source: AgentNoticeSource;
  /** The line. */
  text: string;
  /** More, bounded. */
  detail?: string;
}

/** The agent is waiting for a yes or a no. */
export interface AgentApprovalRequestedEvent extends AgentEventEnvelope {
  type: "approval.requested";
  /** What the answer names. */
  approvalId: string;
  /** The tool call it is about. */
  itemId?: string;
  /** The tool or action, by name. */
  action: string;
  /** What would happen, for a person: the command, the path. */
  summary: string;
  /** How dangerous it is. */
  risk: AgentRisk;
  /** SHA-256 of the exact action, so an answer can only approve what was shown. */
  digest?: string;
  /** When the request goes stale. */
  expiresAt?: string;
  /** The rule allow_always would save, in Tool(pattern) grammar. */
  suggestedRule?: string;
}

/** An approval was answered. */
export interface AgentApprovalResolvedEvent extends AgentEventEnvelope {
  type: "approval.resolved";
  /** The request. */
  approvalId: string;
  /** The answer. */
  decision: AgentApprovalDecision;
  /** Who answered. */
  by: AgentApprovalResolver;
  /** What to do instead, with redirect; why, with deny. */
  feedback?: string;
}

/** The agent asked the reader something and is waiting. */
export interface AgentQuestionAskedEvent extends AgentEventEnvelope {
  type: "question.asked";
  /** What the answer names. */
  questionId: string;
  /** The question. */
  prompt: string;
  /** Offered answers, when it is a choice. */
  options?: AgentQuestionOption[];
  /** Whether more than one option may be chosen. */
  multiSelect?: boolean;
  /** When the agent stops waiting. */
  expiresAt?: string;
}

/** A question was answered. */
export interface AgentQuestionAnsweredEvent extends AgentEventEnvelope {
  type: "question.answered";
  /** The question. */
  questionId: string;
  /** A written answer. */
  answer?: string;
  /** The chosen option ids. */
  selected?: string[];
}

/** The whole todo list, as it now stands. Each snapshot replaces the last. */
export interface AgentPlanUpdatedEvent extends AgentEventEnvelope {
  type: "plan.updated";
  /** Every step, in order. */
  steps: AgentPlanStep[];
  /** What the list is for. */
  objective?: string;
}

/** In plan mode, the agent proposes what it would do and waits for a decision before changing anything. */
export interface AgentPlanProposedEvent extends AgentEventEnvelope {
  type: "plan.proposed";
  /** What the decision names. */
  planId: string;
  /** The plan, as Markdown. */
  text: string;
}

/** A proposed plan was approved or rejected. */
export interface AgentPlanResolvedEvent extends AgentEventEnvelope {
  type: "plan.resolved";
  /** The plan. */
  planId: string;
  /** The answer. */
  decision: AgentPlanDecision;
}

/** Model usage incurred since the producer's previous usage report. Readers add them up. */
export interface AgentUsageUpdatedEvent extends AgentEventEnvelope {
  type: "usage.updated";
  /** The counts. */
  usage: AgentUsage;
  /** The model the calls went to. */
  model?: string;
  /** Whose calls these were. */
  scope: AgentUsageScope;
}

/** Something went wrong that the reader should see. Whether the turn goes on is said by the turn events, not here. */
export interface AgentSessionErrorEvent extends AgentEventEnvelope {
  type: "session.error";
  /** What went wrong. */
  error: AgentErrorInfo;
}

/** The runtime kept the run going with no new reader message: the stop check sent the agent back, or the reader resumed. A quiet caption, never the reader's words. */
export interface AgentRunContinuedEvent extends AgentEventEnvelope {
  type: "run.continued";
  /** Why. */
  reason: AgentContinueReason;
  /** The concrete fact, for the caption: 2 todos were open. */
  detail: string;
  /** The workspace revision it was decided at. */
  revision?: number;
}

/** How a run ended, with the report the runtime built from its recorded evidence. */
export interface AgentRunOutcomeEvent extends AgentEventEnvelope {
  type: "run.outcome";
  /** Why it ended. */
  endReason: AgentRunEndReason;
  /** The outcome in one sentence. */
  summary: string;
  /** What was checked, in words: Checked with swift test; Not checked: no test command. */
  verification?: string;
  /** The Checked rows, only from recorded evidence. */
  checks?: AgentRunCheck[];
  /** What was not checked, plainly. */
  notChecked?: string[];
  /** What is left or recommended next. */
  left?: string[];
  /** How many files the run changed. */
  filesChanged?: number;
  /** How long the run took. */
  durationMs?: number;
}

/** A check ran and its result counts as evidence. Recorded by the runtime, never claimed by the model. */
export interface AgentVerifyResultEvent extends AgentEventEnvelope {
  type: "verify.result";
  /** The command that ran. */
  command: string;
  /** Whether it passed. */
  passed: boolean;
  /** Its exit status. */
  exitCode: number;
  /** The workspace revision it ran at; it counts only while the workspace is still there. */
  revision: number;
  /** The recorded check it matched, when it matched one. */
  check?: string;
  /** What the check is for. */
  kind?: AgentCheckKind;
  /** How long it ran. */
  durationMs?: number;
  /** The failing tail or a pass summary, bounded and redacted. */
  excerpt?: string;
}

/** The running result was looked at: a preview route, a Simulator screen, a Mac app. */
export interface AgentVerifyUiEvent extends AgentEventEnvelope {
  type: "verify.ui";
  /** Where. */
  surface: AgentVerifySurface;
  /** The route, the bundle id or the app. */
  target: string;
  /** Whether every condition held. */
  passed: boolean;
  /** The workspace revision it was checked at. */
  revision: number;
  /** The viewport or device, when there is more than one. */
  viewport?: string;
  /** Each condition and whether it held. */
  checks?: AgentUICheck[];
  /** SHA-256 of the screenshot kept as evidence. */
  screenshotHash?: string;
}

/** A self-review of the diff finished. */
export interface AgentReviewFindingsEvent extends AgentEventEnvelope {
  type: "review.findings";
  /** 1 for a run's first review. */
  round: number;
  /** The overall judgement. */
  overall: AgentReviewOverall;
  /** What it found. Empty is a clean review. */
  findings?: AgentReviewFinding[];
  /** The reviewer's summary. */
  summary?: string;
  /** The workspace revision it reviewed. */
  revision?: number;
}

/** A goal was set. Setting one never changes the permission mode. */
export interface AgentGoalSetEvent extends AgentEventEnvelope {
  type: "goal.set";
  /** Stable for the goal. */
  goalId: string;
  /** What the goal is. */
  objective: string;
  /** What must be true for it to be met. */
  criteria?: AgentGoalCriterion[];
  /** What must not happen along the way. */
  constraints?: string[];
  /** Its budget. */
  budget?: AgentBudget;
  /** Who set it. */
  origin?: AgentGoalOrigin;
}

/** A goal's objective, criteria, constraints or budget changed. Only the fields that are set changed. */
export interface AgentGoalUpdatedEvent extends AgentEventEnvelope {
  type: "goal.updated";
  /** The goal. */
  goalId: string;
  /** The new objective. */
  objective?: string;
  /** The new criteria, whole. */
  criteria?: AgentGoalCriterion[];
  /** The new constraints, whole. */
  constraints?: string[];
  /** The new budget. */
  budget?: AgentBudget;
}

/** A goal was checked: the deterministic part, then the judge. The judge can only say keep working, met or impossible; it never allows anything. */
export interface AgentGoalVerdictEvent extends AgentEventEnvelope {
  type: "goal.verdict";
  /** The goal. */
  goalId: string;
  /** What the check concluded. */
  verdict: AgentGoalVerdict;
  /** Why, in at most 300 characters. */
  reason: string;
  /** The criteria not yet met. */
  unmetCriteria?: string[];
  /** The workspace revision it was checked at. */
  revision?: number;
}

/** A goal's status or spend changed. */
export interface AgentGoalStatusEvent extends AgentEventEnvelope {
  type: "goal.status";
  /** The goal. */
  goalId: string;
  /** Where it stands. */
  status: AgentGoalStatus;
  /** Why, in words, above all when it needs the reader. */
  reason?: string;
  /** What it has spent. */
  usage?: AgentBudgetUsage;
  /** Its budget. */
  budget?: AgentBudget;
}

/** Background work kept the run waiting long enough that the agent is asked to read it, keep waiting, or stop what is stuck. */
export interface AgentCheckinDueEvent extends AgentEventEnvelope {
  type: "checkin.due";
  /** What is still running, in words. */
  running: string[];
  /** How long the run has waited. */
  waitedMs?: number;
  /** Idle check-ins since the reader's last message. */
  idleCheckIns?: number;
}

/** CI for a pull request the agent opened moved. */
export interface AgentCiStatusEvent extends AgentEventEnvelope {
  type: "ci.status";
  /** Every check, as it now stands. */
  checks: AgentCICheck[];
  /** The pull request's number. */
  prNumber?: number;
  /** The pull request. */
  prUrl?: string;
}

/** A run or goal budget was reached. A wrap-up turn follows; reaching a budget is never done, and Keep going adds the same budget again. */
export interface AgentBudgetReachedEvent extends AgentEventEnvelope {
  type: "budget.reached";
  /** Whose budget. */
  scope: AgentBudgetScope;
  /** Which ceiling. */
  limit: AgentBudgetLimit;
  /** The goal, for a goal's budget. */
  goalId?: string;
  /** What was spent. */
  usage?: AgentBudgetUsage;
  /** The budget that was reached. */
  budget?: AgentBudget;
}

/** Code extension: a cloud run pushed a branch, and opened or reused a pull request. */
export interface AgentCodePullRequestEvent extends AgentEventEnvelope {
  type: "code.pull_request";
  /** The branch on origin. */
  branch: string;
  /** The pull request, when there is one. */
  prUrl?: string;
  /** Its number. */
  prNumber?: number;
  /** Whether it already existed and this run added to it. */
  reused?: boolean;
}

/** Every event this build knows. */
export type AgentEvent =
  | AgentSessionCreatedEvent
  | AgentSessionConfiguredEvent
  | AgentSessionStateEvent
  | AgentTurnStartedEvent
  | AgentTurnCompletedEvent
  | AgentTurnFailedEvent
  | AgentTurnInterruptedEvent
  | AgentTranscriptRestartedEvent
  | AgentItemUserMessageEvent
  | AgentItemAssistantTextDeltaEvent
  | AgentItemAssistantTextEvent
  | AgentItemThinkingDeltaEvent
  | AgentItemThinkingEvent
  | AgentItemToolCallEvent
  | AgentItemToolOutputEvent
  | AgentItemToolResultEvent
  | AgentItemFileChangeEvent
  | AgentItemTestRunEvent
  | AgentItemSubagentEvent
  | AgentItemCompactionEvent
  | AgentItemNoticeEvent
  | AgentApprovalRequestedEvent
  | AgentApprovalResolvedEvent
  | AgentQuestionAskedEvent
  | AgentQuestionAnsweredEvent
  | AgentPlanUpdatedEvent
  | AgentPlanProposedEvent
  | AgentPlanResolvedEvent
  | AgentUsageUpdatedEvent
  | AgentSessionErrorEvent
  | AgentRunContinuedEvent
  | AgentRunOutcomeEvent
  | AgentVerifyResultEvent
  | AgentVerifyUiEvent
  | AgentReviewFindingsEvent
  | AgentGoalSetEvent
  | AgentGoalUpdatedEvent
  | AgentGoalVerdictEvent
  | AgentGoalStatusEvent
  | AgentCheckinDueEvent
  | AgentCiStatusEvent
  | AgentBudgetReachedEvent
  | AgentCodePullRequestEvent;
export type AgentEventType = AgentEvent["type"];
export type AgentEventOf<T extends AgentEventType> = Extract<AgentEvent, { type: T }>;
/** What a producer supplies for one event: its type and fields, without the envelope. */
export type AgentEventBody<T extends AgentEventType = AgentEventType> = T extends AgentEventType
  ? Omit<AgentEventOf<T>, keyof AgentEventEnvelope>
  : never;
export const AGENT_EVENT_TYPES = [
  "session.created",
  "session.configured",
  "session.state",
  "turn.started",
  "turn.completed",
  "turn.failed",
  "turn.interrupted",
  "transcript.restarted",
  "item.user_message",
  "item.assistant_text.delta",
  "item.assistant_text",
  "item.thinking.delta",
  "item.thinking",
  "item.tool_call",
  "item.tool_output",
  "item.tool_result",
  "item.file_change",
  "item.test_run",
  "item.subagent",
  "item.compaction",
  "item.notice",
  "approval.requested",
  "approval.resolved",
  "question.asked",
  "question.answered",
  "plan.updated",
  "plan.proposed",
  "plan.resolved",
  "usage.updated",
  "session.error",
  "run.continued",
  "run.outcome",
  "verify.result",
  "verify.ui",
  "review.findings",
  "goal.set",
  "goal.updated",
  "goal.verdict",
  "goal.status",
  "checkin.due",
  "ci.status",
  "budget.reached",
  "code.pull_request",
] as const;

/** An event of a type this build does not know, kept whole. */
export interface UnknownAgentEvent extends AgentEventEnvelope {
  type: "unknown";
  /** The type it arrived with. */
  rawType: string;
  /** The object it arrived as. */
  raw: Record<string, unknown>;
}
export type ParsedAgentEvent = AgentEvent | UnknownAgentEvent;

// ── Commands ────────────────────────────────────────────────────────────────

/** Every command carries these keys, beside its own. A command may be delivered more than once; the host acts on an idempotencyKey once. */
export interface AgentCommandEnvelope {
  /** The protocol version the sender wrote. */
  v: string;
  /** Unique per command. */
  id: string;
  /** Stable across retries of the same intent. */
  idempotencyKey: string;
  /** The session it is for. */
  sessionId: string;
  /** When the sender issued it. */
  issuedAt: string;
  /** After this the host must not act on it, and reports it expired. */
  expiresAt?: string;
}

/** Start a turn with a message. Refused while a turn runs; steer or queue instead. */
export interface AgentTurnSendCommand extends AgentCommandEnvelope {
  type: "turn.send";
  /** The message. */
  text: string;
  /** Uploaded attachments to include. */
  attachmentIds?: string[];
}

/** Give the running turn an instruction, taken before its next step. */
export interface AgentTurnSteerCommand extends AgentCommandEnvelope {
  type: "turn.steer";
  /** The instruction. */
  text: string;
}

/** Hold a message until the running turn ends, then start a turn with it. */
export interface AgentTurnQueueCommand extends AgentCommandEnvelope {
  type: "turn.queue";
  /** The message. */
  text: string;
}

/** Stop the running turn. */
export interface AgentTurnCancelCommand extends AgentCommandEnvelope {
  type: "turn.cancel";
  /** Why, for the transcript. */
  reason?: string;
}

/** Answer an approval request. */
export interface AgentApprovalDecideCommand extends AgentCommandEnvelope {
  type: "approval.decide";
  /** The request. */
  approvalId: string;
  /** The answer. */
  decision: AgentApprovalDecision;
  /** The digest that was shown, so a stale answer cannot approve a changed action. */
  digest?: string;
  /** With redirect, what to do instead. */
  feedback?: string;
}

/** Answer a question. */
export interface AgentQuestionAnswerCommand extends AgentCommandEnvelope {
  type: "question.answer";
  /** The question. */
  questionId: string;
  /** A written answer. */
  answer?: string;
  /** The chosen option ids. */
  selected?: string[];
}

/** Approve or reject a proposed plan. */
export interface AgentPlanDecideCommand extends AgentCommandEnvelope {
  type: "plan.decide";
  /** The plan. */
  planId: string;
  /** The answer. */
  decision: AgentPlanDecision;
}

/** Change what the next turn runs with. The host caps a remote sender at its own ceiling. */
export interface AgentSessionSetModeCommand extends AgentCommandEnvelope {
  type: "session.set_mode";
  /** The permission mode. */
  mode?: AgentPermissionMode;
  /** The model. */
  model?: string;
  /** The thinking level. */
  effort?: AgentReasoningEffort;
}

/** Set a goal. The reader sending it is the approval for the goal itself; it never changes the permission mode, and every action still asks as the mode says. */
export interface AgentGoalSetCommand extends AgentCommandEnvelope {
  type: "goal.set";
  /** What the goal is. */
  objective: string;
  /** What must be true, when the sender has criteria. */
  criteria?: string[];
  /** Its budget; absent takes the host's default. */
  budget?: AgentBudget;
}

/** Pause the active goal. The turn in flight finishes its current tool wave; no continuation starts. */
export interface AgentGoalPauseCommand extends AgentCommandEnvelope {
  type: "goal.pause";
  /** The goal; absent means the active one. */
  goalId?: string;
}

/** Resume a paused goal, or one that needs the reader. */
export interface AgentGoalResumeCommand extends AgentCommandEnvelope {
  type: "goal.resume";
  /** The goal; absent means the current one. */
  goalId?: string;
}

/** Change a goal. Only the fields that are set change; the next check uses them. */
export interface AgentGoalEditCommand extends AgentCommandEnvelope {
  type: "goal.edit";
  /** The goal; absent means the current one. */
  goalId?: string;
  /** The new objective. */
  objective?: string;
  /** The new criteria, whole. */
  criteria?: string[];
  /** The new constraints, whole. */
  constraints?: string[];
  /** The new budget. */
  budget?: AgentBudget;
}

/** Clear the goal. It stays readable as history. */
export interface AgentGoalClearCommand extends AgentCommandEnvelope {
  type: "goal.clear";
  /** The goal; absent means the current one. */
  goalId?: string;
}

/** Carry a run on with no new message: retry a failed turn, or resume one the host lost. Refused while a turn runs. */
export interface AgentRunResumeCommand extends AgentCommandEnvelope {
  type: "run.resume";
  /** Why: retry or after_quit. */
  note: AgentContinueReason;
}

/** Grant another block of steps or budget to a run that stopped at a limit, and resume it. */
export interface AgentRunKeepGoingCommand extends AgentCommandEnvelope {
  type: "run.keep_going";
  /** The goal whose budget was reached, when it was a goal's. */
  goalId?: string;
}

export type AgentCommand =
  | AgentTurnSendCommand
  | AgentTurnSteerCommand
  | AgentTurnQueueCommand
  | AgentTurnCancelCommand
  | AgentApprovalDecideCommand
  | AgentQuestionAnswerCommand
  | AgentPlanDecideCommand
  | AgentSessionSetModeCommand
  | AgentGoalSetCommand
  | AgentGoalPauseCommand
  | AgentGoalResumeCommand
  | AgentGoalEditCommand
  | AgentGoalClearCommand
  | AgentRunResumeCommand
  | AgentRunKeepGoingCommand;
export type AgentCommandType = AgentCommand["type"];
export const AGENT_COMMAND_TYPES = [
  "turn.send",
  "turn.steer",
  "turn.queue",
  "turn.cancel",
  "approval.decide",
  "question.answer",
  "plan.decide",
  "session.set_mode",
  "goal.set",
  "goal.pause",
  "goal.resume",
  "goal.edit",
  "goal.clear",
  "run.resume",
  "run.keep_going",
] as const;
export interface UnknownAgentCommand extends AgentCommandEnvelope {
  type: "unknown";
  rawType: string;
  raw: Record<string, unknown>;
}
export type ParsedAgentCommand = AgentCommand | UnknownAgentCommand;

// ── Field tables (what the reader below walks) ──────────────────────────────

const ENUM_VALUES: Record<string, readonly string[]> = {
  SessionTarget: AGENT_SESSION_TARGET_VALUES,
  PermissionMode: AGENT_PERMISSION_MODE_VALUES,
  ReasoningEffort: AGENT_REASONING_EFFORT_VALUES,
  TurnBehavior: AGENT_TURN_BEHAVIOR_VALUES,
  SessionState: AGENT_SESSION_STATE_VALUES,
  TurnOrigin: AGENT_TURN_ORIGIN_VALUES,
  StopReason: AGENT_STOP_REASON_VALUES,
  UserDelivery: AGENT_USER_DELIVERY_VALUES,
  ToolKind: AGENT_TOOL_KIND_VALUES,
  Risk: AGENT_RISK_VALUES,
  ToolResultStatus: AGENT_TOOL_RESULT_STATUS_VALUES,
  OutputChannel: AGENT_OUTPUT_CHANNEL_VALUES,
  FileChangeKind: AGENT_FILE_CHANGE_KIND_VALUES,
  SubagentStatus: AGENT_SUBAGENT_STATUS_VALUES,
  ApprovalDecision: AGENT_APPROVAL_DECISION_VALUES,
  ApprovalResolver: AGENT_APPROVAL_RESOLVER_VALUES,
  PlanStepStatus: AGENT_PLAN_STEP_STATUS_VALUES,
  PlanDecision: AGENT_PLAN_DECISION_VALUES,
  NoticeSource: AGENT_NOTICE_SOURCE_VALUES,
  CompactionSource: AGENT_COMPACTION_SOURCE_VALUES,
  ErrorCode: AGENT_ERROR_CODE_VALUES,
  UsageScope: AGENT_USAGE_SCOPE_VALUES,
  CommandDisposition: AGENT_COMMAND_DISPOSITION_VALUES,
  RunEndReason: AGENT_RUN_END_REASON_VALUES,
  ContinueReason: AGENT_CONTINUE_REASON_VALUES,
  CheckKind: AGENT_CHECK_KIND_VALUES,
  VerifySurface: AGENT_VERIFY_SURFACE_VALUES,
  ReviewPriority: AGENT_REVIEW_PRIORITY_VALUES,
  ReviewOverall: AGENT_REVIEW_OVERALL_VALUES,
  GoalStatus: AGENT_GOAL_STATUS_VALUES,
  GoalVerdict: AGENT_GOAL_VERDICT_VALUES,
  GoalOrigin: AGENT_GOAL_ORIGIN_VALUES,
  CriterionCheck: AGENT_CRITERION_CHECK_VALUES,
  CICheckState: AGENT_CICHECK_STATE_VALUES,
  BudgetScope: AGENT_BUDGET_SCOPE_VALUES,
  BudgetLimit: AGENT_BUDGET_LIMIT_VALUES,
};

const TYPE_FIELDS: Record<string, readonly FieldSpec[]> = {
  RepositoryRef: [
    { key: "owner", kind: "string", optional: false },
    { key: "name", kind: "string", optional: false },
    { key: "baseRef", kind: "string", optional: true },
  ],
  ErrorInfo: [
    { key: "code", kind: "enum", optional: false, ref: "ErrorCode" },
    { key: "message", kind: "string", optional: false },
    { key: "retryable", kind: "boolean", optional: false },
  ],
  Usage: [
    { key: "inputTokens", kind: "integer", optional: false },
    { key: "outputTokens", kind: "integer", optional: false },
    { key: "cacheReadTokens", kind: "integer", optional: true },
    { key: "cacheWriteTokens", kind: "integer", optional: true },
    { key: "reasoningTokens", kind: "integer", optional: true },
    { key: "costMicroUsd", kind: "integer", optional: true },
  ],
  PlanStep: [
    { key: "id", kind: "string", optional: false },
    { key: "text", kind: "string", optional: false },
    { key: "status", kind: "enum", optional: false, ref: "PlanStepStatus" },
  ],
  QuestionOption: [
    { key: "id", kind: "string", optional: false },
    { key: "label", kind: "string", optional: false },
  ],
  Budget: [
    { key: "minutes", kind: "integer", optional: true },
    { key: "turns", kind: "integer", optional: true },
    { key: "tokens", kind: "integer", optional: true },
    { key: "costMicroUsd", kind: "integer", optional: true },
  ],
  BudgetUsage: [
    { key: "minutes", kind: "number", optional: true },
    { key: "turns", kind: "integer", optional: true },
    { key: "tokens", kind: "integer", optional: true },
    { key: "costMicroUsd", kind: "integer", optional: true },
  ],
  RunCheck: [
    { key: "label", kind: "string", optional: false },
    { key: "passed", kind: "boolean", optional: false },
    { key: "detail", kind: "string", optional: true },
  ],
  UICheck: [
    { key: "name", kind: "string", optional: false },
    { key: "passed", kind: "boolean", optional: false },
    { key: "detail", kind: "string", optional: true },
  ],
  ReviewFinding: [
    { key: "priority", kind: "enum", optional: false, ref: "ReviewPriority" },
    { key: "title", kind: "string", optional: false },
    { key: "confidence", kind: "number", optional: true },
    { key: "path", kind: "string", optional: true },
    { key: "line", kind: "integer", optional: true },
    { key: "body", kind: "string", optional: true },
    { key: "criterion", kind: "string", optional: true },
  ],
  GoalCriterion: [
    { key: "id", kind: "string", optional: false },
    { key: "text", kind: "string", optional: false },
    { key: "check", kind: "enum", optional: false, ref: "CriterionCheck" },
    { key: "checkId", kind: "string", optional: true },
    { key: "surface", kind: "enum", optional: true, ref: "VerifySurface" },
    { key: "target", kind: "string", optional: true },
    { key: "met", kind: "boolean", optional: true },
  ],
  CICheck: [
    { key: "name", kind: "string", optional: false },
    { key: "state", kind: "enum", optional: false, ref: "CICheckState" },
    { key: "url", kind: "string", optional: true },
  ],
};

const ENVELOPE_FIELDS: readonly FieldSpec[] = [
  { key: "v", kind: "string", optional: false },
  { key: "id", kind: "string", optional: false },
  { key: "sessionId", kind: "string", optional: false },
  { key: "seq", kind: "integer", optional: false },
  { key: "at", kind: "timestamp", optional: false },
  { key: "turnId", kind: "string", optional: true },
  { key: "agentId", kind: "string", optional: true },
];
const ENVELOPE_KEYS: ReadonlySet<string> = new Set(["v","id","sessionId","seq","at","turnId","agentId","type"]);

const EVENT_FIELDS: Record<string, readonly FieldSpec[]> = {
  "session.created": [
    { key: "target", kind: "enum", optional: false, ref: "SessionTarget" },
    { key: "workspaceName", kind: "string", optional: true },
    { key: "repository", kind: "type", optional: true, ref: "RepositoryRef" },
    { key: "model", kind: "string", optional: true },
    { key: "effort", kind: "enum", optional: true, ref: "ReasoningEffort" },
    { key: "mode", kind: "enum", optional: true, ref: "PermissionMode" },
    { key: "title", kind: "string", optional: true },
  ],
  "session.configured": [
    { key: "model", kind: "string", optional: true },
    { key: "effort", kind: "enum", optional: true, ref: "ReasoningEffort" },
    { key: "mode", kind: "enum", optional: true, ref: "PermissionMode" },
    { key: "behavior", kind: "enum", optional: true, ref: "TurnBehavior" },
    { key: "title", kind: "string", optional: true },
  ],
  "session.state": [
    { key: "state", kind: "enum", optional: false, ref: "SessionState" },
    { key: "reason", kind: "string", optional: true },
  ],
  "turn.started": [
    { key: "origin", kind: "enum", optional: false, ref: "TurnOrigin" },
  ],
  "turn.completed": [
    { key: "stopReason", kind: "enum", optional: false, ref: "StopReason" },
    { key: "durationMs", kind: "integer", optional: true },
    { key: "filesChanged", kind: "integer", optional: true },
    { key: "summary", kind: "string", optional: true },
  ],
  "turn.failed": [
    { key: "error", kind: "type", optional: false, ref: "ErrorInfo" },
  ],
  "turn.interrupted": [
    { key: "reason", kind: "string", optional: true },
  ],
  "transcript.restarted": [
    { key: "rewoundToTurnId", kind: "string", optional: true },
  ],
  "item.user_message": [
    { key: "itemId", kind: "string", optional: false },
    { key: "text", kind: "string", optional: false },
    { key: "delivery", kind: "enum", optional: false, ref: "UserDelivery" },
    { key: "commandId", kind: "string", optional: true },
  ],
  "item.assistant_text.delta": [
    { key: "itemId", kind: "string", optional: false },
    { key: "text", kind: "string", optional: false },
  ],
  "item.assistant_text": [
    { key: "itemId", kind: "string", optional: false },
    { key: "text", kind: "string", optional: false },
  ],
  "item.thinking.delta": [
    { key: "itemId", kind: "string", optional: false },
    { key: "text", kind: "string", optional: false },
  ],
  "item.thinking": [
    { key: "itemId", kind: "string", optional: false },
    { key: "summary", kind: "string", optional: false },
  ],
  "item.tool_call": [
    { key: "itemId", kind: "string", optional: false },
    { key: "toolName", kind: "string", optional: false },
    { key: "toolKind", kind: "enum", optional: false, ref: "ToolKind" },
    { key: "title", kind: "string", optional: false },
    { key: "inputSummary", kind: "string", optional: true },
    { key: "risk", kind: "enum", optional: true, ref: "Risk" },
  ],
  "item.tool_output": [
    { key: "itemId", kind: "string", optional: false },
    { key: "channel", kind: "enum", optional: false, ref: "OutputChannel" },
    { key: "text", kind: "string", optional: false },
  ],
  "item.tool_result": [
    { key: "itemId", kind: "string", optional: false },
    { key: "status", kind: "enum", optional: false, ref: "ToolResultStatus" },
    { key: "summary", kind: "string", optional: true },
    { key: "exitCode", kind: "integer", optional: true },
    { key: "durationMs", kind: "integer", optional: true },
    { key: "output", kind: "string", optional: true },
  ],
  "item.file_change": [
    { key: "itemId", kind: "string", optional: false },
    { key: "path", kind: "string", optional: false },
    { key: "change", kind: "enum", optional: false, ref: "FileChangeKind" },
    { key: "linesAdded", kind: "integer", optional: false },
    { key: "linesRemoved", kind: "integer", optional: false },
    { key: "patch", kind: "string", optional: true },
    { key: "checkpointId", kind: "string", optional: true },
    { key: "toolItemId", kind: "string", optional: true },
  ],
  "item.test_run": [
    { key: "itemId", kind: "string", optional: false },
    { key: "command", kind: "string", optional: false },
    { key: "passed", kind: "boolean", optional: false },
    { key: "testsRun", kind: "integer", optional: true },
    { key: "failures", kind: "integer", optional: true },
    { key: "durationMs", kind: "integer", optional: true },
  ],
  "item.subagent": [
    { key: "itemId", kind: "string", optional: false },
    { key: "title", kind: "string", optional: false },
    { key: "status", kind: "enum", optional: false, ref: "SubagentStatus" },
    { key: "role", kind: "string", optional: true },
    { key: "activity", kind: "string", optional: true },
    { key: "summary", kind: "string", optional: true },
    { key: "error", kind: "string", optional: true },
    { key: "toolItemId", kind: "string", optional: true },
    { key: "usage", kind: "type", optional: true, ref: "Usage" },
  ],
  "item.compaction": [
    { key: "itemId", kind: "string", optional: false },
    { key: "source", kind: "enum", optional: false, ref: "CompactionSource" },
    { key: "beforeMessages", kind: "integer", optional: true },
    { key: "afterMessages", kind: "integer", optional: true },
    { key: "requestedByUser", kind: "boolean", optional: true },
  ],
  "item.notice": [
    { key: "itemId", kind: "string", optional: false },
    { key: "source", kind: "enum", optional: false, ref: "NoticeSource" },
    { key: "text", kind: "string", optional: false },
    { key: "detail", kind: "string", optional: true },
  ],
  "approval.requested": [
    { key: "approvalId", kind: "string", optional: false },
    { key: "itemId", kind: "string", optional: true },
    { key: "action", kind: "string", optional: false },
    { key: "summary", kind: "string", optional: false },
    { key: "risk", kind: "enum", optional: false, ref: "Risk" },
    { key: "digest", kind: "string", optional: true },
    { key: "expiresAt", kind: "timestamp", optional: true },
    { key: "suggestedRule", kind: "string", optional: true },
  ],
  "approval.resolved": [
    { key: "approvalId", kind: "string", optional: false },
    { key: "decision", kind: "enum", optional: false, ref: "ApprovalDecision" },
    { key: "by", kind: "enum", optional: false, ref: "ApprovalResolver" },
    { key: "feedback", kind: "string", optional: true },
  ],
  "question.asked": [
    { key: "questionId", kind: "string", optional: false },
    { key: "prompt", kind: "string", optional: false },
    { key: "options", kind: "array", optional: true, item: { key: "", kind: "type", optional: false, ref: "QuestionOption" } },
    { key: "multiSelect", kind: "boolean", optional: true },
    { key: "expiresAt", kind: "timestamp", optional: true },
  ],
  "question.answered": [
    { key: "questionId", kind: "string", optional: false },
    { key: "answer", kind: "string", optional: true },
    { key: "selected", kind: "array", optional: true, item: { key: "", kind: "string", optional: false } },
  ],
  "plan.updated": [
    { key: "steps", kind: "array", optional: false, item: { key: "", kind: "type", optional: false, ref: "PlanStep" } },
    { key: "objective", kind: "string", optional: true },
  ],
  "plan.proposed": [
    { key: "planId", kind: "string", optional: false },
    { key: "text", kind: "string", optional: false },
  ],
  "plan.resolved": [
    { key: "planId", kind: "string", optional: false },
    { key: "decision", kind: "enum", optional: false, ref: "PlanDecision" },
  ],
  "usage.updated": [
    { key: "usage", kind: "type", optional: false, ref: "Usage" },
    { key: "model", kind: "string", optional: true },
    { key: "scope", kind: "enum", optional: false, ref: "UsageScope" },
  ],
  "session.error": [
    { key: "error", kind: "type", optional: false, ref: "ErrorInfo" },
  ],
  "run.continued": [
    { key: "reason", kind: "enum", optional: false, ref: "ContinueReason" },
    { key: "detail", kind: "string", optional: false },
    { key: "revision", kind: "integer", optional: true },
  ],
  "run.outcome": [
    { key: "endReason", kind: "enum", optional: false, ref: "RunEndReason" },
    { key: "summary", kind: "string", optional: false },
    { key: "verification", kind: "string", optional: true },
    { key: "checks", kind: "array", optional: true, item: { key: "", kind: "type", optional: false, ref: "RunCheck" } },
    { key: "notChecked", kind: "array", optional: true, item: { key: "", kind: "string", optional: false } },
    { key: "left", kind: "array", optional: true, item: { key: "", kind: "string", optional: false } },
    { key: "filesChanged", kind: "integer", optional: true },
    { key: "durationMs", kind: "integer", optional: true },
  ],
  "verify.result": [
    { key: "command", kind: "string", optional: false },
    { key: "passed", kind: "boolean", optional: false },
    { key: "exitCode", kind: "integer", optional: false },
    { key: "revision", kind: "integer", optional: false },
    { key: "check", kind: "string", optional: true },
    { key: "kind", kind: "enum", optional: true, ref: "CheckKind" },
    { key: "durationMs", kind: "integer", optional: true },
    { key: "excerpt", kind: "string", optional: true },
  ],
  "verify.ui": [
    { key: "surface", kind: "enum", optional: false, ref: "VerifySurface" },
    { key: "target", kind: "string", optional: false },
    { key: "passed", kind: "boolean", optional: false },
    { key: "revision", kind: "integer", optional: false },
    { key: "viewport", kind: "string", optional: true },
    { key: "checks", kind: "array", optional: true, item: { key: "", kind: "type", optional: false, ref: "UICheck" } },
    { key: "screenshotHash", kind: "string", optional: true },
  ],
  "review.findings": [
    { key: "round", kind: "integer", optional: false },
    { key: "overall", kind: "enum", optional: false, ref: "ReviewOverall" },
    { key: "findings", kind: "array", optional: true, item: { key: "", kind: "type", optional: false, ref: "ReviewFinding" } },
    { key: "summary", kind: "string", optional: true },
    { key: "revision", kind: "integer", optional: true },
  ],
  "goal.set": [
    { key: "goalId", kind: "string", optional: false },
    { key: "objective", kind: "string", optional: false },
    { key: "criteria", kind: "array", optional: true, item: { key: "", kind: "type", optional: false, ref: "GoalCriterion" } },
    { key: "constraints", kind: "array", optional: true, item: { key: "", kind: "string", optional: false } },
    { key: "budget", kind: "type", optional: true, ref: "Budget" },
    { key: "origin", kind: "enum", optional: true, ref: "GoalOrigin" },
  ],
  "goal.updated": [
    { key: "goalId", kind: "string", optional: false },
    { key: "objective", kind: "string", optional: true },
    { key: "criteria", kind: "array", optional: true, item: { key: "", kind: "type", optional: false, ref: "GoalCriterion" } },
    { key: "constraints", kind: "array", optional: true, item: { key: "", kind: "string", optional: false } },
    { key: "budget", kind: "type", optional: true, ref: "Budget" },
  ],
  "goal.verdict": [
    { key: "goalId", kind: "string", optional: false },
    { key: "verdict", kind: "enum", optional: false, ref: "GoalVerdict" },
    { key: "reason", kind: "string", optional: false },
    { key: "unmetCriteria", kind: "array", optional: true, item: { key: "", kind: "string", optional: false } },
    { key: "revision", kind: "integer", optional: true },
  ],
  "goal.status": [
    { key: "goalId", kind: "string", optional: false },
    { key: "status", kind: "enum", optional: false, ref: "GoalStatus" },
    { key: "reason", kind: "string", optional: true },
    { key: "usage", kind: "type", optional: true, ref: "BudgetUsage" },
    { key: "budget", kind: "type", optional: true, ref: "Budget" },
  ],
  "checkin.due": [
    { key: "running", kind: "array", optional: false, item: { key: "", kind: "string", optional: false } },
    { key: "waitedMs", kind: "integer", optional: true },
    { key: "idleCheckIns", kind: "integer", optional: true },
  ],
  "ci.status": [
    { key: "checks", kind: "array", optional: false, item: { key: "", kind: "type", optional: false, ref: "CICheck" } },
    { key: "prNumber", kind: "integer", optional: true },
    { key: "prUrl", kind: "string", optional: true },
  ],
  "budget.reached": [
    { key: "scope", kind: "enum", optional: false, ref: "BudgetScope" },
    { key: "limit", kind: "enum", optional: false, ref: "BudgetLimit" },
    { key: "goalId", kind: "string", optional: true },
    { key: "usage", kind: "type", optional: true, ref: "BudgetUsage" },
    { key: "budget", kind: "type", optional: true, ref: "Budget" },
  ],
  "code.pull_request": [
    { key: "branch", kind: "string", optional: false },
    { key: "prUrl", kind: "string", optional: true },
    { key: "prNumber", kind: "integer", optional: true },
    { key: "reused", kind: "boolean", optional: true },
  ],
};

const COMMAND_ENVELOPE_FIELDS: readonly FieldSpec[] = [
  { key: "v", kind: "string", optional: false },
  { key: "id", kind: "string", optional: false },
  { key: "idempotencyKey", kind: "string", optional: false },
  { key: "sessionId", kind: "string", optional: false },
  { key: "issuedAt", kind: "timestamp", optional: false },
  { key: "expiresAt", kind: "timestamp", optional: true },
];
const COMMAND_ENVELOPE_KEYS: ReadonlySet<string> = new Set(["v","id","idempotencyKey","sessionId","issuedAt","expiresAt","type"]);

const COMMAND_FIELDS: Record<string, readonly FieldSpec[]> = {
  "turn.send": [
    { key: "text", kind: "string", optional: false },
    { key: "attachmentIds", kind: "array", optional: true, item: { key: "", kind: "string", optional: false } },
  ],
  "turn.steer": [
    { key: "text", kind: "string", optional: false },
  ],
  "turn.queue": [
    { key: "text", kind: "string", optional: false },
  ],
  "turn.cancel": [
    { key: "reason", kind: "string", optional: true },
  ],
  "approval.decide": [
    { key: "approvalId", kind: "string", optional: false },
    { key: "decision", kind: "enum", optional: false, ref: "ApprovalDecision" },
    { key: "digest", kind: "string", optional: true },
    { key: "feedback", kind: "string", optional: true },
  ],
  "question.answer": [
    { key: "questionId", kind: "string", optional: false },
    { key: "answer", kind: "string", optional: true },
    { key: "selected", kind: "array", optional: true, item: { key: "", kind: "string", optional: false } },
  ],
  "plan.decide": [
    { key: "planId", kind: "string", optional: false },
    { key: "decision", kind: "enum", optional: false, ref: "PlanDecision" },
  ],
  "session.set_mode": [
    { key: "mode", kind: "enum", optional: true, ref: "PermissionMode" },
    { key: "model", kind: "string", optional: true },
    { key: "effort", kind: "enum", optional: true, ref: "ReasoningEffort" },
  ],
  "goal.set": [
    { key: "objective", kind: "string", optional: false },
    { key: "criteria", kind: "array", optional: true, item: { key: "", kind: "string", optional: false } },
    { key: "budget", kind: "type", optional: true, ref: "Budget" },
  ],
  "goal.pause": [
    { key: "goalId", kind: "string", optional: true },
  ],
  "goal.resume": [
    { key: "goalId", kind: "string", optional: true },
  ],
  "goal.edit": [
    { key: "goalId", kind: "string", optional: true },
    { key: "objective", kind: "string", optional: true },
    { key: "criteria", kind: "array", optional: true, item: { key: "", kind: "string", optional: false } },
    { key: "constraints", kind: "array", optional: true, item: { key: "", kind: "string", optional: false } },
    { key: "budget", kind: "type", optional: true, ref: "Budget" },
  ],
  "goal.clear": [
    { key: "goalId", kind: "string", optional: true },
  ],
  "run.resume": [
    { key: "note", kind: "enum", optional: false, ref: "ContinueReason" },
  ],
  "run.keep_going": [
    { key: "goalId", kind: "string", optional: true },
  ],
};

const RECEIPT_FIELDS: readonly FieldSpec[] = [
  { key: "commandId", kind: "string", optional: false },
  { key: "idempotencyKey", kind: "string", optional: false },
  { key: "disposition", kind: "enum", optional: false, ref: "CommandDisposition" },
  { key: "errorCode", kind: "string", optional: true },
  { key: "at", kind: "timestamp", optional: false },
];

// ── Runtime reader ──────────────────────────────────────────────────────────
// One tolerant reader for every surface, and a strict validator for producers
// and tests. The rules, which the Swift decoder follows exactly:
//   - not an object, a bad envelope, or a major version this build does not
//     know → not an event (null);
//   - a type this build does not know → an "unknown" event carrying the raw
//     object;
//   - a known type whose required field is missing or malformed → the same
//     "unknown" event (a buggy producer must not take a reader down);
//   - an optional field that is malformed → dropped;
//   - an enum value this build does not know → "unknown";
//   - an array element that is malformed → skipped;
//   - a key the contract does not name → dropped (a newer minor may add one).

type FieldKind = "string" | "integer" | "number" | "boolean" | "timestamp" | "json" | "enum" | "type" | "array";
interface FieldSpec {
  readonly key: string;
  readonly kind: FieldKind;
  readonly optional: boolean;
  readonly ref?: string;
  readonly item?: FieldSpec;
}
type Read = { ok: true; value: unknown } | { ok: false };

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/** The major version a "<major>.<minor>" string names, or null. */
export function agentProtocolMajor(v: unknown): number | null {
  if (typeof v !== "string") return null;
  const match = /^(\d+)\.(\d+)$/.exec(v);
  return match ? Number(match[1]) : null;
}

function readField(spec: FieldSpec, value: unknown, path: string, problems: string[] | null): Read {
  switch (spec.kind) {
    case "string":
    case "timestamp":
      if (typeof value === "string") return { ok: true, value };
      break;
    case "integer":
      if (typeof value === "number" && Number.isSafeInteger(value)) return { ok: true, value };
      break;
    case "number":
      if (typeof value === "number" && Number.isFinite(value)) return { ok: true, value };
      break;
    case "boolean":
      if (typeof value === "boolean") return { ok: true, value };
      break;
    case "json":
      if (value !== undefined) return { ok: true, value };
      break;
    case "enum": {
      if (typeof value !== "string") break;
      const values = ENUM_VALUES[spec.ref as string] ?? [];
      if (values.includes(value)) return { ok: true, value };
      problems?.push(path + ': "' + value + '" is not a ' + spec.ref);
      return { ok: true, value: "unknown" };
    }
    case "type": {
      if (!isRecord(value)) break;
      const record = readRecord(TYPE_FIELDS[spec.ref as string] ?? [], value, path, problems, new Set());
      return record ? { ok: true, value: record } : { ok: false };
    }
    case "array": {
      if (!Array.isArray(value)) break;
      const out: unknown[] = [];
      value.forEach((element, index) => {
        const read = readField(spec.item as FieldSpec, element, path + "[" + index + "]", problems);
        if (read.ok) out.push(read.value);
      });
      return { ok: true, value: out };
    }
  }
  problems?.push(path + ": expected " + (spec.ref ?? spec.kind));
  return { ok: false };
}

/**
 * The contract's fields of one object, or null when a required one is missing
 * or malformed. A null counts as absent. "extra" lists keys that may appear
 * without being fields (an envelope's); with "problems", any other key is one.
 */
function readRecord(
  fields: readonly FieldSpec[],
  raw: Record<string, unknown>,
  path: string,
  problems: string[] | null,
  extra: ReadonlySet<string> | null,
): Record<string, unknown> | null {
  const out: Record<string, unknown> = {};
  let complete = true;
  for (const spec of fields) {
    const value = raw[spec.key];
    if (value === undefined || value === null) {
      if (!spec.optional) {
        problems?.push(path + "." + spec.key + ": missing");
        complete = false;
      }
      continue;
    }
    const read = readField(spec, value, path + "." + spec.key, problems);
    if (read.ok) out[spec.key] = read.value;
    else if (!spec.optional) complete = false;
  }
  if (problems && extra) {
    for (const key of Object.keys(raw)) {
      if (!extra.has(key) && !fields.some((spec) => spec.key === key)) {
        problems.push(path + "." + key + ": not in the contract");
      }
    }
  }
  return complete ? out : null;
}

function readEnvelope(
  raw: unknown,
  fields: readonly FieldSpec[],
  problems: string[] | null,
): { envelope: Record<string, unknown>; type: string; raw: Record<string, unknown> } | null {
  if (!isRecord(raw)) {
    problems?.push("not an object");
    return null;
  }
  const envelope = readRecord(fields, raw, "envelope", problems, null);
  if (!envelope) return null;
  if (typeof raw.type !== "string") {
    problems?.push("envelope.type: missing");
    return null;
  }
  if (agentProtocolMajor(envelope.v) !== AGENT_PROTOCOL.major) {
    problems?.push("envelope.v: " + String(envelope.v) + " is not major " + AGENT_PROTOCOL.major);
    return null;
  }
  return { envelope, type: raw.type, raw };
}

/** Reads one event the way every Juno reader does. Null when it is not one. */
export function parseAgentEvent(raw: unknown): ParsedAgentEvent | null {
  return readEvent(raw, null);
}

/** Every way "raw" departs from the contract. Empty means a producer may send it. */
export function validateAgentEvent(raw: unknown): string[] {
  const problems: string[] = [];
  const event = readEvent(raw, problems);
  if (event && event.type === "unknown" && problems.length === 0) problems.push("type: not in the contract");
  return problems;
}

function readEvent(raw: unknown, problems: string[] | null): ParsedAgentEvent | null {
  const read = readEnvelope(raw, ENVELOPE_FIELDS, problems);
  if (!read) return null;
  const fields = EVENT_FIELDS[read.type];
  const body = fields ? readRecord(fields, read.raw, read.type, problems, ENVELOPE_KEYS) : null;
  if (!body) {
    if (!fields) problems?.push("type: " + read.type + " is not in the contract");
    return { ...(read.envelope as unknown as AgentEventEnvelope), type: "unknown", rawType: read.type, raw: { ...read.raw } };
  }
  return { ...read.envelope, type: read.type, ...body } as unknown as AgentEvent;
}

/** The JSON object for an event: its known keys, or the raw object it arrived as. */
export function serializeAgentEvent(event: ParsedAgentEvent): Record<string, unknown> {
  if (event.type === "unknown") return { ...(event as UnknownAgentEvent).raw };
  return { ...event } as Record<string, unknown>;
}

/** Whether a parsed event is one this build knows. */
export function isKnownAgentEvent(event: ParsedAgentEvent): event is AgentEvent {
  return event.type !== "unknown";
}

/** Reads one command. Null when it is not one. */
export function parseAgentCommand(raw: unknown): ParsedAgentCommand | null {
  return readCommand(raw, null);
}

/** Every way "raw" departs from the contract's commands. */
export function validateAgentCommand(raw: unknown): string[] {
  const problems: string[] = [];
  const command = readCommand(raw, problems);
  if (command && command.type === "unknown" && problems.length === 0) problems.push("type: not in the contract");
  return problems;
}

function readCommand(raw: unknown, problems: string[] | null): ParsedAgentCommand | null {
  const read = readEnvelope(raw, COMMAND_ENVELOPE_FIELDS, problems);
  if (!read) return null;
  const fields = COMMAND_FIELDS[read.type];
  const body = fields ? readRecord(fields, read.raw, read.type, problems, COMMAND_ENVELOPE_KEYS) : null;
  if (!body) {
    if (!fields) problems?.push("type: " + read.type + " is not in the contract");
    return { ...(read.envelope as unknown as AgentCommandEnvelope), type: "unknown", rawType: read.type, raw: { ...read.raw } };
  }
  return { ...read.envelope, type: read.type, ...body } as unknown as AgentCommand;
}

/** Reads a host's receipt for a command. Null when it is not one. */
export function parseAgentCommandReceipt(raw: unknown): AgentCommandReceipt | null {
  if (!isRecord(raw)) return null;
  return readRecord(RECEIPT_FIELDS, raw, "receipt", null, null) as AgentCommandReceipt | null;
}
