import type { MetadataRoute } from "next";
import { THEME_COLOR } from "@/components/ui/theme-color";

/**
 * The web app manifest — what "Add to Home Screen" and the install prompt
 * read. Absent until now, so an installed app launched with a white splash
 * and a stock icon while the site itself was painting warm paper.
 *
 * `start_url` is the front door rather than /chat: the manifest is also read
 * signed-out, and "/" already sends a signed-in reader on to the app.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Alevr",
    short_name: "Alevr",
    description:
      "Every frontier AI model — Claude, GPT, Gemini and a dozen more labs — in one calm workspace, metered by what answers actually cost.",
    start_url: "/",
    display: "standalone",
    background_color: THEME_COLOR.light,
    theme_color: THEME_COLOR.light,
    // Generated by scripts/brand/export-brand-assets.ts from the Continuum geometry.
    // "any" icons are the rounded tile; the maskable one is full-bleed with the
    // mark inside the 80% safe circle, so a launcher's own mask never cuts it.
    icons: [
      { src: "/brand/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/brand/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/brand/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
