/*
 * German for every `RESEARCH_COPY` phrase, keyed by the English source text.
 *
 * A gallery fixture, not the product's translations: `/dev/research` seeds the
 * phrase store from it when its locale toggle is on `de` (SPEC §11), so the
 * Research UI can be checked in a second language without calling the live
 * translation route. `tests/research-ui-phase.test.ts` keeps it complete, so
 * a new phrase cannot ship without one.
 *
 * Named so the i18n extractor does NOT harvest it: its values are German, and
 * a German string in the English catalog would be offered for translation
 * into every other language.
 */

export const RESEARCH_COPY_DE: Readonly<Record<string, string>> = {
  "Planned from your question as asked, because the planner was unavailable. Add or reword questions before you start.":
    "Aus Ihrer Frage geplant, wie sie gestellt wurde, weil der Planer nicht verfügbar war. Fügen Sie vor dem Start Fragen hinzu oder formulieren Sie sie um.",
  "A simpler plan, because the planner's full plan was unavailable. Edit the questions before you start if you like.":
    "Ein einfacherer Plan, weil der vollständige Plan nicht verfügbar war. Bearbeiten Sie die Fragen vor dem Start, wenn Sie möchten.",
  Research: "Recherche",
  "Close panel": "Bereich schließen",
  "Planning the research": "Plant die Recherche",
  "Ready to start": "Bereit zum Start",
  "Searching for": "Sucht nach",
  "Searching for sources": "Sucht nach Quellen",
  Reading: "Liest",
  "Reading sources": "Liest Quellen",
  "Reviewing what it found": "Prüft, was gefunden wurde",
  "Writing the report": "Schreibt den Bericht",
  "Checking citations": "Prüft die Belege",
  Paused: "Pausiert",
  "Report ready": "Bericht fertig",
  "Research stopped": "Recherche beendet",
  "Research couldn't finish": "Die Recherche konnte nicht abgeschlossen werden",
  source: "Quelle",
  sources: "Quellen",
  page: "Seite",
  pages: "Seiten",
  "new finding": "neuer Befund",
  "new findings": "neue Befunde",
  "claim supported": "Aussage belegt",
  "claims supported": "Aussagen belegt",
  "claim partly supported": "Aussage teilweise belegt",
  "claims partly supported": "Aussagen teilweise belegt",
  "claim not checked": "Aussage nicht geprüft",
  "claims not checked": "Aussagen nicht geprüft",
  "claim not supported": "Aussage nicht belegt",
  "claims not supported": "Aussagen nicht belegt",
  "claim contradicted": "Aussage widerlegt",
  "claims contradicted": "Aussagen widerlegt",
  researcher: "Rechercheur",
  researchers: "Rechercheure",
  round: "Runde",
  rounds: "Runden",
  "min read": "Min. Lesezeit",
  Open: "Öffnen",
  "Open report": "Bericht öffnen",
  "Open research panel": "Recherchebereich öffnen",
  "Research plan": "Rechercheplan",
  Questions: "Fragen",
  Question: "Frage",
  "Add a question": "Frage hinzufügen",
  "Remove this question": "Diese Frage entfernen",
  "Before I start (optional)": "Bevor ich beginne (optional)",
  "Your answer, if you have one": "Deine Antwort, falls du eine hast",
  Sources: "Quellen",
  "Add a source": "Quelle hinzufügen",
  "Paste a link to a page it should read": "Link zu einer Seite einfügen, die gelesen werden soll",
  Add: "Hinzufügen",
  "Remove this source": "Diese Quelle entfernen",
  "Only web addresses (http or https) can be added.": "Nur Webadressen (http oder https) können hinzugefügt werden.",
  About: "Etwa",
  "Reads up to": "Liest bis zu",
  "Notify me when it's ready": "Benachrichtige mich, wenn es fertig ist",
  "Turn on": "Einschalten",
  Cancel: "Abbrechen",
  "Update plan": "Plan aktualisieren",
  Start: "Starten",
  "Start research": "Recherche starten",
  "Updating the plan": "Aktualisiert den Plan",
  "Plan ready": "Plan fertig",
  Review: "Ansehen",
  "The research couldn't start. Try again.": "Die Recherche konnte nicht starten. Versuche es noch einmal.",
  "Where this message goes": "Wohin diese Nachricht geht",
  "Ask Alevr": "Alevr fragen",
  "Guide the research": "Recherche lenken",
  "Add guidance for the research…": "Hinweise für die Recherche hinzufügen…",
  "Added to the research": "Zur Recherche hinzugefügt",
  "The guidance couldn't be added.": "Der Hinweis konnte nicht hinzugefügt werden.",
  You: "Du",
  "Applies at the next round": "Gilt ab der nächsten Runde",
  "Applied in round": "Angewendet in Runde",
  Pause: "Pausieren",
  Resume: "Fortsetzen",
  "Finish now": "Jetzt abschließen",
  "Finishing with what it has": "Schließt mit dem Vorhandenen ab",
  "More research controls": "Weitere Recherche-Steuerung",
  "Cancel research…": "Recherche abbrechen…",
  "Cancel this research?": "Diese Recherche abbrechen?",
  "It stops now and nothing more is spent. Sources found so far stay in the panel.":
    "Sie stoppt sofort und es wird nichts mehr ausgegeben. Bisher gefundene Quellen bleiben im Bereich.",
  "Cancel research": "Recherche abbrechen",
  "Keep going": "Weitermachen",
  "That didn't go through. Try again.": "Das hat nicht geklappt. Versuche es noch einmal.",
  Progress: "Fortschritt",
  Plan: "Plan",
  Report: "Bericht",
  Details: "Details",
  Activity: "Aktivität",
  "Your guidance": "Deine Hinweise",
  "Found so far": "Bisher gefunden",
  "Nothing has happened yet": "Bisher ist nichts passiert",
  "Findings appear here as the research reads.": "Befunde erscheinen hier, während die Recherche liest.",
  "Not started": "Nicht begonnen",
  "In progress": "In Arbeit",
  Covered: "Abgedeckt",
  "Partly covered": "Teilweise abgedeckt",
  "Little evidence": "Wenig Belege",
  "Research started": "Recherche gestartet",
  "Started round": "Runde begonnen",
  "Finished round": "Runde beendet",
  "Searched for": "Gesucht nach",
  Opened: "Geöffnet",
  "Sources disagree": "Quellen widersprechen sich",
  "Applied your guidance": "Deinen Hinweis angewendet",
  Resumed: "Fortgesetzt",
  "Reached its spending limit": "Ausgabenlimit erreicht",
  "Planned another round": "Weitere Runde geplant",
  "Draft report written": "Berichtsentwurf geschrieben",
  "Checked citations": "Belege geprüft",
  Cited: "Zitiert",
  Read: "Gelesen",
  Found: "Gefunden",
  "Read, not cited": "Gelesen, nicht zitiert",
  "No sources yet": "Noch keine Quellen",
  "No sources were read": "Es wurden keine Quellen gelesen",
  Approach: "Vorgehen",
  "Sources it favours": "Bevorzugte Quellen",
  "Sources you added": "Von dir hinzugefügte Quellen",
  Constraints: "Vorgaben",
  "Estimate at the start": "Schätzung zu Beginn",
  "Sized to your plan's limit": "An das Limit deines Tarifs angepasst",
  "Sized to what's left of your monthly allowance": "An dein verbleibendes Monatskontingent angepasst",
  "Sized to your current usage window": "An dein aktuelles Nutzungsfenster angepasst",
  "Written by": "Geschrieben von",
  Team: "Team",
  "Pages read": "Gelesene Seiten",
  "Working time": "Arbeitszeit",
  Spent: "Ausgegeben",
  "Limit for this run": "Limit für diese Recherche",
  "Research report": "Recherchebericht",
  Contents: "Inhalt",
  "Jump to a section": "Zu einem Abschnitt springen",
  Researched: "Recherchiert",
  "Full screen": "Vollbild",
  "Close the report": "Bericht schließen",
  Markdown: "Markdown",
  "Download the report as Markdown": "Bericht als Markdown herunterladen",
  PDF: "PDF",
  "Print or save the report as PDF": "Bericht drucken oder als PDF sichern",
  "Downloaded the report": "Bericht heruntergeladen",
  "Couldn't download the report.": "Der Bericht konnte nicht heruntergeladen werden.",
  "Also read": "Außerdem gelesen",
  accessed: "abgerufen",
  "Stopped early": "Vorzeitig beendet",
  "It reached its spending limit": "Das Ausgabenlimit wurde erreicht",
  "You finished it early": "Du hast sie vorzeitig abgeschlossen",
  "It ran out of time": "Die Zeit ist abgelaufen",
  "There is no report for this run.": "Für diese Recherche gibt es keinen Bericht.",
  Supported: "Belegt",
  "Partly supported": "Teilweise belegt",
  "Not checked": "Nicht geprüft",
  "Not supported": "Nicht belegt",
  "Contradicted by the source": "Von der Quelle widerlegt",
  Source: "Quelle",
  "Open at passage": "An der Stelle öffnen",
  Passage: "Stelle",
  of: "von",
  "Previous passage": "Vorherige Stelle",
  "Next passage": "Nächste Stelle",
  "No passage was recorded for this citation.": "Für diesen Beleg wurde keine Stelle erfasst.",
  "What should it look into next?": "Was soll als Nächstes untersucht werden?",
  "Keep researching": "Weiter recherchieren",
  "Research report ready": "Recherchebericht fertig",
  "Research was skipped": "Recherche wurde übersprungen",
  "Research is included from the Pro plan.": "Recherche ist ab dem Pro-Tarif enthalten.",
  "Research isn't set up on this server.": "Recherche ist auf diesem Server nicht eingerichtet.",
  "This project doesn't allow Research.": "Dieses Projekt erlaubt keine Recherche.",
  "Research isn't available in private chats.": "Recherche ist in privaten Chats nicht verfügbar.",
  "Research is off (Lockdown).": "Recherche ist aus (Sperrmodus).",
  "Research isn't available in voice chats.": "Recherche ist in Sprachchats nicht verfügbar.",
  "Too many research runs are going. Wait for one to finish.":
    "Es laufen zu viele Recherchen. Warte, bis eine abgeschlossen ist.",
  "You've reached today's research limit.": "Du hast das heutige Recherchelimit erreicht.",
  "Research needs more of your usage window or monthly allowance than is left.":
    "Die Recherche braucht mehr von deinem Nutzungsfenster oder Monatskontingent, als übrig ist.",
  "Resets on": "Wird zurückgesetzt am",
  "Researched for": "Recherchiert für",
};
