import Foundation
import JunoCodeCore

/// The fixed shape of a local run directory.
///
/// The names are reserved rather than merely conventional: the harvester below
/// decides what to return to the user by looking at these paths, so a script
/// that writes its own `__juno_charts__/x.png` would have its output presented
/// as a Matplotlib figure. The double-underscore prefix is the same guard
/// CPython uses for its own scratch (`__pycache__`) and makes an accidental
/// collision essentially impossible while keeping a deliberate one visible in
/// the source the user wrote.
public enum SandboxScratchLayout {
    /// The user's script, verbatim.
    public static let scriptFileName = "main.py"
    /// Juno's launcher. It is a *separate* file, not a prologue prepended to
    /// `main.py`, and that distinction is the whole reason it exists: prepending
    /// even three lines shifts every line number in every traceback, so a
    /// `NameError` on the user's line 12 gets reported as line 15 and the user
    /// reads the wrong line of their own code.
    public static let bootstrapFileName = "__juno_bootstrap__.py"
    /// Where the launcher writes captured figures.
    public static let chartDirectoryName = "__juno_charts__"

    public enum Role: Equatable, Sendable {
        /// Juno's own scaffolding, or the interpreter's. Never returned.
        case harnessArtifact
        /// A captured Matplotlib figure.
        case chart
        /// Something the script wrote.
        case generatedFile
    }

    /// - Parameter relativePath: path relative to the run directory, with `/`
    ///   separators. Passing an absolute path is a programming error and is
    ///   classified as a generated file rather than crashing a harvest.
    public static func role(ofRelativePath relativePath: String) -> Role {
        let components = relativePath.split(separator: "/").map(String.init)
        guard let first = components.first else { return .harnessArtifact }
        if first == chartDirectoryName {
            // A directory entry itself is not a chart, only the files under it.
            return components.count > 1 ? .chart : .harnessArtifact
        }
        if components.contains("__pycache__") { return .harnessArtifact }
        if components.count == 1,
            first == scriptFileName || first == bootstrapFileName
        { return .harnessArtifact }
        return .generatedFile
    }
}

/// The Python launcher Juno runs instead of the user's script.
///
/// Pure string generation, so the exact program that will execute on a
/// developer's machine can be asserted in a test without an interpreter.
public enum PythonSandboxBootstrap {
    /// Every step here is wrapped in `try/except` and every failure is silent,
    /// which is the opposite of this codebase's usual instinct — but this file
    /// runs *inside the user's script's process*, and a bootstrap traceback
    /// interleaved with their program's output would look like their bug. A
    /// missing Matplotlib means no charts, which the result reports honestly as
    /// an empty chart list; it must not mean a failed run.
    public static func source(
        scriptFileName: String = SandboxScratchLayout.scriptFileName,
        chartDirectoryName: String = SandboxScratchLayout.chartDirectoryName
    ) -> String {
        """
        # Generated by Juno. Runs the user's script unmodified so that every
        # traceback line number matches the file they wrote.
        import atexit as _juno_atexit
        import os as _juno_os
        import runpy as _juno_runpy
        import sys as _juno_sys

        _juno_root = _juno_os.path.dirname(_juno_os.path.abspath(__file__))
        _juno_script = _juno_os.path.join(_juno_root, \(quoted(scriptFileName)))
        _juno_charts = _juno_os.path.join(_juno_root, \(quoted(chartDirectoryName)))

        try:
            import matplotlib as _juno_matplotlib
            # Force the non-interactive backend before pyplot is imported by the
            # script. Without this a plot call on a desktop machine can open a
            # window and block the process until the timeout kills it.
            _juno_matplotlib.use("Agg", force=True)
        except Exception:
            pass


        def _juno_capture_figures():
            # Registered with atexit rather than run after the script, so figures
            # are still captured when the script ends in sys.exit() or an
            # uncaught exception -- the runs where seeing the chart matters most.
            if "matplotlib" not in _juno_sys.modules:
                return
            try:
                import matplotlib.pyplot as _juno_pyplot
            except Exception:
                return
            try:
                numbers = list(_juno_pyplot.get_fignums())
            except Exception:
                return
            if not numbers:
                return
            try:
                _juno_os.makedirs(_juno_charts, exist_ok=True)
            except Exception:
                return
            for _juno_number in numbers:
                try:
                    _juno_figure = _juno_pyplot.figure(_juno_number)
                    _juno_figure.savefig(
                        _juno_os.path.join(
                            _juno_charts, "figure-%d.png" % _juno_number
                        ),
                        format="png",
                        dpi=144,
                        bbox_inches="tight",
                    )
                except Exception:
                    continue


        _juno_atexit.register(_juno_capture_figures)

        # The script sees itself as __main__ and as argv[0], exactly as it would
        # under `python main.py`. Anything less breaks the `if __name__ ==
        # "__main__":` guard that most generated analysis scripts carry.
        _juno_sys.argv = [_juno_script]
        if _juno_root not in _juno_sys.path:
            _juno_sys.path.insert(0, _juno_root)
        _juno_runpy.run_path(_juno_script, run_name="__main__")
        """
    }

    private static func quoted(_ value: String) -> String {
        "\"" + value.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"") + "\""
    }
}

/// Runs Python on this Mac, for desktop developer mode only.
///
/// This is a *fallback*, and it is weaker than the hosted sandbox in a way the
/// type cannot hide: containment here is whatever the injected
/// ``CommandExecuting`` provides. `CommandExecutionService.contained(…)` gives a
/// kernel-enforced profile; the plain initialiser gives none, and then a script
/// runs with the app's own file access. `isKernelContained` is therefore an
/// initialiser parameter that defaults to nil — the composition root knows the
/// answer, this type does not, and nil says so instead of guessing `false` (or,
/// far worse, `true`).
///
/// Reuses ``CommandExecuting`` rather than reaching for `Process` directly, so a
/// script inherits the scrubbed environment, the wall-clock timeout, the bounded
/// output budget, the process-group kill on cancellation and the secret
/// redaction that `JunoCodeLocal` already implements and tests. Duplicating any
/// of that here would have meant a second, weaker copy.
public struct LocalPythonSandboxClient: CloudCodeSandboxClient {
    public enum PreparationError: Error, Equatable, Sendable, LocalizedError {
        case unsafeInputFileName(String)

        public var errorDescription: String? {
            switch self {
            case let .unsafeInputFileName(name):
                "'\(name)' is not a valid sandbox input file name."
            }
        }
    }

    private let executor: any CommandExecuting
    private let scratchRootURL: URL
    private let pythonExecutablePath: String
    private let kernelContainment: Bool?
    private let limits: SandboxPayloadLimits

    /// - Parameters:
    ///   - scratchRootURL: where run directories are created. It must be
    ///     writable *by the executor*, which is not the same as writable by this
    ///     process: a contained `CommandExecutionService` confines writes to the
    ///     workspace, so passing the system temporary directory alongside a
    ///     contained executor produces a script that cannot save anything. The
    ///     parameter has no default for exactly that reason — the caller who
    ///     chose the executor is the only one who can choose this correctly.
    ///   - isKernelContained: whatever the caller knows about the executor.
    ///     `CommandExecutionService` answers this with `isContained`.
    public init(
        executor: any CommandExecuting,
        scratchRootURL: URL,
        pythonExecutablePath: String = "/usr/bin/python3",
        isKernelContained: Bool? = nil,
        limits: SandboxPayloadLimits = .default
    ) {
        self.executor = executor
        self.scratchRootURL = scratchRootURL
        self.pythonExecutablePath = pythonExecutablePath
        kernelContainment = isKernelContained
        self.limits = limits
    }

    /// `FileManager` is not `Sendable`, and a stored instance would make this
    /// client non-`Sendable` for no benefit. A fresh instance per call is the
    /// documented way to use it off the main thread, and every call below is a
    /// single-shot operation with no state to carry between them.
    private var fileManager: FileManager { FileManager() }

    public var backend: SandboxBackendDescription {
        SandboxBackendDescription(
            identifier: "local-developer-mode",
            isRemote: false,
            isKernelContained: kernelContainment,
            capturesCharts: true,
            returnsGeneratedFiles: true
        )
    }

    public func run(_ request: SandboxScriptRequest) async throws -> SandboxExecutionResult {
        let runDirectory = try prepareRunDirectory(for: request)
        // The run directory is not deleted on failure. A developer debugging a
        // script that produced nothing needs to look at what actually landed on
        // disk, and a cleanup here would remove the only evidence. Callers own
        // the lifetime of `scratchRootURL`.
        let (result, stdout, stderr) = try await executor.run(
            commandLine(runDirectory: runDirectory),
            timeoutSeconds: request.timeoutSeconds,
            outputLimit: .commandOutput
        )
        let harvest = harvestOutputs(in: runDirectory)
        return SandboxExecutionResult(
            stdout: stdout,
            stderr: stderr,
            exitCode: result.exitCode,
            timedOut: result.wasTimeout,
            durationSeconds: result.durationSeconds,
            // Nil, not false, when the shared budget was hit: see
            // `SandboxExecutionResult.outputWasTruncated`.
            stdoutWasTruncated: result.wasTruncated ? nil : false,
            stderrWasTruncated: result.wasTruncated ? nil : false,
            outputWasTruncated: result.wasTruncated,
            charts: harvest.charts,
            files: harvest.files,
            omittedFiles: harvest.omitted
        )
    }

    // MARK: - Preparation

    private func prepareRunDirectory(for request: SandboxScriptRequest) throws -> URL {
        let runDirectory = scratchRootURL
            .appendingPathComponent("juno-python-\(UUID().uuidString)", isDirectory: true)
        do {
            try fileManager.createDirectory(
                at: runDirectory,
                withIntermediateDirectories: true,
                // 0o700: the run directory can hold a customer CSV pulled from
                // the workspace, and on a shared Mac the default umask would
                // leave it world-readable.
                attributes: [.posixPermissions: 0o700]
            )
            try Data(request.source.utf8).write(
                to: runDirectory.appendingPathComponent(SandboxScratchLayout.scriptFileName)
            )
            try Data(PythonSandboxBootstrap.source().utf8).write(
                to: runDirectory.appendingPathComponent(SandboxScratchLayout.bootstrapFileName)
            )
        } catch {
            throw SandboxClientError.scratchDirectoryUnavailable(
                message: error.localizedDescription
            )
        }

        for file in request.inputFiles {
            // A name is one path component, always. `../../.ssh/id_rsa` as an
            // "input file" would otherwise write outside the run directory using
            // this process's own privileges, before any containment applies.
            guard Self.isSafeFileName(file.name) else {
                throw PreparationError.unsafeInputFileName(file.name)
            }
            do {
                try file.contents.write(to: runDirectory.appendingPathComponent(file.name))
            } catch {
                throw SandboxClientError.scratchDirectoryUnavailable(
                    message: error.localizedDescription
                )
            }
        }
        return runDirectory
    }

    static func isSafeFileName(_ name: String) -> Bool {
        guard !name.isEmpty, name.utf8.count <= 255,
            name != ".", name != "..",
            !name.contains("/"), !name.contains("\0"),
            !name.hasPrefix(".")
        else { return false }
        return true
    }

    /// `MPLBACKEND=Agg` duplicates what the bootstrap already does. It is here
    /// because the environment variable is read by Matplotlib at import time
    /// even when `matplotlib.use` never runs — for instance when the bootstrap's
    /// import of Matplotlib fails but the script's own import later succeeds
    /// against a repaired path.
    func commandLine(runDirectory: URL) -> String {
        let directory = Self.singleQuoted(runDirectory.path)
        let interpreter = Self.singleQuoted(pythonExecutablePath)
        let bootstrap = Self.singleQuoted(SandboxScratchLayout.bootstrapFileName)
        return "cd \(directory) && MPLBACKEND=Agg \(interpreter) \(bootstrap)"
    }

    /// POSIX single-quote escaping: everything inside `'…'` is literal, and the
    /// only sequence that can end the quote is `'` itself, which is replaced by
    /// `'\''`. A path containing `$(…)` or a space therefore cannot become a
    /// second command.
    static func singleQuoted(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    // MARK: - Harvest

    private struct Harvest {
        var charts: [SandboxChart] = []
        var files: [SandboxGeneratedFile] = []
        var omitted: [SandboxOmittedFile] = []
    }

    private func harvestOutputs(in runDirectory: URL) -> Harvest {
        var harvest = Harvest()
        let root = runDirectory.standardizedFileURL.path
        guard let enumerator = fileManager.enumerator(
            at: runDirectory,
            includingPropertiesForKeys: [.isRegularFileKey, .fileSizeKey],
            options: [.skipsHiddenFiles]
        ) else { return harvest }

        var paths: [(relative: String, url: URL)] = []
        for case let url as URL in enumerator {
            let standardized = url.standardizedFileURL.path
            guard standardized.hasPrefix(root + "/"),
                (try? url.resourceValues(forKeys: [.isRegularFileKey]))?.isRegularFile == true
            else { continue }
            paths.append((String(standardized.dropFirst(root.count + 1)), url))
        }
        // Enumeration order is filesystem order, which is neither stable nor
        // meaningful. Sorting makes two runs of the same script produce the same
        // chart order, so a UI does not reshuffle figures between runs.
        paths.sort { $0.relative < $1.relative }

        for entry in paths {
            switch SandboxScratchLayout.role(ofRelativePath: entry.relative) {
            case .harnessArtifact:
                continue
            case .chart:
                guard harvest.charts.count < limits.maximumChartCount else {
                    harvest.omitted.append(
                        SandboxOmittedFile(
                            name: entry.relative,
                            reason: .exceededFileCountLimit(limit: limits.maximumChartCount)
                        )
                    )
                    continue
                }
                appendChart(entry, to: &harvest)
            case .generatedFile:
                guard harvest.files.count < limits.maximumFileCount else {
                    harvest.omitted.append(
                        SandboxOmittedFile(
                            name: entry.relative,
                            reason: .exceededFileCountLimit(limit: limits.maximumFileCount)
                        )
                    )
                    continue
                }
                appendFile(entry, to: &harvest)
            }
        }
        return harvest
    }

    private func appendChart(_ entry: (relative: String, url: URL), to harvest: inout Harvest) {
        guard let data = readBounded(entry, into: &harvest) else { return }
        let name = (entry.relative as NSString).lastPathComponent
        guard let format = SandboxChartSniffer.format(of: data)
            ?? SandboxChartSniffer.format(ofFileNamed: name)
        else {
            // Something non-image landed in the chart directory. Returning it as
            // a file is honest; calling it a chart in an invented format is not.
            harvest.files.append(
                SandboxGeneratedFile(
                    name: entry.relative,
                    mimeType: SandboxMediaType.forFileName(name),
                    contents: data
                )
            )
            return
        }
        harvest.charts.append(
            SandboxChart(
                name: name,
                format: format,
                imageData: data,
                figureNumber: SandboxChartSniffer.figureNumber(inFileNamed: name)
            )
        )
    }

    private func appendFile(_ entry: (relative: String, url: URL), to harvest: inout Harvest) {
        guard let data = readBounded(entry, into: &harvest) else { return }
        harvest.files.append(
            SandboxGeneratedFile(
                name: entry.relative,
                mimeType: SandboxMediaType.forFileName(entry.relative),
                contents: data
            )
        )
    }

    /// Checks the size before reading. Reading a 4 GB parquet file into memory
    /// only to discard it would take the app down before the limit could apply.
    private func readBounded(
        _ entry: (relative: String, url: URL),
        into harvest: inout Harvest
    ) -> Data? {
        let size = (try? entry.url.resourceValues(forKeys: [.fileSizeKey]))?.fileSize
        if let size, size > limits.maximumFileBytes {
            harvest.omitted.append(
                SandboxOmittedFile(
                    name: entry.relative,
                    reason: .exceededFileSizeLimit(
                        byteCount: size,
                        limitBytes: limits.maximumFileBytes
                    )
                )
            )
            return nil
        }
        guard let data = try? Data(contentsOf: entry.url, options: [.mappedIfSafe]) else {
            harvest.omitted.append(
                SandboxOmittedFile(name: entry.relative, reason: .unreadable)
            )
            return nil
        }
        guard data.count <= limits.maximumFileBytes else {
            harvest.omitted.append(
                SandboxOmittedFile(
                    name: entry.relative,
                    reason: .exceededFileSizeLimit(
                        byteCount: data.count,
                        limitBytes: limits.maximumFileBytes
                    )
                )
            )
            return nil
        }
        // Detach from the memory map: the run directory outlives this call only
        // by convention, and a mapped Data whose file is deleted faults later.
        return Data(data)
    }
}
