/*
 * German for every `PANEL_COPY` phrase, keyed by the English source text.
 *
 * A gallery fixture, not the product's translations: `/dev/run` seeds the
 * phrase store from it when its locale toggle is on `de` (SPEC §11), so the
 * panel can be checked in a second language without calling the live
 * translation route. `tests/panel-state.test.ts` keeps it complete, so a new
 * phrase cannot ship without one.
 *
 * Named so the i18n extractor does NOT harvest it: its values are German, and
 * a German string in the English catalog would be offered for translation
 * into every other language.
 */

export const PANEL_COPY_DE: Readonly<Record<string, string>> = {
  "Close panel": "Bereich schließen",
  "Back to chat": "Zurück zum Chat",
  "More actions": "Weitere Aktionen",
  "Resize panel": "Bereichsgröße ändern",
  "Drag to resize. Arrow keys adjust, Home resets.":
    "Zum Ändern der Größe ziehen. Pfeiltasten passen an, Pos1 setzt zurück.",
  Activity: "Aktivität",
  Timeline: "Verlauf",
  Sources: "Quellen",
  Details: "Details",
  Thinking: "Denkt nach",
  "Searching…": "Sucht …",
  "Reading…": "Liest …",
  "Using a tool": "Nutzt ein Werkzeug",
  "Waiting for your approval": "Wartet auf deine Freigabe",
  Writing: "Schreibt",
  "Thought for": "Nachgedacht für",
  "Answered in": "Geantwortet in",
  "Researched for": "Recherchiert für",
  "Stopped after": "Gestoppt nach",
  "Couldn’t finish": "Konnte nicht abschließen",
  "No steps yet": "Noch keine Schritte",
  "Steps appear here as Juno works.": "Schritte erscheinen hier, während Juno arbeitet.",
  "Said while working": "Während der Arbeit gesagt",
  Arguments: "Argumente",
  Result: "Ergebnis",
  Output: "Ausgabe",
  "What went wrong": "Was schiefging",
  Approval: "Freigabe",
  "Show all": "Alles anzeigen",
  "Show less": "Weniger anzeigen",
  Shortened: "Gekürzt",
  Shown: "Angezeigt",
  "Full length": "Volle Länge",
  Pages: "Seiten",
  "Time limit": "Zeitlimit",
  "Reused from earlier in this turn": "Aus diesem Durchgang wiederverwendet",
  "Contained instructions aimed at the assistant; they were ignored":
    "Enthielt Anweisungen an den Assistenten; sie wurden ignoriert",
  "No results": "Keine Ergebnisse",
  "Ask to run again": "Erneute Ausführung anfragen",
  "Try again:": "Noch einmal versuchen:",
  "Opens in a new tab": "Öffnet in einem neuen Tab",
  "Approve this call": "Diesen Aufruf freigeben",
  "Allow once": "Einmal erlauben",
  "Always allow": "Immer erlauben",
  Decline: "Ablehnen",
  "Sending your answer": "Deine Antwort wird gesendet",
  "Allowed once": "Einmal erlaubt",
  "Always allowed": "Immer erlaubt",
  "You declined this": "Du hast das abgelehnt",
  "Approval expired": "Freigabe abgelaufen",
  "Blocked by your settings": "Durch deine Einstellungen blockiert",
  Cancelled: "Abgebrochen",
  "Couldn’t record your answer": "Deine Antwort konnte nicht gespeichert werden",
  "Couldn’t reach the server. Try again.": "Server nicht erreichbar. Versuch es noch einmal.",
  "This was already answered": "Das wurde bereits beantwortet",
  "Only Allow once is possible for this action": "Für diese Aktion ist nur „Einmal erlauben“ möglich",
  Cited: "Zitiert",
  "Also read": "Außerdem gelesen",
  Found: "Gefunden",
  "No sources": "Keine Quellen",
  "Pages the answer used appear here.": "Seiten, die die Antwort genutzt hat, erscheinen hier.",
  "Cited as": "Zitiert als",
  Model: "Modell",
  Effort: "Aufwand",
  Context: "Kontext",
  Tools: "Werkzeuge",
  Connectors: "Verbindungen",
  "Memory used": "Genutzte Erinnerungen",
  "Context used": "Genutzter Kontext",
  Window: "Fenster",
  "Tools available": "Verfügbare Werkzeuge",
  "Search built into the model": "Im Modell eingebaute Suche",
  "Up to": "Bis zu",
  Connected: "Verbunden",
  "Couldn’t connect": "Keine Verbindung möglich",
  "Chosen automatically": "Automatisch gewählt",
  "Picked by Auto": "Von Auto gewählt",
  Forget: "Vergessen",
  "Open source chat": "Ursprungschat öffnen",
  "Manage all": "Alle verwalten",
  "Forgotten. Juno won’t learn this again.": "Vergessen. Juno lernt das nicht erneut.",
  "Couldn’t forget that. Nothing was changed.": "Das konnte nicht vergessen werden. Nichts wurde geändert.",
  Undo: "Rückgängig",
  Instant: "Sofort",
  Minimal: "Minimal",
  Low: "Niedrig",
  Medium: "Mittel",
  High: "Hoch",
  "Extra high": "Sehr hoch",
  Max: "Maximal",
  token: "Token",
  tokens: "Token",
  character: "Zeichen",
  characters: "Zeichen",
  "earlier message": "frühere Nachricht",
  "earlier messages": "frühere Nachrichten",
  attachment: "Anhang",
  attachments: "Anhänge",
  "project file": "Projektdatei",
  "project files": "Projektdateien",
  step: "Schritt",
  steps: "Schritte",
  tool: "Werkzeug",
  tools: "Werkzeuge",
  "Search the web": "Im Web suchen",
  "Read web pages": "Webseiten lesen",
  "Read attached documents": "Angehängte Dokumente lesen",
  "Look closely at images": "Bilder genau ansehen",
  "Run code": "Code ausführen",
  "Search your chats": "Deine Chats durchsuchen",
  "Check the time": "Uhrzeit prüfen",
  "Do exact arithmetic": "Exakt rechnen",
  "Hand work to a task": "Arbeit an eine Aufgabe übergeben",
  "Suggest Research": "Recherche vorschlagen",
  "The model’s own web search": "Die eigene Websuche des Modells",
  "Search X": "X durchsuchen",
  "Connector tools": "Werkzeuge von Verbindungen",
  "Switched model to": "Modell gewechselt zu",
  "A skill couldn’t be applied": "Ein Skill konnte nicht angewendet werden",
  "couldn’t connect": "konnte keine Verbindung herstellen",
  "You’ve reached your usage limit": "Du hast dein Nutzungslimit erreicht",
  "The model stopped responding": "Das Modell hat nicht mehr geantwortet",
  "The answer hit its length limit": "Die Antwort hat ihre Längengrenze erreicht",
  "The provider stopped this answer": "Der Anbieter hat diese Antwort gestoppt",
  "Stopped using tools after": "Werkzeugnutzung beendet nach",
  "Reached this turn’s search limit": "Suchlimit für diesen Durchgang erreicht",
  "Web access is off in Lockdown": "Webzugriff ist im Lockdown aus",
  "Didn’t open a link that wasn’t in this conversation":
    "Einen Link, der nicht in dieser Unterhaltung vorkam, nicht geöffnet",
  "A page tried to give the assistant instructions": "Eine Seite hat versucht, dem Assistenten Anweisungen zu geben",
  "Search was limited": "Die Suche war eingeschränkt",
  "Research was skipped": "Die Recherche wurde übersprungen",
  "Connectors aren’t available in private chats": "Verbindungen sind in privaten Chats nicht verfügbar",
  "Some tools weren’t offered": "Einige Werkzeuge wurden nicht angeboten",
  "Sign in again in Settings": "Melde dich in den Einstellungen erneut an",
  "Couldn’t be reached": "Nicht erreichbar",
  "Isn’t set up correctly": "Nicht richtig eingerichtet",
  "Took too long to connect": "Verbindung hat zu lange gedauert",
  "Isn’t linked": "Nicht verknüpft",
  "Research isn’t set up on this server.": "Recherche ist auf diesem Server nicht eingerichtet.",
  "Research is available on paid plans.": "Recherche ist in kostenpflichtigen Tarifen verfügbar.",
  "This project doesn’t allow Research.": "Dieses Projekt erlaubt keine Recherche.",
  "Research isn’t available in private chats.": "Recherche ist in privaten Chats nicht verfügbar.",
  "Research is off (Lockdown).": "Recherche ist aus (Lockdown).",
  "Too many research runs are going. Wait for one to finish.":
    "Es laufen zu viele Recherchen. Warte, bis eine fertig ist.",
  "You’ve reached today’s research limit.": "Du hast das heutige Recherchelimit erreicht.",
  "Research needs more of your monthly allowance than is left.":
    "Die Recherche braucht mehr von deinem Monatskontingent, als übrig ist.",
  "Resets on": "Wird zurückgesetzt am",
};
