/**
 * Writes the web's bundled model catalogue as a Swift fixture for the Mac
 * model picker's snapshot tests, so the Mac renders exactly the models the web
 * gallery (/dev/model-picker) renders, for a side-by-side check.
 *
 *   npx tsx scripts/export-model-picker-fixture.mts > native/macOS/JunoDesktop/Tests/Snapshots/ModelPickerWebFixtures.swift
 *
 * `npm run models:sync -- --apply` runs this after every catalogue change, and
 * tests/model-picker-fixture-drift.test.ts fails when the committed fixture is
 * not what this prints. The catalogue is read AS OF `FIXTURE_DAY` (default
 * below, which the sync moves forward), so the output does not change at
 * midnight on its own: retirements are applied by the sync, not by the clock.
 */
export const DEFAULT_FIXTURE_DAY = "2026-10-10";
const FIXTURE_DAY = process.env.FIXTURE_DAY ?? DEFAULT_FIXTURE_DAY;
// Before the catalogue loads: MODEL_LIST is filtered by this day at import.
process.env.JUNO_CATALOG_TODAY = FIXTURE_DAY;
const { GEN_MODELS, MODEL_LIST } = await import("@/lib/models");
const { PROVIDERS } = await import("@/lib/providers");
const { PLANS, modelRequiredPlan, planRank } = await import("@/lib/plans");
const { defaultReasoning, getModelMetrics, reasoningOptions, sortModelsForDisplay, withSupersededMarked } = await import("@/lib/model-metrics");
const { fastModeMultiplier } = await import("@/lib/pricing");

const PLAN = "PRO" as const;
const s = (v: string) => JSON.stringify(v);
const opt = (v: string | null | undefined) => (v == null ? "nil" : s(v));

const models = sortModelsForDisplay(withSupersededMarked([...MODEL_LIST, ...GEN_MODELS], FIXTURE_DAY));
const rows = models.map((m) => {
  const metrics = getModelMetrics(m, new Date(FIXTURE_DAY));
  const options = reasoningOptions(m);
  const stopId = (v: string | null, label: string) => (v === null ? "instant" : label === "Thinking" ? "thinking" : v);
  const stops = options.length >= 2
    ? options.map((o) => `.init(id: ${s(stopId(o.value, o.label))}, label: ${s(o.label)}, accessibilityLabel: ${s(o.label)})`)
    : [];
  const def = defaultReasoning(m);
  const defaultLabel = options.find((o) => o.value === def)?.label ?? "";
  const defaultId = options.length >= 2 ? stopId(def, defaultLabel) : null;
  const fast = fastModeMultiplier(m);
  const caps = [
    m.reasoning ? ".reasoning" : null,
    m.vision ? ".vision" : null,
    m.webSearch ? ".search" : null,
    m.agenticTools && m.modality === "chat" ? ".tools" : null,
  ].filter(Boolean);
  const required = modelRequiredPlan(m);
  const reason = m.comingSoon ? "Coming soon" : planRank(PLAN) < planRank(required) ? `Requires ${PLANS[required].name}` : null;
  const price = metrics.inputUsdPerMTok + metrics.outputUsdPerMTok >= 0
    ? `JunoModelPrice(inputPerMillion: ${metrics.inputUsdPerMTok}, outputPerMillion: ${metrics.outputUsdPerMTok})`
    : "nil";
  return `        JunoModelDescriptor(
            id: ${s(m.id)},
            providerID: ${s(m.provider)},
            providerName: ${s(PROVIDERS[m.provider]?.label ?? m.provider)},
            displayName: ${s(m.name)},
            summary: ${opt(m.description)},
            modality: .${m.modality === "chat" ? "chat" : m.modality},
            isLegacy: ${m.legacy ? "true" : "false"},
            released: ${opt(m.released)},
            contextWindowTokens: ${m.modality === "chat" && metrics.contextTokens > 0 ? metrics.contextTokens : "nil"},
            speedGrade: ${metrics.speed},
            intelligenceGrade: ${metrics.intelligence},
            capabilities: [${caps.join(", ")}],
            thinking: JunoThinkingLadder(stops: [${stops.join(", ")}], modelName: ${s(m.name)}, fastModeRateMultiplier: ${fast ?? "nil"}, defaultStopID: ${opt(defaultId)}),
            unavailabilityReason: ${opt(reason)},
            deprecationNote: ${opt(m.status === "deprecated" ? m.deprecationNote ?? null : null)},
            retiresOn: ${opt(m.retiresOn)},
            price: ${price}
        )`;
});

console.log(`import JunoDesignSystem

// Generated by scripts/export-model-picker-fixture.mts from the web's bundled
// catalogue (src/lib/models.ts) for a ${PLAN} account. Do not edit by hand.
enum ModelPickerWebFixtures {
    static let auto = JunoModelDescriptor(
        id: "juno:auto",
        providerID: "juno",
        providerName: "Alevr",
        displayName: "Auto",
        summary: "Picks the model and thinking depth most likely to answer each prompt well for the least total cost.",
        choosesThinkingAutomatically: true
    )

    static let models: [JunoModelDescriptor] = [auto] + catalog

    static let catalog: [JunoModelDescriptor] = [
${rows.join(",\n")}
    ]
}`);
