/**
 * contracts/code-run/console-fixtures.json: the console documents
 * /api/code/console returns for a few code blocks, so the native snapshot and
 * preview harnesses run the web's own document without a server.
 *
 *   npx tsx scripts/generate-console-fixtures.ts          # write
 *   npx tsx scripts/generate-console-fixtures.ts --check  # fail when stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { codeBlockConsoleDoc } from "@/lib/sandbox/console-doc";

export const CONSOLE_FIXTURE_SAMPLES: { language: string; code: string }[] = [
  {
    language: "sql",
    code: "SELECT employee_id, first_name, last_name, salary\nFROM employees\nWHERE department_id = 60\nORDER BY salary DESC;",
  },
  { language: "sql", code: "SELECT last_name, salary\nFROM employees\nWHERE department_id = 60;" },
  {
    language: "python",
    code: 'import math\n\nradii = [1, 2.5, 4]\nfor r in radii:\n    print(f"r = {r}: area = {math.pi * r ** 2:.2f}")\nprint("mean radius", sum(radii) / len(radii))',
  },
  {
    language: "javascript",
    code: "const fib = (n) => (n < 2 ? n : fib(n - 1) + fib(n - 2));\nconsole.log([...Array(10).keys()].map(fib).join(', '));",
  },
];

export function consoleFixtures() {
  const docs = [];
  for (const sample of CONSOLE_FIXTURE_SAMPLES) {
    for (const theme of ["light", "dark"] as const) {
      const doc = codeBlockConsoleDoc(sample.language, sample.code, theme);
      if (!doc) throw new Error(`no console for ${sample.language}`);
      docs.push({ language: doc.language, theme, code: sample.code, html: doc.html });
    }
  }
  return {
    $comment: "Generated by scripts/generate-console-fixtures.ts from src/lib/sandbox/console-doc.ts. Do not edit.",
    docs,
  };
}

const PATH = "contracts/code-run/console-fixtures.json";

if (process.argv[1]?.endsWith("generate-console-fixtures.ts")) {
  const text = JSON.stringify(consoleFixtures(), null, 2) + "\n";
  if (process.argv.includes("--check")) {
    if (readFileSync(PATH, "utf8") !== text) {
      console.error(`${PATH} is stale: npx tsx scripts/generate-console-fixtures.ts`);
      process.exit(1);
    }
  } else {
    writeFileSync(PATH, text);
    console.log(`wrote ${PATH}`);
  }
}
