/**
 * The Swift twin of /api/v1/models' `mediaParams` for the media models the
 * native preview and snapshot harnesses serve (an app in the simulator cannot
 * reach the server): each model's generation choices exactly as
 * `nativeMediaParams` builds them from src/lib/media-params.ts, so the Mac and
 * iPhone trays drawn offline are the trays the real catalogue produces.
 *
 *   npx tsx scripts/generate-native-media-params-fixtures.ts          # write
 *   npx tsx scripts/generate-native-media-params-fixtures.ts --check  # fail when stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { nativeMediaParams } from "@/lib/media-params-ui";

/** Every kind of control at least once: segmented, menus, aspect, slider with Auto, toggles, facts. */
export const PREVIEW_MEDIA_MODELS = [
  "openai:gpt-image-2.5-sunburst",
  "openai:gpt-image-2.5-flare",
  "google:gemini-nano-banana-2.1",
  "xai:grok-imagine-image-2.0",
  "google:gemini-omni-1.1-flash",
  "google:veo-3.1-generate-preview",
  "xai:grok-imagine-video-1.5",
  "seedance:dreamina-seedance-2-5-260628",
  "google:lyria-3.5",
  "google:lyria-3-clip-preview",
];

const OUTPUT = "native/Packages/JunoNativeKit/Sources/JunoPreviewSupport/Generated/PreviewMediaParams.swift";

export function swiftSource(): string {
  const rows = PREVIEW_MEDIA_MODELS.map((id) => {
    const params = nativeMediaParams(id);
    if (!params) throw new Error(`no media params for ${id}`);
    return `        "${id}": ####"""\n${JSON.stringify(params)}\n"""####,`;
  });
  return `// Generated by scripts/generate-native-media-params-fixtures.ts from src/lib/media-params.ts. Do not edit.
#if DEBUG
/// The \`mediaParams\` /api/v1/models publishes for the harness's media models,
/// as JSON, keyed by model id.
public enum PreviewMediaParams {
    public static let json: [String: String] = [
${rows.join("\n")}
    ]
}
#endif
`;
}

const source = swiftSource();
if (process.argv.includes("--check")) {
  const current = readFileSync(OUTPUT, "utf8");
  if (current !== source) {
    console.error(`${OUTPUT} is stale: run npx tsx scripts/generate-native-media-params-fixtures.ts`);
    process.exit(1);
  }
  console.log("Native media params fixtures match src/lib/media-params.ts.");
} else {
  writeFileSync(OUTPUT, source);
  console.log(`Wrote ${OUTPUT}`);
}
