/**
 * contracts/code-run/console-fixtures.json, and its Swift twin in
 * JunoPreviewSupport (an app in the simulator cannot read the checkout): the
 * console documents /api/code/console returns for a few code blocks, so the
 * native snapshot and preview harnesses run the web's own document without a
 * server.
 *
 *   npx tsx scripts/generate-console-fixtures.ts          # write
 *   npx tsx scripts/generate-console-fixtures.ts --check  # fail when stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { codeBlockConsoleDoc } from "@/lib/sandbox/console-doc";

export const CONSOLE_FIXTURE_SAMPLES: { language: string; code: string }[] = [
  {
    language: "sql",
    code: "SELECT employee_id, first_name, last_name, salary\nFROM employees\nWHERE department_id = 60\nORDER BY salary DESC;",
  },
  { language: "sql", code: "SELECT last_name, salary\nFROM employees\nWHERE department_id = 60;" },
  {
    language: "python",
    code: 'import math\n\nradii = [1, 2.5, 4]\nfor r in radii:\n    print(f"r = {r}: area = {math.pi * r ** 2:.2f}")\nprint("mean radius", sum(radii) / len(radii))',
  },
  {
    language: "javascript",
    code: "const fib = (n) => (n < 2 ? n : fib(n - 1) + fib(n - 2));\nconsole.log([...Array(10).keys()].map(fib).join(', '));",
  },
];

export function consoleFixtures() {
  const docs = [];
  for (const sample of CONSOLE_FIXTURE_SAMPLES) {
    for (const theme of ["light", "dark"] as const) {
      const doc = codeBlockConsoleDoc(sample.language, sample.code, theme);
      if (!doc) throw new Error(`no console for ${sample.language}`);
      docs.push({ language: doc.language, theme, code: sample.code, html: doc.html });
    }
  }
  return {
    $comment: "Generated by scripts/generate-console-fixtures.ts from src/lib/sandbox/console-doc.ts. Do not edit.",
    docs,
  };
}

const PATH = "contracts/code-run/console-fixtures.json";
const SWIFT_PATH = "native/Packages/JunoNativeKit/Sources/JunoPreviewSupport/Generated/PreviewConsoleDocs.swift";

export function consoleFixturesSwift(): string {
  const docs = consoleFixtures().docs;
  for (const d of docs) if (d.html.includes('"""####') || d.code.includes('"""####')) throw new Error("delimiter clash");
  const rows = docs
    .map((d) => `        .init(language: "${d.language}", theme: "${d.theme}", code: ####"""\n${d.code}\n"""####, html: ####"""\n${d.html}\n"""####),`)
    .join("\n");
  return `// Generated by scripts/generate-console-fixtures.ts from src/lib/sandbox/console-doc.ts. Do not edit.
#if DEBUG
enum PreviewConsoleDocs {
    struct Doc {
        let language: String
        let theme: String
        let code: String
        let html: String
    }

    static let all: [Doc] = [
${rows}
    ]
}
#endif
`;
}

if (process.argv[1]?.endsWith("generate-console-fixtures.ts")) {
  const outputs: [string, string][] = [
    [PATH, JSON.stringify(consoleFixtures(), null, 2) + "\n"],
    [SWIFT_PATH, consoleFixturesSwift()],
  ];
  for (const [path, text] of outputs) {
    if (process.argv.includes("--check")) {
      if (readFileSync(path, "utf8") !== text) {
        console.error(`${path} is stale: npx tsx scripts/generate-console-fixtures.ts`);
        process.exitCode = 1;
      }
    } else {
      writeFileSync(path, text);
      console.log(`wrote ${path}`);
    }
  }
}
