/** Product maturity projection, distinct from per-turn model/tool negotiation. */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { createHash } from "node:crypto";
import {
  CANONICAL_CAPABILITY_REGISTRY,
  CAPABILITY_MATURITY_STATES,
  CAPABILITY_SURFACES,
  isCapabilityProductionAccepted,
} from "../src/lib/capabilities";

const entries = Object.values(CANONICAL_CAPABILITY_REGISTRY);
for (const entry of entries) {
  for (const surface of CAPABILITY_SURFACES) {
    for (const evidence of entry.maturity[surface].evidence) {
      if (!existsSync(resolve(evidence))) throw new Error(`${entry.id}/${surface}: missing evidence ${evidence}`);
    }
  }
  if (entry.production.accepted && !entry.platforms.every((platform) => isCapabilityProductionAccepted(entry.id, platform))) {
    throw new Error(`${entry.id}: production acceptance contradicts surface evidence or blockers`);
  }
}
const json = JSON.stringify({ version: 1, capabilities: CANONICAL_CAPABILITY_REGISTRY }, null, 2) + "\n";
if (process.argv.includes("--json")) {
  process.stdout.write(json);
} else {
  const output = resolve("native/Packages/JunoNativeKit/Sources/JunoCore/Generated/JunoProductCapabilityRegistry.swift");
  const quote = (value: string) => JSON.stringify(value);
  const swiftState = (value: string) => value.replace(/_([a-z])/g, (_, char: string) => char.toUpperCase());
  const swift = `// Generated by scripts/generate-capability-maturity.ts. Do not edit.
// Source of truth: src/lib/capabilities.ts. Source evidence does not imply release acceptance.
import Foundation

public enum JunoProductMaturity: String, Codable, CaseIterable, Sendable {
${CAPABILITY_MATURITY_STATES.map((state) => `    case ${swiftState(state)} = ${quote(state)}`).join("\n")}
}

public struct JunoProductCapability: Sendable {
    public let id: String
    public let maturity: [String: JunoProductMaturity]
    public let supportedPlatforms: [String]
    public let productionAccepted: Bool
}

public enum JunoProductCapabilityRegistry {
    public static let version = 1
    public static let digest = ${quote(createHash("sha256").update(json).digest("hex"))}
    public static let entries: [JunoProductCapability] = [
${entries.map((entry) => `        JunoProductCapability(
            id: ${quote(entry.id)},
            maturity: [${CAPABILITY_SURFACES.map((surface) => `${quote(surface)}: .${swiftState(entry.maturity[surface].state)}`).join(", ")}],
            supportedPlatforms: [${entry.platforms.map(quote).join(", ")}],
            productionAccepted: ${entry.production.accepted}
        ),`).join("\n")}
    ]
}
`;
  if (process.argv.includes("--check")) {
    if (!existsSync(output) || readFileSync(output, "utf8") !== swift) {
      throw new Error("Product capability maturity projection is stale. Run: npx tsx scripts/generate-capability-maturity.ts");
    }
    console.log(`Product capability maturity projection matches ${entries.length} canonical capabilities.`);
  } else {
    writeFileSync(output, swift);
    console.log(`Wrote ${output}`);
  }
}
