import { NextResponse } from "next/server";
import { createHash, randomUUID } from "node:crypto";
import JSZip from "jszip";
import { Prisma, Role } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/session";
import { rateLimit } from "@/lib/rate-limit";
import { encryptMessageText } from "@/lib/message-crypto";
import { getSuppressions } from "@/lib/memory";
import { guardedMemoryWrite } from "@/lib/memory-suppression";
import { getUserPlan } from "@/lib/usage";
import { PLANS } from "@/lib/plans";
import { buildImportObjectKey, deleteObject, putObject } from "@/lib/storage";
import { isStorageAvailable } from "@/lib/env";
import { planAttachmentUpload } from "@/lib/attachment-upload";
import { assertLibraryCapacity, libraryCapacity, lockedLibraryCapacity, LibraryQuotaExceededError } from "@/lib/library";
import { scheduleIngest } from "@/lib/knowledge";
import { cleanupImportRun, IMPORT_RUN_LEASE_MS } from "@/lib/import-recovery";
import {
  detectFormat,
  findConversationsEntry,
  importArchiveBudgetProblems,
  parseHistoryExport,
  HistoryImportError,
} from "@/lib/history-import";

export const runtime = "nodejs";
// Vercel-only directive (`next start` ignores it) — a big export can take a while.
export const maxDuration = 300;

const MAX_BYTES = 100 * 1024 * 1024;

type PlannedAttachment = Extract<ReturnType<typeof planAttachmentUpload>, { ok: true }>["plan"];

type AttachmentSnapshotRow = {
  version: number;
  origin: string;
  kind: "IMAGE" | "FILE";
  fileName: string;
  mimeType: string;
  size: number;
  storageKey: string;
  extractedText: string | null;
  parserState: string;
  parserVersion: string | null;
};

type PreparedImportAttachment = {
  raw: Record<string, unknown>;
  bytes: Uint8Array;
  plan: PlannedAttachment;
  currentKey: string;
  snapshotRows: AttachmentSnapshotRow[];
  objectIds: string[];
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function stringValue(value: unknown, max = 500): string | null {
  return typeof value === "string" && value.length > 0 && value.length <= max ? value : null;
}

function dateValue(value: unknown): Date | null {
  if (typeof value !== "string" && typeof value !== "number") return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

function positiveInt(value: unknown, fallback: number): number {
  return typeof value === "number" && Number.isInteger(value) && value > 0 && value <= 100_000 ? value : fallback;
}

function nullableInt(value: unknown): number | null {
  return typeof value === "number" && Number.isInteger(value) && value >= 0 && value <= 2_000_000_000 ? value : null;
}

function nullableFloat(value: unknown): number | null {
  return typeof value === "number" && Number.isFinite(value) && value >= 0 && value <= 1 ? value : null;
}

function jsonInput(value: unknown): Prisma.InputJsonValue | typeof Prisma.DbNull | undefined {
  if (value === null || value === undefined) return Prisma.DbNull;
  if (typeof value !== "object") return undefined;
  return value as Prisma.InputJsonValue;
}

function enumValue<T extends string>(value: unknown, allowed: readonly T[]): T | null {
  return typeof value === "string" && allowed.includes(value as T) ? (value as T) : null;
}

/** Archive paths are generated by Juno, but imports are untrusted input. */
function safeArchivePath(value: unknown): string | null {
  const path = stringValue(value, 400);
  if (!path || path.startsWith("/") || path.includes("\\")) return null;
  const parts = path.split("/");
  if (parts.some((part) => !part || part === "." || part === "..")) return null;
  return path;
}

/**
 * POST /api/import — upload a ChatGPT, Claude, Gemini, or Juno export ZIP/JSON and recreate its
 * conversations for the current user. Titles and timestamps are preserved,
 * message bodies go through the same encryption-at-rest path as live chats,
 * and a conversation whose title + createdAt already exist for this user is
 * skipped so re-uploading the same archive doesn't duplicate anything.
 */
export async function POST(req: Request) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const limit = await rateLimit({ key: `import:${user.id}`, limit: 10, windowSec: 3600 });
  if (!limit.success) return NextResponse.json({ error: "Too many imports — try again later." }, { status: 429 });

  const form = await req.formData().catch(() => null);
  const file = form?.get("file");
  if (!(file instanceof File)) return NextResponse.json({ error: "No file provided." }, { status: 400 });
  if (file.size > MAX_BYTES) return NextResponse.json({ error: "Export must be under 100 MB." }, { status: 400 });

  let parsed;
  let sourceZip: JSZip | null = null;
  let junoPayload: Record<string, unknown> | null = null;
  let archiveSha256 = "";
  try {
    const bytes = await file.arrayBuffer();
    archiveSha256 = createHash("sha256").update(Buffer.from(bytes)).digest("hex");
    const isJson = file.type === "application/json" || file.name.toLowerCase().endsWith(".json");
    if (isJson) {
      const raw = new TextDecoder().decode(bytes);
      parsed = parseHistoryExport(raw, "juno");
      const decoded = JSON.parse(raw) as unknown;
      if (isRecord(decoded) && parsed.format === "juno") junoPayload = decoded;
    } else {
      const zip = await JSZip.loadAsync(bytes).catch(() => null);
      if (!zip) throw new HistoryImportError("That file isn't a readable ZIP — upload a ChatGPT, Claude, Gemini, or Juno export.");
      const budgetProblems = importArchiveBudgetProblems(
        Object.values(zip.files).map((entry) => {
          const data = (entry as unknown as { _data?: { uncompressedSize?: number; compressedSize?: number } })._data;
          return {
            name: entry.name,
            dir: entry.dir,
            unsafeOriginalName: entry.unsafeOriginalName,
            uncompressedSize: data?.uncompressedSize,
            compressedSize: data?.compressedSize,
          };
        }),
      );
      if (budgetProblems.length > 0) throw new HistoryImportError(budgetProblems.join(" "));
      sourceZip = zip;
      const entries = Object.keys(zip.files);
      const entryPath = findConversationsEntry(entries);
      const zipEntry = entryPath ? zip.file(entryPath) : null;
      if (!zipEntry) throw new HistoryImportError("Couldn't find a supported conversation JSON file in this export.");
      const raw = await zipEntry.async("string");
      parsed = parseHistoryExport(raw, detectFormat(entries));
      const decoded = JSON.parse(raw) as unknown;
      if (isRecord(decoded) && parsed.format === "juno") junoPayload = decoded;
    }
  } catch (err) {
    if (err instanceof HistoryImportError) return NextResponse.json({ error: err.message }, { status: 400 });
    throw err;
  }

  if (junoPayload?.messagesTruncated === true) {
    return NextResponse.json(
      { error: "This Juno export is incomplete because its message cap was reached. Export the full account again before importing." },
      { status: 422 },
    );
  }

  // Claim the archive digest before any account mutation. A completed digest is
  // a durable idempotent replay; an active digest is a concurrent retry; and an
  // expired/failed run can be reclaimed after its staged objects are cleaned.
  const now = new Date();
  const leaseExpiresAt = new Date(now.getTime() + IMPORT_RUN_LEASE_MS);
  const attemptLeaseToken = randomUUID();
  let importRun = await prisma.importRun.findUnique({
    where: { userId_archiveSha256: { userId: user.id, archiveSha256 } },
  });
  if (importRun?.status === "completed") {
    return NextResponse.json(importRun.result ?? { imported: 0, skipped: 0, format: parsed.format, projectsImported: 0, memoriesImported: 0, attachmentsImported: 0, attachmentsSkipped: 0 });
  }
  if (importRun?.leaseExpiresAt && importRun.leaseExpiresAt > now) {
    return NextResponse.json({ error: "An identical import is already in progress.", importRunId: importRun.id }, { status: 409 });
  }
  if (importRun) {
    const previousLeaseToken = importRun.leaseToken;
    const claimed = await prisma.importRun.updateMany({
      where: {
        id: importRun.id,
        userId: user.id,
        status: { in: ["applying", "failed"] },
        leaseToken: previousLeaseToken,
        OR: [{ leaseExpiresAt: null }, { leaseExpiresAt: { lt: now } }],
      },
      data: { status: "applying", result: Prisma.DbNull, error: null, completedAt: null, leaseExpiresAt, leaseToken: attemptLeaseToken },
    });
    if (claimed.count !== 1) {
      return NextResponse.json({ error: "An identical import is already in progress.", importRunId: importRun.id }, { status: 409 });
    }
    importRun = await prisma.importRun.findFirstOrThrow({ where: { id: importRun.id, userId: user.id } });
    await cleanupImportRun(user.id, importRun.id, previousLeaseToken);
  } else {
    try {
      importRun = await prisma.importRun.create({
        data: { userId: user.id, archiveSha256, status: "applying", leaseExpiresAt, leaseToken: attemptLeaseToken },
      });
    } catch (error) {
      if (!(error instanceof Prisma.PrismaClientKnownRequestError) || error.code !== "P2002") throw error;
      const raced = await prisma.importRun.findUnique({ where: { userId_archiveSha256: { userId: user.id, archiveSha256 } } });
      if (raced?.status === "completed") return NextResponse.json(raced.result);
      return NextResponse.json({ error: "An identical import is already in progress.", importRunId: raced?.id }, { status: 409 });
    }
  }

  // Relational state is committed in one transaction. Object storage cannot
  // participate in that transaction, so every key is written through the
  // durable ImportObject ledger before the byte upload and is compensated by
  // the recovery worker if the process dies mid-import.
  const uploadedStorageKeys: string[] = [];
  const scheduledIngests: Parameters<typeof scheduleIngest>[0][] = [];
  const importedSuppressionsSnapshot =
    parsed.format === "juno" && junoPayload && Array.isArray(junoPayload.memories) ? await getSuppressions(user.id) : [];
  const cleanupStorageKeys = async (keys: readonly string[]) => {
    const uniqueKeys = [...new Set(keys)];
    if (uniqueKeys.length === 0) return;
    const results = await Promise.allSettled(uniqueKeys.map((key) => deleteObject(key)));
    const failed = results.filter((result): result is PromiseRejectedResult => result.status === "rejected");
    if (failed.length > 0) {
      console.error("[import] object compensation failed; orphan cleanup must be retried", {
        count: failed.length,
        messages: failed.slice(0, 3).map((result) => (result.reason instanceof Error ? result.reason.message : String(result.reason))),
      });
    }
  };

  try {
    const preparedAttachments: PreparedImportAttachment[] = [];
    let attachmentsSkipped = 0;
    const attachmentManifest =
      parsed.format === "juno" && junoPayload && isRecord(junoPayload.attachments) && Array.isArray(junoPayload.attachments.items)
        ? junoPayload.attachments.items.slice(0, 1_000)
        : [];
    const existingAttachmentByImportKey = new Map<string, string>();
    const stagedAttachmentImportKeys = new Set<string>();
    if (attachmentManifest.length > 0) {
      const existingAttachments = await prisma.attachment.findMany({
        where: { userId: user.id },
        select: { id: true, idempotencyKey: true },
      });
      for (const attachment of existingAttachments) {
        if (attachment.idempotencyKey) existingAttachmentByImportKey.set(attachment.idempotencyKey, attachment.id);
      }
    }

    const plan = await getUserPlan(user.id);
    let archiveBytesRead = 0;
    let importStorageBytes = 0;
    const archiveBytes = new Map<string, Uint8Array | null>();
    const readArchiveBytes = async (path: string): Promise<Uint8Array | null> => {
      if (archiveBytes.has(path)) return archiveBytes.get(path) ?? null;
      if (!sourceZip || archiveBytesRead >= MAX_BYTES) {
        archiveBytes.set(path, null);
        return null;
      }
      const entry = sourceZip.file(path);
      if (!entry || entry.dir) {
        archiveBytes.set(path, null);
        return null;
      }
      const metadata = (entry as unknown as { _data?: { uncompressedSize?: number } })._data;
      const declaredSize = Number(metadata?.uncompressedSize ?? 0);
      if (declaredSize > MAX_BYTES - archiveBytesRead) {
        archiveBytes.set(path, null);
        return null;
      }
      try {
        const bytes = new Uint8Array(await entry.async("uint8array"));
        if (bytes.byteLength > MAX_BYTES - archiveBytesRead) {
          archiveBytes.set(path, null);
          return null;
        }
        archiveBytesRead += bytes.byteLength;
        archiveBytes.set(path, bytes);
        return bytes;
      } catch {
        archiveBytes.set(path, null);
        return null;
      }
    };

    const stageObject = async (input: {
      bytes: Uint8Array;
      fileName: string;
      contentType: string;
      contentDisposition?: string;
    }) => {
      const storageKey = buildImportObjectKey(user.id, importRun.id, input.fileName);
      const ledger = await prisma.$transaction(
        async (tx) => {
          const renewed = await tx.importRun.updateMany({
            where: {
              id: importRun.id,
              userId: user.id,
              status: "applying",
              leaseToken: importRun.leaseToken,
              leaseExpiresAt: { gt: new Date() },
            },
            data: { leaseExpiresAt: new Date(Date.now() + IMPORT_RUN_LEASE_MS) },
          });
          if (renewed.count !== 1) throw new Error("Import lease was reclaimed before an attachment could be staged.");
          return tx.importObject.create({
            data: {
              userId: user.id,
              importRunId: importRun.id,
              leaseToken: importRun.leaseToken,
              storageKey,
              size: input.bytes.byteLength,
              status: "staged",
            },
            select: { id: true },
          });
        },
        { maxWait: 15_000, timeout: 30_000, isolationLevel: Prisma.TransactionIsolationLevel.Serializable },
      );
      // Register before the remote write: a storage provider can acknowledge a
      // write and then lose the response, so registering after putObject leaves
      // a crash window with no durable cleanup key.
      uploadedStorageKeys.push(storageKey);
      try {
        await putObject(storageKey, input.bytes, input.contentType, input.contentDisposition);
        const uploaded = await prisma.importObject.updateMany({
          where: { id: ledger.id, userId: user.id, importRunId: importRun.id, leaseToken: importRun.leaseToken, status: "staged" },
          data: { status: "uploaded" },
        });
        if (uploaded.count !== 1) throw new Error("Import lease was reclaimed while an attachment was uploading.");
        const renewed = await prisma.importRun.updateMany({
          where: { id: importRun.id, userId: user.id, status: "applying", leaseToken: importRun.leaseToken, leaseExpiresAt: { gt: new Date() } },
          data: { leaseExpiresAt: new Date(Date.now() + IMPORT_RUN_LEASE_MS) },
        });
        if (renewed.count !== 1) throw new Error("Import lease was reclaimed after an attachment upload.");
        return { id: ledger.id, storageKey };
      } catch (error) {
        await prisma.importObject
          .updateMany({ where: { id: ledger.id, userId: user.id, leaseToken: importRun.leaseToken, status: { in: ["staged", "uploaded"] } }, data: { status: "delete_pending" } })
          .catch(() => undefined);
        throw error;
      }
    };

    for (const rawValue of attachmentManifest) {
      if (!isRecord(rawValue) || !sourceZip || !isStorageAvailable()) {
        attachmentsSkipped += 1;
        continue;
      }
      const sourceAttachmentId = stringValue(rawValue.idempotencyKey, 200) ?? stringValue(rawValue.id, 200);
      const importKey = sourceAttachmentId
        ? sourceAttachmentId.startsWith("juno:") ? sourceAttachmentId : `juno:${sourceAttachmentId}`
        : null;
      if (importKey && (existingAttachmentByImportKey.has(importKey) || stagedAttachmentImportKeys.has(importKey))) {
        attachmentsSkipped += 1;
        continue;
      }
      const archivePath = safeArchivePath(rawValue.archivePath);
      if (!archivePath || !archivePath.startsWith("attachments/")) {
        attachmentsSkipped += 1;
        continue;
      }
      const bytes = await readArchiveBytes(archivePath);
      if (!bytes) {
        attachmentsSkipped += 1;
        continue;
      }
      const planned = planAttachmentUpload({
        declaredMime: stringValue(rawValue.mimeType, 200) ?? "application/octet-stream",
        fileName: stringValue(rawValue.fileName, 500) ?? "imported-file",
        size: bytes.length,
        bytes,
        maxUploadMb: PLANS[plan].maxUploadMb,
      });
      if (!planned.ok) {
        attachmentsSkipped += 1;
        continue;
      }
      const capacity = await libraryCapacity(user.id, plan, bytes.length + importStorageBytes);
      if (!capacity.allowed) {
        attachmentsSkipped += 1;
        continue;
      }

      const current = await stageObject({
        bytes,
        fileName: planned.plan.fileName,
        contentType: planned.plan.storedContentType,
        contentDisposition: planned.plan.contentDisposition,
      });
      importStorageBytes += bytes.length;
      const objectIds = [current.id];
      const currentVersion = positiveInt(rawValue.version, 1);
      const snapshotRows: AttachmentSnapshotRow[] = [{
        version: currentVersion,
        origin: "import",
        kind: planned.plan.kind,
        fileName: planned.plan.fileName,
        mimeType: planned.plan.storedMime,
        size: bytes.length,
        storageKey: current.storageKey,
        extractedText: planned.plan.extractedText,
        parserState: planned.plan.kind === "FILE" ? "queued" : "skipped",
        parserVersion: null,
      }];

      const priorVersions = Array.isArray(rawValue.versions) ? rawValue.versions.slice(0, 100) : [];
      for (const rawVersion of priorVersions) {
        if (!isRecord(rawVersion)) continue;
        const version = positiveInt(rawVersion.version, 0);
        const path = safeArchivePath(rawVersion.archivePath);
        if (!version || version === currentVersion || !path || !path.startsWith("attachments/")) continue;
        const versionBytes = await readArchiveBytes(path);
        if (!versionBytes) continue;
        const versionPlan = planAttachmentUpload({
          declaredMime: stringValue(rawVersion.mimeType, 200) ?? "application/octet-stream",
          fileName: stringValue(rawVersion.fileName, 500) ?? planned.plan.fileName,
          size: versionBytes.length,
          bytes: versionBytes,
          maxUploadMb: PLANS[plan].maxUploadMb,
        });
        if (!versionPlan.ok) continue;
        const versionCapacity = await libraryCapacity(user.id, plan, versionBytes.length + importStorageBytes);
        if (!versionCapacity.allowed) continue;
        const versionObject = await stageObject({
          bytes: versionBytes,
          fileName: versionPlan.plan.fileName,
          contentType: versionPlan.plan.storedContentType,
          contentDisposition: versionPlan.plan.contentDisposition,
        });
        importStorageBytes += versionBytes.length;
        objectIds.push(versionObject.id);
        snapshotRows.push({
          version,
          origin: "import",
          kind: versionPlan.plan.kind,
          fileName: versionPlan.plan.fileName,
          mimeType: versionPlan.plan.storedMime,
          size: versionBytes.length,
          storageKey: versionObject.storageKey,
          extractedText: versionPlan.plan.extractedText,
          parserState: versionPlan.plan.kind === "FILE" ? "ready" : "skipped",
          parserVersion: null,
        });
      }
      if (importKey) stagedAttachmentImportKeys.add(importKey);
      preparedAttachments.push({ raw: rawValue, bytes, plan: planned.plan, currentKey: current.storageKey, snapshotRows, objectIds });
    }

    const result = await prisma.$transaction(
      async (tx) => {
        // The pre-staging checks keep the happy path cheap, but only this
        // account-locked re-check can make a multi-object restore quota-safe
        // against concurrent uploads or generated media.
        const lockedCapacity = await lockedLibraryCapacity(tx, user.id, plan, importStorageBytes);
        assertLibraryCapacity(lockedCapacity);
        // Preferences are account-scoped, so a user-initiated Juno restore applies
        // the exported settings without changing account identity, plan, or billing.
        if (parsed.format === "juno" && junoPayload && isRecord(junoPayload.settings)) {
          const raw = junoPayload.settings;
          const theme = enumValue(raw.theme, ["LIGHT", "DARK", "SYSTEM"] as const);
          const update: Record<string, unknown> = {};
          if (theme) update.theme = theme;
          for (const key of [
            "accent",
            "defaultModel",
            "customInstructions",
            "responseLanguage",
            "uiLocale",
            "personality",
            "backgroundProviderMode",
            "backgroundProviderSelected",
            "voiceId",
            "actionApprovalPolicy",
          ]) {
            if (typeof raw[key] === "string") update[key] = raw[key];
          }
          for (const key of ["memoryEnabled", "emailBudgetAlerts", "emailWeeklyDigest", "lockdownMode", "spendCapDisabled"]) {
            if (typeof raw[key] === "boolean") update[key] = raw[key];
          }
          if (Array.isArray(raw.favoriteModels)) update.favoriteModels = raw.favoriteModels.filter((value): value is string => typeof value === "string").slice(0, 200);
          if (Array.isArray(raw.blockedConnectors)) update.blockedConnectors = raw.blockedConnectors.filter((value): value is string => typeof value === "string").slice(0, 200);
          if (typeof raw.monthlySpendCapEur === "number" && Number.isInteger(raw.monthlySpendCapEur) && raw.monthlySpendCapEur >= 0) {
            update.monthlySpendCapEur = raw.monthlySpendCapEur;
          }
          if (Object.keys(update).length > 0) {
            await tx.settings.upsert({ where: { userId: user.id }, create: { userId: user.id, ...update }, update });
          }
        }

        // Idempotency-light: title + createdAt identifies a conversation well enough
        // to make re-uploading the same archive a no-op. Seeding the set from the DB
        // and adding as we insert also dedupes repeats inside the ZIP itself.
        const [existing, existingProjects] = await Promise.all([
          tx.conversation.findMany({
            where: { userId: user.id },
            select: { id: true, clientRequestId: true, title: true, createdAt: true },
          }),
          tx.project.findMany({
            where: { userId: user.id },
            select: { id: true, importSourceId: true, name: true, createdAt: true },
          }),
        ]);
  const seen = new Set(existing.map((c) => `${c.createdAt.getTime()}\\0${c.title}`));
  const existingConversationByImportKey = new Map(
    existing.filter((conversation) => conversation.clientRequestId).map((conversation) => [conversation.clientRequestId!, conversation.id]),
  );
  const existingProjectByImportKey = new Map(
    existingProjects.filter((project) => project.importSourceId).map((project) => [project.importSourceId!, project.id]),
  );
  const existingProjectByNaturalKey = new Map(existingProjects.map((project) => [`${project.createdAt.getTime()}\\0${project.name}`, project.id]));

  const sourceIdToProjectId = new Map<string, string>();
  let projectsImported = 0;
  if (parsed.format === "juno" && junoPayload && Array.isArray(junoPayload.projects)) {
    for (const rawProject of junoPayload.projects) {
      if (!isRecord(rawProject)) continue;
      const exportedImportSourceId = stringValue(rawProject.importSourceId, 200);
      const sourceId = exportedImportSourceId?.startsWith("juno:")
        ? exportedImportSourceId.slice("juno:".length)
        : stringValue(rawProject.id, 200);
      const name = stringValue(rawProject.name, 200);
      if (!name) continue;
      const createdAt = dateValue(rawProject.createdAt);
      const updatedAt = dateValue(rawProject.updatedAt);
      const importSourceId = sourceId ? `juno:${sourceId}` : null;
      const existingProjectId =
        (importSourceId ? existingProjectByImportKey.get(importSourceId) : null) ??
        (createdAt ? existingProjectByNaturalKey.get(`${createdAt.getTime()}\\0${name}`) : null);
      if (existingProjectId) {
        if (sourceId) sourceIdToProjectId.set(sourceId, existingProjectId);
        continue;
      }
      const project = await tx.project.create({
        data: {
          userId: user.id,
          name,
          nameSource: "imported",
          instructions: stringValue(rawProject.instructions, 200_000) ?? "",
          starred: rawProject.starred === true,
          workDefaults: isRecord(rawProject.workDefaults) ? (rawProject.workDefaults as Prisma.InputJsonValue) : {},
          workDefaultsVersion: positiveInt(rawProject.workDefaultsVersion, 1),
          ...(importSourceId ? { importSourceId } : {}),
          ...(createdAt ? { createdAt } : {}),
          ...(updatedAt ? { updatedAt } : {}),
        },
        select: { id: true },
      });
      if (sourceId) sourceIdToProjectId.set(sourceId, project.id);
      projectsImported += 1;
    }
  }

  const sourceIdToConversationId = new Map<string, string>();
  const sourceIdToMessageId = new Map<string, string>();
  const sourceAttachmentToMessageId = new Map<string, string>();
  const sourceMessageToConversationId = new Map<string, string>();
  const hydrateExistingConversation = async (convo: (typeof parsed.conversations)[number], conversationId: string) => {
    const rows = await tx.message.findMany({
      where: { conversationId },
      orderBy: { createdAt: "asc" },
      select: { id: true, clientId: true },
    });
    convo.messages.forEach((message, index) => {
      const row = (message.sourceId && rows.find((candidate) => candidate.clientId === `juno:${message.sourceId}`)) ?? rows[index];
      if (!row || !message.sourceId) return;
      sourceIdToMessageId.set(message.sourceId, row.id);
      sourceMessageToConversationId.set(message.sourceId, conversationId);
    });
    if (convo.sourceId) sourceIdToConversationId.set(convo.sourceId, conversationId);
  };
  let imported = 0;
  let skipped = parsed.skipped;
  // Parents are inserted before their exported branch children whenever the
  // export provides a source id. If a hand-edited export contains a cycle, the
  // first unresolved item is imported without a pointer rather than looping.
  const pending = [...parsed.conversations];
  while (pending.length > 0) {
    const index = pending.findIndex(
      (convo) =>
        !convo.forkedFromSourceId ||
        sourceIdToConversationId.has(convo.forkedFromSourceId) ||
        !pending.some((candidate) => candidate.sourceId === convo.forkedFromSourceId),
    );
    const convo = pending.splice(index < 0 ? 0 : index, 1)[0];
    const key = `${convo.createdAt.getTime()}\\0${convo.title}`;
    const importKey = convo.sourceId ? `juno:${convo.sourceId}` : null;
    const existingConversationId = importKey ? existingConversationByImportKey.get(importKey) : null;
    if (existingConversationId) {
      await hydrateExistingConversation(convo, existingConversationId);
      skipped += 1;
      continue;
    }
    if (seen.has(key)) {
      const naturalMatch = existing.find((candidate) => `${candidate.createdAt.getTime()}\\0${candidate.title}` === key);
      if (naturalMatch) await hydrateExistingConversation(convo, naturalMatch.id);
      skipped += 1;
      continue;
    }
    seen.add(key);

    const lastMessage = convo.messages[convo.messages.length - 1];
    const created = await tx.conversation.create({
      data: {
        userId: user.id,
        origin: "import",
        ...(importKey ? { clientRequestId: importKey } : {}),
        title: convo.title,
        titleSource: convo.titleSource ?? "imported",
        model: convo.model ?? "claude-opus-4-8",
        kind: convo.kind ?? "chat",
        pinned: convo.pinned === true,
        archivedAt: convo.archivedAt ?? null,
        activeConnectors: convo.activeConnectors ?? [],
        codeWorkspaceName: convo.codeWorkspaceName ?? null,
        codeWorkspacePath: convo.codeWorkspacePath ?? null,
        codeWorkspaceKey: convo.codeWorkspaceKey ?? null,
        forkedFromId: convo.forkedFromSourceId ? sourceIdToConversationId.get(convo.forkedFromSourceId) ?? null : null,
        projectId: convo.projectSourceId ? sourceIdToProjectId.get(convo.projectSourceId) ?? null : null,
        createdAt: convo.createdAt,
        lastMessageAt: convo.lastMessageAt ?? lastMessage.createdAt,
        messages: {
          create: convo.messages.map((message) => ({
            ...(message.sourceId ? { clientId: `juno:${message.sourceId}` } : {}),
            role: message.role === "user" ? Role.USER : Role.ASSISTANT,
            // Same encryption-at-rest path as live chats (message-crypto.ts).
            content: encryptMessageText(message.content),
            ...(message.reasoning ? { reasoning: encryptMessageText(message.reasoning) } : {}),
            ...(message.reasoningParts?.length
              ? { reasoningParts: message.reasoningParts.map((part) => encryptMessageText(part)) as unknown as Prisma.InputJsonValue }
              : {}),
            ...(message.model ? { model: message.model } : {}),
            ...(message.feedback ? { feedback: message.feedback } : {}),
            ...(message.promptTokens != null ? { promptTokens: message.promptTokens } : {}),
            ...(message.completionTokens != null ? { completionTokens: message.completionTokens } : {}),
            ...(message.costMicroUsd != null ? { costMicroUsd: message.costMicroUsd } : {}),
            ...(message.sources !== null && message.sources !== undefined ? { sources: jsonInput(message.sources) } : {}),
            ...(message.activity !== null && message.activity !== undefined ? { activity: jsonInput(message.activity) } : {}),
            createdAt: message.createdAt,
          })),
        },
      },
    });
    const createdMessages = await tx.message.findMany({
      where: { conversationId: created.id },
      orderBy: { createdAt: "asc" },
      select: { id: true },
    });
    convo.messages.forEach((message, messageIndex) => {
      const targetId = createdMessages[messageIndex]?.id;
      if (!targetId) return;
      if (message.sourceId) {
        sourceIdToMessageId.set(message.sourceId, targetId);
        sourceMessageToConversationId.set(message.sourceId, created.id);
      }
      for (const attachmentId of message.attachmentSourceIds ?? []) {
        if (!sourceAttachmentToMessageId.has(attachmentId)) sourceAttachmentToMessageId.set(attachmentId, targetId);
      }
    });
    if (convo.sourceId) sourceIdToConversationId.set(convo.sourceId, created.id);
    if (importKey) existingConversationByImportKey.set(importKey, created.id);
    imported += 1;
  }

  // Restore the memory graph after conversations exist so project and source
  // message pointers can be translated to this account's new ids. The source
  // key is separate from the user-visible provenance fields and makes a second
  // import an update-free no-op rather than a duplicate belief.
  let memoriesImported = 0;
  const sourceIdToMemoryId = new Map<string, string>();
  if (parsed.format === "juno" && junoPayload && Array.isArray(junoPayload.memories)) {
    const existingMemories = await tx.memoryEntry.findMany({
      where: { userId: user.id },
      select: { id: true, importSourceId: true },
    });
    const existingMemoryByImportKey = new Map(
      existingMemories.filter((memory) => memory.importSourceId).map((memory) => [memory.importSourceId!, memory.id]),
    );
    const pendingSupersession: Array<{ id: string; sourceId: string }> = [];
    const importedSuppressions = [...importedSuppressionsSnapshot];
    for (const rawMemory of junoPayload.memories.slice(0, 50_000)) {
      if (!isRecord(rawMemory)) continue;
      const content = stringValue(rawMemory.content, 500);
      if (!content) continue;
      const sourceId = stringValue(rawMemory.id, 200);
      const exportedImportSourceId = stringValue(rawMemory.importSourceId, 200);
      const importSourceId = exportedImportSourceId?.startsWith("juno:memory:")
        ? exportedImportSourceId
        : sourceId ? `juno:memory:${sourceId}` : null;
      const existingMemoryId = importSourceId ? existingMemoryByImportKey.get(importSourceId) : null;
      if (existingMemoryId) {
        if (sourceId) sourceIdToMemoryId.set(sourceId, existingMemoryId);
        continue;
      }
      const source = enumValue(rawMemory.source, ["AUTO", "MANUAL"] as const) ?? "AUTO";
      const kind = enumValue(rawMemory.kind, ["FACT", "SUPPRESSION"] as const) ?? "FACT";
      const outcome = await guardedMemoryWrite({
        content,
        kind,
        loadSuppressions: async () => importedSuppressions,
        write: (checked) => tx.memoryEntry.create({
          data: {
            userId: user.id,
            content: checked,
            source,
            kind,
            category: stringValue(rawMemory.category, 100),
            projectId: stringValue(rawMemory.projectId, 200)
              ? sourceIdToProjectId.get(stringValue(rawMemory.projectId, 200)!) ?? null
              : null,
            sourceRef: stringValue(rawMemory.sourceRef, 500),
            sourceMessageId: stringValue(rawMemory.sourceMessageId, 200)
              ? sourceIdToMessageId.get(stringValue(rawMemory.sourceMessageId, 200)!) ?? null
              : null,
            confidence: nullableFloat(rawMemory.confidence) ?? 0.5,
            status: stringValue(rawMemory.status, 50) ?? "active",
            reason: stringValue(rawMemory.reason, 2_000),
            expiresAt: dateValue(rawMemory.expiresAt),
            lastUsedAt: dateValue(rawMemory.lastUsedAt),
            lastVerifiedAt: dateValue(rawMemory.lastVerifiedAt),
            normalized: stringValue(rawMemory.normalized, 200_000),
            ...(importSourceId ? { importSourceId } : {}),
            ...(dateValue(rawMemory.createdAt) ? { createdAt: dateValue(rawMemory.createdAt)! } : {}),
            ...(dateValue(rawMemory.updatedAt) ? { updatedAt: dateValue(rawMemory.updatedAt)! } : {}),
          },
          select: { id: true },
        }),
      });
      if (!outcome.ok) continue;
      const created = outcome.value;
      if (kind === "SUPPRESSION") importedSuppressions.push(content);
      if (sourceId) {
        sourceIdToMemoryId.set(sourceId, created.id);
        existingMemoryByImportKey.set(importSourceId!, created.id);
      }
      const supersededById = stringValue(rawMemory.supersededById, 200);
      if (supersededById) pendingSupersession.push({ id: created.id, sourceId: supersededById });
      memoriesImported += 1;
    }
    for (const pending of pendingSupersession) {
      const supersededById = sourceIdToMemoryId.get(pending.sourceId);
      if (supersededById) await tx.memoryEntry.update({ where: { id: pending.id, userId: user.id }, data: { supersededById } });
    }

    const rawSummary = isRecord(junoPayload.memorySummary) ? junoPayload.memorySummary : null;
    const summaryContent = rawSummary ? stringValue(rawSummary.content, 500_000) : null;
    if (rawSummary && summaryContent) {
      await tx.memorySummary.upsert({
        where: { userId: user.id },
        create: {
          userId: user.id,
          content: summaryContent,
          entryCount: nullableInt(rawSummary.entryCount) ?? memoriesImported,
          ...(dateValue(rawSummary.createdAt) ? { createdAt: dateValue(rawSummary.createdAt)! } : {}),
          ...(dateValue(rawSummary.updatedAt) ? { updatedAt: dateValue(rawSummary.updatedAt)! } : {}),
        },
        update: {
          content: summaryContent,
          entryCount: nullableInt(rawSummary.entryCount) ?? memoriesImported,
        },
      });
    }
  }

    let attachmentsImported = 0;
    for (const prepared of preparedAttachments) {
      const rawAttachment = prepared.raw;
      const sourceAttachmentId = stringValue(rawAttachment.idempotencyKey, 200) ?? stringValue(rawAttachment.id, 200);
      const importKey = sourceAttachmentId
        ? sourceAttachmentId.startsWith("juno:") ? sourceAttachmentId : `juno:${sourceAttachmentId}`
        : null;
      if (importKey && existingAttachmentByImportKey.has(importKey)) {
        attachmentsSkipped += 1;
        continue;
      }
      const sourceMessageId = stringValue(rawAttachment.messageId, 200);
      const messageId = sourceMessageId
        ? sourceIdToMessageId.get(sourceMessageId) ?? null
        : sourceAttachmentId
          ? sourceAttachmentToMessageId.get(sourceAttachmentId) ?? null
          : null;
      const conversationId = stringValue(rawAttachment.conversationId, 200)
        ? sourceIdToConversationId.get(stringValue(rawAttachment.conversationId, 200)!) ?? null
        : messageId && sourceMessageId
          ? sourceMessageToConversationId.get(sourceMessageId) ?? null
          : null;
      const deletedAt = dateValue(rawAttachment.deletedAt);
      const created = await tx.attachment.create({
        data: {
          userId: user.id,
          conversationId,
          messageId,
          projectId: stringValue(rawAttachment.projectId, 200)
            ? sourceIdToProjectId.get(stringValue(rawAttachment.projectId, 200)!) ?? null
            : null,
          kind: prepared.plan.kind,
          fileName: prepared.plan.fileName,
          mimeType: prepared.plan.storedMime,
          size: prepared.bytes.length,
          storageKey: prepared.currentKey,
          extractedText: stringValue(rawAttachment.extractedText, 200_000) ?? prepared.plan.extractedText,
          width: nullableInt(rawAttachment.width),
          height: nullableInt(rawAttachment.height),
          ...(importKey ? { idempotencyKey: importKey } : {}),
          version: positiveInt(rawAttachment.version, 1),
          origin: "import",
          parserState: deletedAt ? "deleted" : prepared.plan.kind === "FILE" ? "queued" : "skipped",
          deletedAt,
          versions: { create: prepared.snapshotRows },
        },
        select: { id: true, projectId: true, fileName: true, mimeType: true },
      });
      const attached = await tx.importObject.updateMany({
        where: { id: { in: prepared.objectIds }, userId: user.id, importRunId: importRun.id, leaseToken: importRun.leaseToken, status: "uploaded" },
        data: { status: "attached" },
      });
      if (attached.count !== prepared.objectIds.length) throw new Error("Import object ledger did not attach every staged object.");
      if (!deletedAt && prepared.plan.kind === "FILE") {
        scheduledIngests.push({
          userId: user.id,
          attachmentId: created.id,
          projectId: created.projectId,
          fileName: created.fileName,
          mimeType: created.mimeType,
          bytes: prepared.bytes,
        });
      }
      attachmentsImported += 1;
      if (importKey) existingAttachmentByImportKey.set(importKey, created.id);
    }

    const resultPayload = { imported, skipped, format: parsed.format, projectsImported, memoriesImported, attachmentsImported, attachmentsSkipped };
    const completed = await tx.importRun.updateMany({
      where: { id: importRun.id, userId: user.id, status: "applying", leaseToken: importRun.leaseToken },
      data: { status: "completed", result: resultPayload, error: null, leaseExpiresAt: null, completedAt: new Date() },
    });
    if (completed.count !== 1) throw new Error("Import run was lost before completion.");
    return resultPayload;
      },
      {
        maxWait: 15_000,
        timeout: 120_000,
        isolationLevel: Prisma.TransactionIsolationLevel.Serializable,
      },
    );
    await cleanupImportRun(user.id, importRun.id, importRun.leaseToken).catch((cleanupError) => {
      console.error("[import] post-commit cleanup of skipped objects failed", {
        importRunId: importRun.id,
        message: cleanupError instanceof Error ? cleanupError.message : String(cleanupError),
      });
    });
    for (const ingest of scheduledIngests) {
      try {
        scheduleIngest(ingest);
      } catch (error) {
        // The attachment is committed and the recovery worker can re-enqueue
        // queued files; a scheduling failure must not turn a successful import
        // into a compensating delete after the transaction has committed.
        console.error("[import] could not schedule knowledge ingest", {
          attachmentId: ingest.attachmentId,
          message: error instanceof Error ? error.message : String(error),
        });
      }
    }
    return NextResponse.json(result);
  } catch (error) {
    await prisma.importRun
      .updateMany({
        where: { id: importRun.id, userId: user.id, status: "applying", leaseToken: importRun.leaseToken },
        data: {
          status: "failed",
          error: (error instanceof Error ? error.message : String(error)).slice(0, 4_000),
          leaseExpiresAt: new Date(),
        },
      })
      .catch((markError) => {
        console.error("[import] could not mark failed import run", {
          importRunId: importRun.id,
          message: markError instanceof Error ? markError.message : String(markError),
        });
      });
    await cleanupImportRun(user.id, importRun.id, importRun.leaseToken).catch((cleanupError) => {
      console.error("[import] durable object compensation failed", {
        importRunId: importRun.id,
        message: cleanupError instanceof Error ? cleanupError.message : String(cleanupError),
      });
    });
    await cleanupStorageKeys(uploadedStorageKeys);
    if (error instanceof LibraryQuotaExceededError) {
      return NextResponse.json(
        {
          error: error.message,
          code: "LIBRARY_QUOTA_EXCEEDED",
          usedBytes: error.capacity.usedBytes,
          quotaBytes: error.capacity.quotaBytes,
          remainingBytes: error.capacity.remainingBytes,
        },
        { status: 413 },
      );
    }
    throw error;
  }
}
